// Generated by scripts/generate_build_info.py from the checked-out HEAD.
import "../src/sections/beta17-final-icon-polish-section.js";
import "../src/sections/beta-entry-section.js";
import "../src/sections/save-engine-section.js";
import "../src/sections/beta11-real-device-polish-section.js";
import "../src/sections/beta12-room-color-lock-section.js";
import "../src/sections/beta14-real-device-hotfix-section.js";
import "../src/sections/beta16-real-device-layout-section.js";
import "../src/sections/beta22-load-slots-hotfix-section.js";
import "../src/sections/beta24-energy-recovery-section.js";
import "../src/sections/beta25-real-device-fixes-section.js";
import "../src/sections/beta25-compatibility-section.js";
import "../src/sections/beta26-real-device-stability-section.js";
import "../src/sections/segnalazioni-section.js";
export const BUILD_INFO = Object.freeze({"generated":true,"integrationVersion":"1.4.20","dashboardVersion":"1.4.20","moduleVersion":14,"schemaVersion":4,"date":"2026-09-11T12:49:44+00:00","commit":"51f5e15622bf92dd5a461504bc2182363ced7d4a","assetHash":"f485a83aa964e3e6"});
