import assert from "node:assert/strict";
import test from "node:test";
import { createDefaultCardRegistry } from "../src/cards/registry.js";
import { normalizeEnergy, renderEnergyOverviewCard, renderEnergyFlowsCard, renderBatteryStatusEditor, validateEnergyOverviewConfig, validateBatteryStatusConfig } from "../src/cards/energy.js";

class Node { constructor(tag) { this.tagName = tag; this.children = []; this.attributes = {}; this.dataset = {}; this._text = ""; } append(...items) { this.children.push(...items); } setAttribute(k, v) { this.attributes[k] = String(v); } addEventListener(t, f) { this[`on${t}`] = f; } get textContent() { return this._text + this.children.map((c) => c.textContent).join(""); } set textContent(v) { this._text = String(v); this.children = []; } querySelectorAll(selector) { const out = []; const match = (n) => selector.startsWith(".") ? n.className?.split?.(" ").includes(selector.slice(1)) : n.tagName === selector; const walk = (n) => { if (match(n)) out.push(n); for (const c of n.children) walk(c); }; walk(this); return out; } }
globalThis.document = { createElement: (tag) => new Node(tag) };
const runtime = (states = {}) => ({ locale: "en-US", getEntityState: (id) => states[id] || null, interactions: { opened: [], openHistory(id, label) { this.opened.push([id, label]); } } });
const cfg = { productionEntityId: "sensor.pv", houseConsumptionEntityId: "sensor.house", gridImportEntityId: "sensor.import", gridExportEntityId: "sensor.export", batterySocEntityId: "sensor.soc", batteryPowerEntityId: "sensor.battery", batteryCapacityEntityId: "sensor.capacity", dailyProductionEntityId: "sensor.solar_day", peakProductionEntityId: "sensor.peak", dailyImportEntityId: "sensor.import_day", dailyExportEntityId: "sensor.export_day" };
const states = { "sensor.pv": { state: "3.2", attributes: { unit_of_measurement: "kW" } }, "sensor.house": { state: "2,4" }, "sensor.import": { state: "0.1" }, "sensor.export": { state: "0.9" }, "sensor.soc": { state: "81" }, "sensor.battery": { state: "-1.5" }, "sensor.capacity": { state: "7" }, "sensor.solar_day": { state: "18" }, "sensor.peak": { state: "4.4" }, "sensor.import_day": { state: "2" }, "sensor.export_day": { state: "8" } };

test("energy normalization returns normalized values and battery mode before rendering", () => { const n = normalizeEnergy(runtime(states), cfg); assert.equal(n.metrics.production.value, 3.2); assert.equal(n.metrics.house.value, 2.4); assert.equal(n.selfConsumption.value, 2.4); assert.equal(n.batteryMode, "discharging"); assert.equal(n.flows.battery, 1.5); });
test("energy normalization creates explicit unavailable states", () => { const n = normalizeEnergy(runtime({ "sensor.pv": { state: "unavailable" }, "sensor.house": { state: "bad" } }), { productionEntityId: "sensor.pv", houseConsumptionEntityId: "sensor.house", gridImportEntityId: "sensor.missing" }); assert.equal(n.metrics.production.status, "unavailable"); assert.equal(n.metrics.house.status, "malformed"); assert.equal(n.metrics.import.status, "missing-entity"); assert.equal(n.metrics.export.status, "missing-config"); });
test("energy validators cover missing configuration, templates, and malformed option types", () => { const errors = validateEnergyOverviewConfig({ productionEntityId: "{{ states }}", powerUnit: 1 }); assert(errors.some((e) => e.field === "config.houseConsumptionEntityId")); assert(errors.some((e) => /cannot contain templates/.test(e.message))); assert(errors.some((e) => e.field === "config.powerUnit")); assert.deepEqual(validateBatteryStatusConfig({ batterySocEntityId: "sensor.soc", batteryPowerEntityId: "sensor.p" }), []); });
test("energy cards render normalized values and unavailable text", () => { const card = { id: "e", title: "Energy", type: "energy-overview", config: cfg }; const node = renderEnergyOverviewCard(card, runtime(states)); assert.match(node.textContent, /Energy/); assert.match(node.textContent, /3.2 kW/); const bad = renderEnergyOverviewCard({ ...card, config: {} }, runtime()); assert.match(bad.textContent, /Unavailable/); });
test("energy flow rendering uses directional arrows and normalized values only", () => { const node = renderEnergyFlowsCard({ id: "f", title: "Flows", config: cfg }, runtime(states)); assert.match(node.textContent, /PV→House/); assert.match(node.textContent, /1.5 kW/); assert.doesNotMatch(node.textContent, /sensor\./); });
test("energy overview interactions open history for available metrics only", () => { const rt = runtime(states); const node = renderEnergyOverviewCard({ id: "e", title: "Energy", config: cfg }, rt); node.querySelectorAll("button")[0].onclick(); assert.deepEqual(rt.interactions.opened[0], ["sensor.pv", "Production"]); });
test("energy structured editor patches fields and surfaces validation errors", () => { const patches = []; const editor = renderBatteryStatusEditor(globalThis.document, { id: "b", config: { batterySocEntityId: "sensor.old" } }, { updateCardConfigPatch: (id, patch) => patches.push([id, patch]) }, [{ message: "Battery SOC is required" }]); const input = editor.querySelectorAll("input")[0]; input.value = "sensor.new"; input.oninput(); assert.deepEqual(patches[0], ["b", { batterySocEntityId: "sensor.new" }]); assert.match(editor.textContent, /Battery SOC is required/); });
test("built-in registry includes all Phase 11 energy plugins", () => { assert.deepEqual(createDefaultCardRegistry().types(), ["battery-status", "energy-flows", "energy-overview", "grid-status", "home-summary", "legacy-panel", "solar-production", "weather-current", "weather-forecast"]); });
