import assert from "node:assert/strict";
import test from "node:test";
import { renderCard } from "../src/render/card-renderer.js";
import { renderCardForm } from "../src/editor/card-form.js";
import { EditorController } from "../src/editor/editor-controller.js";
import { DashboardModernStore } from "../src/state.js";
import { WEATHER_CONDITIONS, defaultWeatherCurrentConfig, defaultWeatherForecastConfig, normalizeWeather, validateWeatherCurrentConfig, validateWeatherForecastConfig, weatherConditionMeta } from "../src/cards/weather.js";
import { defaultHomeSummaryConfig, nextHomeSummaryItemKey, normalizeHomeSummaryItems, normalizeSummaryMetric, validateHomeSummaryConfig } from "../src/cards/home-summary.js";
import { cardRendererTypes } from "../src/render/card-renderer.js";

class Node { constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.dataset={};this.className="";this._text="";this.listeners={};this.disabled=false;this.value="";this.type="";this.checked=false;this.min="";this.max="";} append(...i){this.children.push(...i)} setAttribute(k,v){this.attributes[k]=String(v)} addEventListener(t,f){this.listeners[t]=f;this[`on${t}`]=f} click(){this.listeners.click?.({})} get textContent(){return this._text+this.children.map(c=>c.textContent).join("")} set textContent(v){this._text=String(v);this.children=[]} querySelectorAll(sel){const out=[];const match=n=>sel.startsWith(".")?n.className?.split?.(" ").includes(sel.slice(1)):sel.startsWith("[")?Boolean(n.dataset?.editorField):n.tagName===sel;const walk=n=>{if(match(n))out.push(n);for(const c of n.children)walk(c)};walk(this);return out;} }
globalThis.document = { createElement: (tag) => new Node(tag) };
const states = { "weather.home": { entity_id:"weather.home", state:"rainy", last_updated:"2026-07-21T10:00:00Z", attributes:{ temperature:21.5, humidity:67, wind_speed:12, forecast:[{datetime:"2026-07-22T00:00:00", condition:"sunny", temperature:29, templow:18},{datetime:"2026-07-23T00:00:00", condition:"cloudy", temperature:28}] } }, "sensor.luci": { state:"3" }, "sensor.decimal": { state:"2.5" }, "sensor.zero": { state:"0" }, "sensor.unknown": { state:"unknown" }, "sensor.unavailable": { state:"unavailable" }, "sensor.bad": { state:"abc" } };
const runtime = { locale:"it-IT", connectionStatus:"connected", getEntityState:(id)=>states[id], callService:()=>{ throw new Error("backend call during render"); }, interactions:{ openWeather(){}, openHistory(){} } };
const base = (config, type = "home-summary") => ({ id:"dash", title:"Dash", views:[{id:"v",title:"V",section_ids:["s"]}], sections:[{id:"s",title:"S",card_ids:["c"]}], cards:[{id:"c",title:"Card",type,config}] });

function storeWith(dashboard) { let saved = dashboard; const store = new DashboardModernStore({ replaceDashboard: async (_e, d) => { saved = d; return d; }, listDashboards: async () => [saved], getDashboard: async () => saved }, { entryIdResolver: async () => "e" }); store.setState({ entryId:"e", activeDashboard:dashboard, activeDashboardId:"dash", dashboards:[dashboard] }); return store; }

test("default configs contain only empty entity ids", () => { const cfg = defaultHomeSummaryConfig(); assert.deepEqual(cfg.items.map((i) => i.entityId), ["", "", "", "", ""]); assert.equal(defaultWeatherCurrentConfig().weatherEntityId, ""); assert.equal(defaultWeatherForecastConfig().weatherEntityId, ""); assert.equal(defaultWeatherCurrentConfig().outdoorTemperatureEntityId, ""); assert.equal(defaultWeatherCurrentConfig().outdoorHumidityEntityId, ""); assert.equal(defaultWeatherCurrentConfig().apparentTemperatureEntityId, ""); assert.equal(defaultWeatherCurrentConfig().updateTimestampEntityId, ""); });
test("weather condition mapping uses controlled icon ids and no emoji", () => { assert.equal(WEATHER_CONDITIONS.rainy.iconId, "rain"); assert.equal(WEATHER_CONDITIONS.partlycloudy.label, "Poco Nuvoloso"); assert.equal(JSON.stringify(WEATHER_CONDITIONS).match(/[☀️🌧️💡]/u), null); const unknown = weatherConditionMeta("space-weather"); assert.equal(unknown.iconId, "alert"); assert.notEqual(unknown.iconId, "sun"); assert.equal(unknown.label, "space weather"); assert.equal(JSON.stringify(unknown).match(/[☀️🌧️💡]/u), null); });
test("current weather rendering uses live state and safe local icons", () => { const node = renderCard({id:"w",title:"M",type:"weather-current",config:{weatherEntityId:"weather.home"}}, runtime); assert.match(node.textContent, /21,5°C/); assert.match(node.textContent, /Pioggia/); assert.match(node.textContent, /Umidità 67%/); assert.equal(node.attributes.role, "button"); assert.equal(node.querySelectorAll("svg").length, 1); });
test("forecast rendering handles arrays and item count", () => { const node = renderCard({id:"f",title:"P",type:"weather-forecast",config:{weatherEntityId:"weather.home",forecastItemCount:1,showForecast:true,unitDisplay:"°"}}, runtime); assert.match(node.textContent, /MERCOLEDÌ 22/); assert.doesNotMatch(node.textContent, /GIOVED/); assert.equal(node.querySelectorAll("svg").length, 1); });
test("weather unavailable states distinguish missing config entity unknown unavailable malformed", () => { assert.equal(normalizeWeather(runtime, {weatherEntityId:""}).status, "missing-config"); assert.equal(normalizeWeather(runtime, {weatherEntityId:"weather.missing"}).status, "missing-entity"); assert.equal(normalizeWeather({getEntityState:()=>({state:"unknown",attributes:{}})}, {weatherEntityId:"weather.x"}).status, "unknown"); assert.equal(normalizeWeather({getEntityState:()=>({state:"unavailable",attributes:{}})}, {weatherEntityId:"weather.x"}).status, "unavailable"); assert.equal(normalizeWeather({getEntityState:()=>({state:"sunny",attributes:"bad"})}, {weatherEntityId:"weather.x"}).status, "malformed-attributes"); });
test("locale-aware formatting", () => { const n = normalizeWeather({locale:"en-US",getEntityState:()=>states["weather.home"]}, {weatherEntityId:"weather.home"}); assert.equal(n.temperatureText, "21.5°C"); });
test("home summary normalizers handle numeric decimal zero unknown unavailable malformed and missing", () => { assert.equal(normalizeSummaryMetric(states["sensor.luci"]).display, "3"); assert.equal(normalizeSummaryMetric(states["sensor.decimal"], {locale:"it-IT", suffix:" kW"}).display, "2,5 kW"); assert.equal(normalizeSummaryMetric(states["sensor.zero"]).display, "0"); assert.equal(normalizeSummaryMetric(states["sensor.unknown"]).status, "unknown"); assert.equal(normalizeSummaryMetric(states["sensor.unavailable"]).status, "unavailable"); assert.equal(normalizeSummaryMetric(states["sensor.bad"]).status, "malformed"); assert.equal(normalizeSummaryMetric(null).status, "missing-entity"); });
test("home summary rendering does not show unavailable as zero", () => { const cfg = {title:"Quadro Avvisi",items:[{key:"u",label:"Bad",entityId:"sensor.unavailable",icon:"alert",accent:"danger",fallbackText:"—"}]}; const node = renderCard({id:"h",title:"Home",type:"home-summary",config:cfg}, runtime); assert.match(node.textContent, /Bad—/); assert.doesNotMatch(node.textContent, /Bad0/); });
test("home summary rendering uses normalized configured entity ids", () => { const cfg = {title:"Quadro Avvisi",items:[{key:"l",label:"Luci Accese",entityId:"sensor.luci",icon:"lights",accent:"solar"}]}; const items = normalizeHomeSummaryItems(runtime, cfg); assert.equal(items[0].display, "3"); const node = renderCard({id:"h",title:"Home",type:"home-summary",config:cfg}, runtime); assert.match(node.textContent, /Quadro Avvisi/); assert.match(node.textContent, /Luci Accese3/); assert.equal(node.querySelectorAll("button").length, 1); assert.equal(node.querySelectorAll("svg").length, 1); });

test("structured weather editors expose all options with typed values", () => { const current = {id:"wc",title:"Weather",type:"weather-current",config:{weatherEntityId:"",outdoorTemperatureEntityId:"",outdoorHumidityEntityId:"",apparentTemperatureEntityId:"",updateTimestampEntityId:"",showTitle:false,showSubtitle:false,unitDisplay:"°C"}}; const currentPatches=[]; const controller={updateCardConfigPatch:(_id,patch)=>currentPatches.push(patch)}; const currentForm = renderCardForm(document, current, controller, [], {}, undefined); for (const field of ["weatherEntityId", "outdoorTemperatureEntityId", "outdoorHumidityEntityId", "apparentTemperatureEntityId", "updateTimestampEntityId", "unitDisplay", "showTitle", "showSubtitle"]) assert.ok(currentForm.querySelectorAll("[data-editor-field]").some((n) => n.dataset.editorField === `card:wc:config.${field}`), field); const showTitle = currentForm.querySelectorAll("input").find((i) => i.dataset.editorField === "card:wc:config.showTitle"); showTitle.checked = true; showTitle.onchange(); assert.deepEqual(currentPatches.at(-1), {showTitle:true}); const forecast = {id:"wf",title:"Forecast",type:"weather-forecast",config:{weatherEntityId:"",showForecast:true,forecastItemCount:7,unitDisplay:"°"}}; const forecastPatches=[]; const forecastForm = renderCardForm(document, forecast, {updateCardConfigPatch:(_id,patch)=>forecastPatches.push(patch)}, [], {}, undefined); for (const field of ["weatherEntityId", "showForecast", "forecastItemCount", "unitDisplay"]) assert.ok(forecastForm.querySelectorAll("[data-editor-field]").some((n) => n.dataset.editorField === `card:wf:config.${field}`), field); const count = forecastForm.querySelectorAll("input").find((i) => i.dataset.editorField === "card:wf:config.forecastItemCount"); assert.equal(count.type, "number"); assert.equal(count.min, "1"); assert.equal(count.max, "10"); count.value = "4"; count.oninput(); assert.deepEqual(forecastPatches.at(-1), {forecastItemCount:4}); const showForecast = forecastForm.querySelectorAll("input").find((i) => i.dataset.editorField === "card:wf:config.showForecast"); showForecast.checked = false; showForecast.onchange(); assert.deepEqual(forecastPatches.at(-1), {showForecast:false}); });
test("validators reject unsafe invalid config remote icons colors and templates", () => { assert.ok(validateWeatherCurrentConfig({weatherEntityId:"{{ x }}"}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:11}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:7,showForecast:"yes"}).length); const errors = validateHomeSummaryConfig({items:[{key:"x",label:"{{bad}}",entityId:"",icon:"https://x/icon.svg",accent:"#fff"}]}); assert.ok(errors.some((e) => e.field === "config.items.0.entityId")); assert.ok(errors.some((e) => e.field === "config.items.0.icon")); assert.ok(errors.some((e) => e.field === "config.items.0.accent")); assert.ok(errors.some((e) => e.field === "config.items.0.label")); });

test("home summary duplicate keys are rejected and generated keys stay unique", () => { const duplicateErrors = validateHomeSummaryConfig({items:[{key:"dup",label:"A",entityId:"sensor.a",icon:"alert",accent:"green"},{key:"dup",label:"B",entityId:"sensor.b",icon:"lights",accent:"solar"}]}); assert.ok(duplicateErrors.some((e) => e.field === "config.items.1.key")); assert.equal(nextHomeSummaryItemKey([{key:"item-1"},{key:"item-3"}]), "item-2"); assert.equal(nextHomeSummaryItemKey([{key:"item-1"},{key:"item-2"},{key:"item-4"}]), "item-3"); assert.equal(nextHomeSummaryItemKey([{key:"item-2"},{key:"item-1"}]), "item-3"); });
test("structured item editor adds removes reorders and edits items", () => { const card = {id:"c",title:"Home",type:"home-summary",config:{title:"T",items:[{key:"a",label:"A",entityId:"sensor.a",icon:"alert",accent:"green"},{key:"b",label:"B",entityId:"sensor.b",icon:"lights",accent:"solar"}]}}; const patches=[]; const controller={updateCardConfigPatch:(_id,patch)=>patches.push(patch)}; const form = renderCardForm(document, card, controller, [], {}, undefined); const inputs = form.querySelectorAll("input"); inputs.find((i) => i.dataset.editorField === "card:c:config.items.0.label").value = "AA"; inputs.find((i) => i.dataset.editorField === "card:c:config.items.0.label").oninput(); assert.deepEqual(patches.at(-1).items[0].label, "AA"); form.querySelectorAll("button").find((b) => b.textContent === "↓").click(); assert.equal(patches.at(-1).items[0].key, "b"); form.querySelectorAll("button").find((b) => b.textContent === "Remove").click(); assert.equal(patches.at(-1).items.length, 1); form.querySelectorAll("button").find((b) => b.textContent === "Add item").click(); assert.equal(patches.at(-1).items.length, 3); assert.equal(patches.at(-1).items.at(-1).key, "item-1"); });

test("missing weather entity configuration blocks save and correction enables save", async () => { const dashboard = base(defaultWeatherCurrentConfig(), "weather-current"); const store = storeWith(dashboard); const controller = new EditorController(store); await controller.enter(); assert.equal(await controller.save(), false); assert.equal(store.state.activeDashboard, dashboard); assert.ok(store.state.editor.validationErrors.some((e) => e.field === "card:c:config.weatherEntityId")); controller.updateCardConfigPatch("c", { weatherEntityId: "weather.home" }); assert.equal(store.state.editor.validationErrors.length, 0); assert.equal(await controller.save(), true); assert.equal(store.state.activeDashboard.cards[0].config.weatherEntityId, "weather.home"); });
test("missing required entity ids block save, advanced JSON validates, correction enables save without mutating activeDashboard early", async () => { const dashboard = base(defaultHomeSummaryConfig()); const store = storeWith(dashboard); const controller = new EditorController(store); await controller.enter(); assert.equal(await controller.save(), false); assert.equal(store.state.activeDashboard, dashboard); assert.ok(store.state.editor.validationErrors.some((e) => e.field === "card:c:config.items.0.entityId")); controller.updateCardConfig("c", JSON.stringify({title:"Quadro",items:[{key:"l",label:"Luci",entityId:"sensor.luci",icon:"lights",accent:"solar"}]})); assert.equal(store.state.editor.validationErrors.length, 0); assert.equal(await controller.save(), true); assert.equal(store.state.activeDashboard.cards[0].config.items[0].entityId, "sensor.luci"); });
test("built-in plugin types are registered", () => { assert.deepEqual(cardRendererTypes(), ["alarm-control", "alert-summary", "automation-control", "battery-status", "binary-sensor-status", "button-control", "camera-status", "climate-control", "cover-control", "device-tracker-status", "energy-flows", "energy-overview", "fan-control", "generic-appliance", "grid-status", "home-summary", "input-boolean-control", "input-number-control", "input-select-control", "legacy-panel", "light-control", "lock-control", "media-player-control", "person-status", "quick-action", "scene-control", "script-control", "sensor-status", "solar-production", "switch-control", "vacuum-control", "weather-current", "weather-forecast", "weather-hero"]); });
