import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createDefaultCardRegistry } from "../src/cards/registry.js";
import { createDashboardPayload } from "../src/app.js";
import { normalizeCardLayout } from "../src/layout.js";
import { defaultBrandingConfig, defaultSectionContract, navigationContract, PLUGIN_SCHEMA_FIELDS, THEME_TOKENS } from "../src/contracts.js";
import { buildQuickActionServicePayload, calculateAlertSummary, defaultWeatherHeroConfig, mapApplianceStatus, renderAlertSummaryEditor, renderGenericApplianceCard, renderQuickActionEditor, renderWeatherHeroCard, validateAlertSummaryConfig } from "../src/cards/home-foundation.js";

function installDom(){global.document={createElement(tag){return {tagName:tag.toUpperCase(),children:[],dataset:{},style:{setProperty(k,v){this[k]=v}},attributes:{},className:"",_text:"",append(...n){this.children.push(...n)},get textContent(){return this._text+this.children.map(c=>c.textContent).join("")},set textContent(v){this._text=String(v);this.children=[]},prepend(...n){this.children.unshift(...n)},setAttribute(k,v){this.attributes[k]=String(v)},addEventListener(t,f){this.listeners=this.listeners||{};this.listeners[t]=f;this[`on${t}`]=f;}}}}}

test("legacy parity inventory exists and covers required components",()=>{const doc=readFileSync(new URL("../../../../docs/LEGACY_PARITY_INVENTORY.md",import.meta.url),"utf8"); for(const term of ["weather hero","alert summary","quick actions","generic-appliance","EV/wallbox","setup wizard","multilingual support"]) assert.match(doc,new RegExp(term,"i"));});
test("default first dashboard uses registered card types only and no placeholder",()=>{const reg=createDefaultCardRegistry(); const d=createDashboardPayload({id:"main",title:"Home"}); assert.equal(JSON.stringify(d).includes("dashboardmodern-placeholder"),false); for(const c of d.cards) assert.ok(reg.get(c.type), c.type);});
test("branding and theme contracts are persistable config",()=>{const c=defaultBrandingConfig("Casa"); assert.equal(c.branding.title,"Casa"); assert.ok(PLUGIN_SCHEMA_FIELDS.genericAppliance.includes("primaryStateEntityId")); assert.equal(THEME_TOKENS.green,"#22c55e");});
test("weather card configuration states are polished",()=>{installDom(); let node=renderWeatherHeroCard({title:"Weather",config:defaultWeatherHeroConfig()},{getEntityState(){return null}}); assert.equal(node.textContent.includes("Card type"),false); node=renderWeatherHeroCard({title:"Weather",config:{weatherEntityId:"weather.home"}},{getEntityState(){return null}}); assert.equal(node.textContent.includes("not found"),true);});
test("alert summary calculations",()=>{const rt={getEntityState:id=>({a:{state:"on"},b:{state:"off"},bat:{state:"15"}}[id]||null)}; const rows=calculateAlertSummary(rt,{alerts:[{title:"Lights",entityIds:["a","b"],condition:"on"},{title:"Battery",entityIds:["bat"],condition:"below",value:20}]}); assert.deepEqual(rows.map(r=>r.count),[1,1]);});
test("quick action service payload",()=>{const p=buildQuickActionServicePayload({action:{domain:"light",service:"turn_on",target:{entity_id:"light.kitchen"},serviceData:{brightness:100}}}); assert.deepEqual(p.data,{brightness:100,entity_id:"light.kitchen"});});
test("generic appliance status mapping and unavailable state",()=>{assert.equal(mapApplianceStatus("run",{run:"Running"}),"Running"); installDom(); const n=renderGenericApplianceCard({title:"Washer",config:{primaryStateEntityId:"sensor.washer"}},{getEntityState(){return {state:"unavailable"}}}); assert.equal(n.textContent.includes("unavailable"),true);});
test("responsive layout contract and safe unknown fallback/editor schema",()=>{const reg=createDefaultCardRegistry(); assert.ok(reg.get("weather-hero").editor); assert.ok(reg.get("alert-summary").editor); const layout=normalizeCardLayout({layout:{desktop:{columns:6,rows:2},tablet:{columns:4,rows:2},mobile:{columns:2,rows:2}}}); assert.equal(layout.status,"valid");});

test("quick action editor updates nested action fields",()=>{installDom();const patches=[];const card={id:"qa",title:"Action",config:{action:{domain:"",service:"",target:{entity_id:""},serviceData:{},confirmation:false}}};const form=renderQuickActionEditor(document,card,{updateCardConfigPatch:(_id,patch)=>patches.push(patch)});const fields=form.children.flatMap((label)=>label.children||[]);const domain=fields.find((node)=>node.dataset?.editorField==="card:qa:config.action.domain");domain.value="light";domain.listeners?.input?.();assert.equal(patches.at(-1).action.domain,"light");const service=fields.find((node)=>node.dataset?.editorField==="card:qa:config.action.service");service.value="turn_on";service.listeners?.input?.();assert.equal(patches.at(-1).action.service,"turn_on");const target=fields.find((node)=>node.dataset?.editorField==="card:qa:config.action.target.entity_id");target.value="light.kitchen";target.listeners?.input?.();assert.equal(patches.at(-1).action.target.entity_id,"light.kitchen");const payload=buildQuickActionServicePayload({action:{domain:"light",service:"turn_on",target:{entity_id:"light.kitchen"},serviceData:{brightness:55},confirmation:true}});assert.deepEqual(payload,{domain:"light",service:"turn_on",data:{brightness:55,entity_id:"light.kitchen"},confirmation:true});});

test("alert summary JSON editor preserves invalid text and keeps alerts arrays",()=>{installDom();const card={id:"alerts",config:{alerts:[{id:"a",title:"A",entityIds:["light.a"],condition:"on"}]}};const states=[];let controller={state:{fieldText:{},validationErrors:[]},store:{setState(update){states.push(update);controller.state=update.editor;}},updateCardConfigPatch(_id,patch){states.push({patch});}};let form=renderAlertSummaryEditor(document,card,controller,[],{});let textarea=form.children[0].children.find((node)=>node.tagName==="TEXTAREA");textarea.value='[{"id":"b","title":"B","entityIds":[],"condition":"on"},{"id":"c","title":"C","entityIds":[],"condition":"on"}]';textarea.listeners.input({target:textarea});assert.equal(Array.isArray(states.find((item)=>item.patch)?.patch.alerts),true);assert.equal(validateAlertSummaryConfig({alerts:states.find((item)=>item.patch)?.patch.alerts}).length,0);textarea.value='{bad';textarea.listeners.input({target:textarea});assert.equal(controller.state.fieldText["card:alerts:config.alerts"],"{bad");assert.deepEqual(card.config.alerts,[{id:"a",title:"A",entityIds:["light.a"],condition:"on"}]);form=renderAlertSummaryEditor(document,card,controller,[],controller.state.fieldText);textarea=form.children[0].children.find((node)=>node.tagName==="TEXTAREA");assert.equal(textarea.value,"{bad");textarea.value='[{"id":"a","title":"Edited","entityIds":[],"condition":"on"}]';textarea.listeners.input({target:textarea});assert.equal(states.at(-2).patch.alerts[0].title,"Edited");assert.equal(controller.state.fieldText["card:alerts:config.alerts"],undefined);});

test("section and navigation contracts derive bottom navigation from enabled visible sections",()=>{const sections=[defaultSectionContract("energy","Energy"),{...defaultSectionContract("security","Security"),order:-1,badge:{entityId:"binary_sensor.door"}},{...defaultSectionContract("server","Server"),enabled:false}];const nav=navigationContract(sections);assert.deepEqual(nav.entries.map((entry)=>entry.id),["security","energy"]);assert.equal(nav.entries[0].badge.entityId,"binary_sensor.door");});
