import assert from "node:assert/strict";
import test from "node:test";
import { renderCard } from "../src/render/card-renderer.js";
import { renderCardForm } from "../src/editor/card-form.js";
import { EditorController } from "../src/editor/editor-controller.js";
import { DashboardModernStore } from "../src/state.js";
import { WEATHER_CONDITIONS, defaultWeatherCurrentConfig, normalizeWeather, validateWeatherCurrentConfig, validateWeatherForecastConfig } from "../src/cards/weather.js";
import { defaultHomeSummaryConfig, normalizeHomeSummaryItems, normalizeSummaryMetric, validateHomeSummaryConfig } from "../src/cards/home-summary.js";
import { cardRendererTypes } from "../src/render/card-renderer.js";

class Node { constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.dataset={};this.className="";this._text="";this.listeners={};this.disabled=false;this.value="";this.type="";} append(...i){this.children.push(...i)} setAttribute(k,v){this.attributes[k]=String(v)} addEventListener(t,f){this.listeners[t]=f;this[`on${t}`]=f} click(){this.listeners.click?.({})} get textContent(){return this._text+this.children.map(c=>c.textContent).join("")} set textContent(v){this._text=String(v);this.children=[]} querySelectorAll(sel){const out=[];const match=n=>sel.startsWith(".")?n.className?.split?.(" ").includes(sel.slice(1)):sel.startsWith("[")?Boolean(n.dataset?.editorField):n.tagName===sel;const walk=n=>{if(match(n))out.push(n);for(const c of n.children)walk(c)};walk(this);return out;} }
globalThis.document = { createElement: (tag) => new Node(tag) };
const states = { "weather.home": { entity_id:"weather.home", state:"rainy", last_updated:"2026-07-21T10:00:00Z", attributes:{ temperature:21.5, humidity:67, wind_speed:12, forecast:[{datetime:"2026-07-22T00:00:00", condition:"sunny", temperature:29, templow:18},{datetime:"2026-07-23T00:00:00", condition:"cloudy", temperature:28}] } }, "sensor.luci": { state:"3" }, "sensor.decimal": { state:"2.5" }, "sensor.zero": { state:"0" }, "sensor.unknown": { state:"unknown" }, "sensor.unavailable": { state:"unavailable" }, "sensor.bad": { state:"abc" } };
const runtime = { locale:"it-IT", connectionStatus:"connected", getEntityState:(id)=>states[id], callService:()=>{ throw new Error("backend call during render"); }, interactions:{ openWeather(){}, openHistory(){} } };
const base = (config) => ({ id:"dash", title:"Dash", views:[{id:"v",title:"V",section_ids:["s"]}], sections:[{id:"s",title:"S",card_ids:["c"]}], cards:[{id:"c",title:"Home",type:"home-summary",config}] });

function storeWith(dashboard) { let saved = dashboard; const store = new DashboardModernStore({ replaceDashboard: async (_e, d) => { saved = d; return d; }, listDashboards: async () => [saved], getDashboard: async () => saved }, { entryIdResolver: async () => "e" }); store.setState({ entryId:"e", activeDashboard:dashboard, activeDashboardId:"dash", dashboards:[dashboard] }); return store; }

test("default configs contain no installation-specific entity ids", () => { const cfg = defaultHomeSummaryConfig(); assert.deepEqual(cfg.items.map((i) => i.entityId), ["", "", "", "", ""]); assert.equal(defaultWeatherCurrentConfig().weatherEntityId, "weather.home"); });
test("weather condition mapping uses controlled icon ids and no emoji", () => { assert.equal(WEATHER_CONDITIONS.rainy.iconId, "rain"); assert.equal(WEATHER_CONDITIONS.partlycloudy.label, "Poco Nuvoloso"); assert.equal(JSON.stringify(WEATHER_CONDITIONS).match(/[☀️🌧️💡]/u), null); });
test("current weather rendering uses live state and safe local icons", () => { const node = renderCard({id:"w",title:"M",type:"weather-current",config:{weatherEntityId:"weather.home"}}, runtime); assert.match(node.textContent, /21,5°C/); assert.match(node.textContent, /Pioggia/); assert.match(node.textContent, /Umidità 67%/); assert.equal(node.attributes.role, "button"); assert.equal(node.querySelectorAll("svg").length, 1); });
test("forecast rendering handles arrays and item count", () => { const node = renderCard({id:"f",title:"P",type:"weather-forecast",config:{weatherEntityId:"weather.home",forecastItemCount:1,showForecast:true,unitDisplay:"°"}}, runtime); assert.match(node.textContent, /MERCOLEDÌ 22/); assert.doesNotMatch(node.textContent, /GIOVED/); assert.equal(node.querySelectorAll("svg").length, 1); });
test("weather unavailable states distinguish missing config entity unknown unavailable malformed", () => { assert.equal(normalizeWeather(runtime, {weatherEntityId:""}).status, "missing-config"); assert.equal(normalizeWeather(runtime, {weatherEntityId:"weather.missing"}).status, "missing-entity"); assert.equal(normalizeWeather({getEntityState:()=>({state:"unknown",attributes:{}})}, {weatherEntityId:"weather.x"}).status, "unknown"); assert.equal(normalizeWeather({getEntityState:()=>({state:"unavailable",attributes:{}})}, {weatherEntityId:"weather.x"}).status, "unavailable"); assert.equal(normalizeWeather({getEntityState:()=>({state:"sunny",attributes:"bad"})}, {weatherEntityId:"weather.x"}).status, "malformed-attributes"); });
test("locale-aware formatting", () => { const n = normalizeWeather({locale:"en-US",getEntityState:()=>states["weather.home"]}, {weatherEntityId:"weather.home"}); assert.equal(n.temperatureText, "21.5°C"); });
test("home summary normalizers handle numeric decimal zero unknown unavailable malformed and missing", () => { assert.equal(normalizeSummaryMetric(states["sensor.luci"]).display, "3"); assert.equal(normalizeSummaryMetric(states["sensor.decimal"], {locale:"it-IT", suffix:" kW"}).display, "2,5 kW"); assert.equal(normalizeSummaryMetric(states["sensor.zero"]).display, "0"); assert.equal(normalizeSummaryMetric(states["sensor.unknown"]).status, "unknown"); assert.equal(normalizeSummaryMetric(states["sensor.unavailable"]).status, "unavailable"); assert.equal(normalizeSummaryMetric(states["sensor.bad"]).status, "malformed"); assert.equal(normalizeSummaryMetric(null).status, "missing-entity"); });
test("home summary rendering does not show unavailable as zero", () => { const cfg = {title:"Quadro Avvisi",items:[{key:"u",label:"Bad",entityId:"sensor.unavailable",icon:"alert",accent:"danger",fallbackText:"—"}]}; const node = renderCard({id:"h",title:"Home",type:"home-summary",config:cfg}, runtime); assert.match(node.textContent, /Bad—/); assert.doesNotMatch(node.textContent, /Bad0/); });
test("home summary rendering uses normalized configured entity ids", () => { const cfg = {title:"Quadro Avvisi",items:[{key:"l",label:"Luci Accese",entityId:"sensor.luci",icon:"lights",accent:"solar"}]}; const items = normalizeHomeSummaryItems(runtime, cfg); assert.equal(items[0].display, "3"); const node = renderCard({id:"h",title:"Home",type:"home-summary",config:cfg}, runtime); assert.match(node.textContent, /Quadro Avvisi/); assert.match(node.textContent, /Luci Accese3/); assert.equal(node.querySelectorAll("button").length, 1); assert.equal(node.querySelectorAll("svg").length, 1); });
test("validators reject unsafe invalid config remote icons colors and templates", () => { assert.ok(validateWeatherCurrentConfig({weatherEntityId:"{{ x }}"}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:11}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:7,showForecast:"yes"}).length); const errors = validateHomeSummaryConfig({items:[{key:"x",label:"{{bad}}",entityId:"",icon:"https://x/icon.svg",accent:"#fff"}]}); assert.ok(errors.some((e) => e.field === "config.items.0.entityId")); assert.ok(errors.some((e) => e.field === "config.items.0.icon")); assert.ok(errors.some((e) => e.field === "config.items.0.accent")); assert.ok(errors.some((e) => e.field === "config.items.0.label")); });
test("structured item editor adds removes reorders and edits items", () => { const card = {id:"c",title:"Home",type:"home-summary",config:{title:"T",items:[{key:"a",label:"A",entityId:"sensor.a",icon:"alert",accent:"green"},{key:"b",label:"B",entityId:"sensor.b",icon:"lights",accent:"solar"}]}}; const patches=[]; const controller={updateCardConfigPatch:(_id,patch)=>patches.push(patch)}; const form = renderCardForm(document, card, controller, [], {}, undefined); const inputs = form.querySelectorAll("input"); inputs.find((i) => i.dataset.editorField === "card:c:config.items.0.label").value = "AA"; inputs.find((i) => i.dataset.editorField === "card:c:config.items.0.label").oninput(); assert.deepEqual(patches.at(-1).items[0].label, "AA"); form.querySelectorAll("button").find((b) => b.textContent === "↓").click(); assert.equal(patches.at(-1).items[0].key, "b"); form.querySelectorAll("button").find((b) => b.textContent === "Remove").click(); assert.equal(patches.at(-1).items.length, 1); form.querySelectorAll("button").find((b) => b.textContent === "Add item").click(); assert.equal(patches.at(-1).items.length, 3); });
test("missing required entity ids block save, advanced JSON validates, correction enables save without mutating activeDashboard early", async () => { const dashboard = base(defaultHomeSummaryConfig()); const store = storeWith(dashboard); const controller = new EditorController(store); await controller.enter(); assert.equal(await controller.save(), false); assert.equal(store.state.activeDashboard, dashboard); assert.ok(store.state.editor.validationErrors.some((e) => e.field === "card:c:config.items.0.entityId")); controller.updateCardConfig("c", JSON.stringify({title:"Quadro",items:[{key:"l",label:"Luci",entityId:"sensor.luci",icon:"lights",accent:"solar"}]})); assert.equal(store.state.editor.validationErrors.length, 0); assert.equal(await controller.save(), true); assert.equal(store.state.activeDashboard.cards[0].config.items[0].entityId, "sensor.luci"); });
test("built-in plugin types are registered", () => { assert.deepEqual(cardRendererTypes(), ["home-summary", "legacy-panel", "weather-current", "weather-forecast"]); });
