import assert from "node:assert/strict";
import test from "node:test";
import { renderCard } from "../src/render/card-renderer.js";
import { WEATHER_CONDITIONS, normalizeWeather, validateWeatherCurrentConfig, validateWeatherForecastConfig } from "../src/cards/weather.js";
import { validateHomeSummaryConfig } from "../src/cards/home-summary.js";
import { cardRendererTypes } from "../src/render/card-renderer.js";

class Node { constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.dataset={};this.className="";this._text="";this.listeners={};} append(...i){this.children.push(...i)} setAttribute(k,v){this.attributes[k]=String(v)} addEventListener(t,f){this.listeners[t]=f} get textContent(){return this._text+this.children.map(c=>c.textContent).join("")} set textContent(v){this._text=String(v);this.children=[]} querySelectorAll(sel){const out=[];const match=n=>sel.startsWith(".")?n.className?.split?.(" ").includes(sel.slice(1)):n.tagName===sel;const walk=n=>{if(match(n))out.push(n);for(const c of n.children)walk(c)};walk(this);return out;} }
globalThis.document = { createElement: (tag) => new Node(tag) };
const states = { "weather.home": { entity_id:"weather.home", state:"rainy", last_updated:"2026-07-21T10:00:00Z", attributes:{ temperature:21.5, humidity:67, wind_speed:12, forecast:[{datetime:"2026-07-22T00:00:00", condition:"sunny", temperature:29, templow:18},{datetime:"2026-07-23T00:00:00", condition:"cloudy", temperature:28}] } }, "sensor.luci": { state:"3" } };
const runtime = { locale:"it-IT", connectionStatus:"connected", getEntityState:(id)=>states[id], callService:()=>{ throw new Error("backend call during render"); }, interactions:{ openWeather(){}, openHistory(){} } };

test("weather condition mapping is controlled and localized", () => { assert.equal(WEATHER_CONDITIONS.rainy.icon, "🌧️"); assert.equal(WEATHER_CONDITIONS.partlycloudy.label, "Poco Nuvoloso"); });
test("current weather rendering uses live state and safe text", () => { const node = renderCard({id:"w",title:"M",type:"weather-current",config:{weatherEntityId:"weather.home"}}, runtime); assert.match(node.textContent, /21,5°C/); assert.match(node.textContent, /Pioggia/); assert.match(node.textContent, /Umidità 67%/); assert.equal(node.attributes.role, "button"); });
test("forecast rendering handles arrays and item count", () => { const node = renderCard({id:"f",title:"P",type:"weather-forecast",config:{weatherEntityId:"weather.home",forecastItemCount:1,showForecast:true,unitDisplay:"°"}}, runtime); assert.match(node.textContent, /MERCOLEDÌ 22/); assert.doesNotMatch(node.textContent, /GIOVED/); });
test("unavailable and malformed weather attributes render without throwing", () => { const node = renderCard({id:"w",title:"M",type:"weather-current",config:{weatherEntityId:"weather.missing"}}, runtime); assert.match(node.textContent, /Meteo non disponibile/); const n = normalizeWeather({locale:"en-US",getEntityState:()=>({state:"sunny",attributes:{forecast:"bad",temperature:"x"}})}, {weatherEntityId:"weather.x"}); assert.equal(n.temperatureText, "--"); assert.deepEqual(n.forecast, []); });
test("locale-aware formatting", () => { const n = normalizeWeather({locale:"en-US",getEntityState:()=>states["weather.home"]}, {weatherEntityId:"weather.home"}); assert.equal(n.temperatureText, "21.5°C"); });
test("home summary rendering uses configured entity ids", () => { const node = renderCard({id:"h",title:"Home",type:"home-summary",config:{title:"Quadro Avvisi",items:[{label:"Luci Accese",entityId:"sensor.luci",icon:"💡"}]}}, runtime); assert.match(node.textContent, /Quadro Avvisi/); assert.match(node.textContent, /Luci Accese3/); assert.equal(node.querySelectorAll("button").length, 1); });
test("validators reject unsafe and invalid config", () => { assert.ok(validateWeatherCurrentConfig({weatherEntityId:""}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:11}).length); assert.ok(validateWeatherForecastConfig({weatherEntityId:"weather.home",forecastItemCount:7,showForecast:"yes"}).length); assert.ok(validateHomeSummaryConfig({items:[{entityId:""}]}).length); });
test("built-in plugin types are registered", () => { assert.deepEqual(cardRendererTypes(), ["home-summary", "legacy-panel", "weather-current", "weather-forecast"]); });
