import assert from "node:assert/strict";
import test from "node:test";
import { createPluginManager } from "../src/plugins/registry.js";
import { createSectionRegistry } from "../src/sections/registry.js";
import { createWidgetRegistry } from "../src/widgets/registry.js";
import { registerBuiltInModules } from "../src/modules/bootstrap.js";
import { VEHICLES_MODULE, normalizeVehicle, validateVehicleAction, renderVehicleTile, renderVehiclesOverview, openVehicleDetailPanel } from "../src/modules/vehicles.js";
import { CAMERAS_MODULE, normalizeCamera, cameraImage, cameraStream, cleanupCameraStream, validateCameraAction, renderCameraTile, renderCameraGrid, renderCameraLive, openCameraDetailPanel } from "../src/modules/cameras.js";
import { renderWidgetSpecificEditor } from "../src/editor/widget-editor.js";
class Node{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attributes={};this.listeners={};this.disabled=false;this.value="";this.checked=false;this._text="";this.focused=false;}append(...c){this.children.push(...c);for(const x of c)if(x)x.parentNode=this;}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);}replaceChildren(...c){this.children=[];this.append(...c);}setAttribute(k,v){this.attributes[k]=String(v);if(k==="disabled")this.disabled=true;if(k==="value")this.value=String(v);if(k.startsWith("data-"))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=String(v);}getAttribute(k){return this.attributes[k];}addEventListener(t,f){this.listeners[t]=f;}focus(){this.focused=true;globalThis.document.activeElement=this;}querySelectorAll(sel){const parts=sel.split(",").map(s=>s.trim()),out=[];const ok=n=>parts.includes(n.tagName)||parts.some(p=>p.startsWith("[")&&n.attributes[p.slice(1,-1)]!==undefined);const walk=n=>{if(ok(n))out.push(n);for(const c of n.children)walk(c);};walk(this);return out;}querySelector(sel){return this.querySelectorAll(sel)[0]||null;}get textContent(){return this._text+this.children.map(c=>c.textContent).join("");}set textContent(v){this._text=String(v);this.children=[];}}
const body=new Node("body");globalThis.document={body,activeElement:null,listeners:{},createElement:t=>new Node(t),querySelector:s=>s==="[data-dashboardmodern-detail-host]"?body.children.find(c=>c.dataset.dashboardmodernDetailHost!==undefined)||null:null,addEventListener(t,f){this.listeners[t]=f;},removeEventListener(t){delete this.listeners[t];}};
const runtime={states:{},calls:[],streams:[],getEntityState(id){return this.states[id]||null;},callService(d,s,data){this.calls.push([d,s,data]);return Promise.resolve();},getCameraImage(id){return `image:${id}`;},getCameraStream(id){return `stream:${id}`;},releaseCameraStream(ref){this.streams.push(ref);}};
test("Vehicles and Cameras modules register deterministically with default sections and widgets",()=>{const manager=createPluginManager({sectionRegistry:createSectionRegistry(),widgetRegistry:createWidgetRegistry()});registerBuiltInModules({pluginManager:manager});assert.deepEqual(manager.listModules().map(m=>m.id),["appliances","cameras","climate","covers","energy","home","lights","vehicles"]);assert.equal(manager.contributions().widgets.length,55);assert.equal(VEHICLES_MODULE.defaultLayouts[0].sectionType,"vehicles");assert.equal(CAMERAS_MODULE.defaultLayouts[0].widgets[0],"cameras-overview");});
test("vehicle normalization widgets actions and detail panel use runtime abstractions",async()=>{runtime.calls=[];body.replaceChildren();runtime.states={"device_tracker.car":{state:"home",attributes:{friendly_name:"Car",battery_level:81,charging_state:"charging",range:220,odometer:1000,trip_distance:42,latitude:1,longitude:2,locked:true,tyre_front_left:35,tyre_front_right:36,tyre_rear_left:34,tyre_rear_right:33,climate_state:"off"}}};const v=normalizeVehicle(runtime,{entityId:"device_tracker.car"});assert.equal(v.battery,81);assert.equal(v.charging,true);assert.equal(validateVehicleAction({type:"bad"}).length,1);assert.match(renderVehicleTile({type:"vehicle-tile",config:{entityId:"device_tracker.car"}},runtime).textContent,/Car/);assert.match(renderVehiclesOverview({type:"vehicles-overview",config:{entityIds:["device_tracker.car"]}},runtime).textContent,/battery 81/);const panel=openVehicleDetailPanel("device_tracker.car",runtime,new Node("button"));await panel.querySelectorAll("button").find(b=>b.textContent==="Lock").listeners.click();assert.deepEqual(runtime.calls[0],["lock","lock",{entity_id:"device_tracker.car"}]);globalThis.document.listeners.keydown({key:"Escape",preventDefault(){}});assert.equal(globalThis.document.listeners.keydown,undefined);});
test("camera image stream widgets actions cleanup and detail panel stay runtime-safe",async()=>{runtime.calls=[];runtime.streams=[];body.replaceChildren();runtime.states={"camera.front":{state:"recording",attributes:{friendly_name:"Front",entity_picture:"/api/camera_proxy/front",stream_source:"rtsp://secret",motion:true,recording:true,ptz:true,presets:["Door"]}}};const c=normalizeCamera(runtime,{entityId:"camera.front"});assert.equal(c.snapshotRef,"runtime-image:camera.front");assert.equal(cameraImage(runtime,c),"image:camera.front");assert.equal(cameraStream(runtime,c),"stream:camera.front");assert.equal(validateCameraAction({type:"ftp"}).length,1);assert.match(renderCameraTile({type:"camera-tile",config:{entityId:"camera.front"}},runtime).textContent,/Front/);assert.match(renderCameraGrid({type:"camera-grid",config:{entityIds:["camera.front"]}},runtime).textContent,/Front/);assert.match(renderCameraLive({type:"camera-live",config:{entityId:"camera.front"}},runtime).textContent,/Live stream stream:camera.front/);const panel=openCameraDetailPanel("camera.front",runtime,new Node("button"));await panel.querySelectorAll("button").find(b=>b.textContent==="Snapshot").listeners.click();assert.deepEqual(runtime.calls[0],["camera","snapshot",{entity_id:"camera.front"}]);await panel.querySelectorAll("button").find(b=>b.textContent==="Close").listeners.click();assert.deepEqual(runtime.streams,["stream:camera.front"]);cleanupCameraStream(runtime,"stream:x");assert.equal(runtime.streams.at(-1),"stream:x");});
test("vehicle and camera structured editors expose real fields and validate entity ids",()=>{const updates=[],controller={state:{validationErrors:[],fieldText:{}},store:{setState(s){controller.state=s.editor;}},updateWidget(s,w,p){updates.push(p);}};const section={id:"s"};const ve=renderWidgetSpecificEditor(document,section,{id:"v",type:"vehicle-control-panel",config:{entityId:"device_tracker.car",actions:[{type:"lock",title:"Lock"}]}},controller);assert.match(ve.textContent,/Vehicle entity ID/);assert.match(ve.textContent,/Control action titles/);ve.querySelectorAll("input")[0].value="bad id";ve.querySelectorAll("input")[0].listeners.input();assert.equal(controller.state.validationErrors.length,1);const ce=renderWidgetSpecificEditor(document,section,{id:"c",type:"camera-grid",config:{entityIds:["camera.front"]}},controller);assert.match(ce.textContent,/Camera entity IDs/);ce.querySelectorAll("input")[0].value="camera.front, camera.back";ce.querySelectorAll("input")[0].listeners.input();assert.deepEqual(updates.at(-1).config.entityIds,["camera.front","camera.back"]);});
