import assert from "node:assert/strict";
import test from "node:test";
import { createSectionRegistry } from "../src/sections/registry.js";
import { createWidgetRegistry, defaultWidgetContract, validateWidgetContract } from "../src/widgets/registry.js";
import { createPluginManager } from "../src/plugins/registry.js";
import { createCardRegistry } from "../src/cards/registry.js";
import { navigationEntriesForSections, normalizeNavigationConfig, revealOnScroll, splitMoreMenuItems, validateNavigationConfig } from "../src/navigation/navigation.js";

test("section registry registers, rejects duplicates, looks up, orders, and falls back", () => { const r = createSectionRegistry(); r.register({ type: "a", displayName: "A" }); r.register({ type: "b", displayName: "B" }); assert.throws(() => r.register({ type: "a", displayName: "A2" }), /already registered/); assert.equal(r.get("a").displayName, "A"); assert.deepEqual(r.types(), ["a", "b"]); assert.equal(r.resolve("missing").type, "unknown-section"); });
test("plugin manager registers modules and aggregates contributions with schema defaults", () => { const sectionRegistry = createSectionRegistry(); const cardRegistry = createCardRegistry(); const widgetRegistry = createWidgetRegistry(); const manager = createPluginManager({ sectionRegistry, cardRegistry, widgetRegistry }); const mod = manager.registerModule({ id: "home", sections: [{ type: "hero", displayName: "Hero" }], widgets: [{ type: "chip", displayName: "Chip" }], editorPanels: [{ id: "nav" }] }); assert.equal(mod.schemaVersion, 1); assert.equal(sectionRegistry.get("hero").owner, "home"); assert.equal(widgetRegistry.get("chip").owner, "home"); assert.equal(manager.contributions().editorPanels.length, 1); });
test("widget contract defaults validate and config is serialization safe", () => { const widget = defaultWidgetContract({ id: "w1", config: { entity: "light.kitchen" } }); assert.equal(widget.schemaVersion, 1); assert.deepEqual(validateWidgetContract(widget), []); assert.equal(validateWidgetContract(defaultWidgetContract({ config: { bad: BigInt(1) } })).at(-1).field, "config"); });
test("navigation filters visible sections, orders entries, tracks active-compatible ids and falls back invalid config", () => { const sections = [{ id: "b", title: "B", order: 2 }, { id: "a", title: "A", order: 1, visibleInNavbar: true }, { id: "x", enabled: false }, { id: "y", visibleInNavbar: false }]; assert.deepEqual(navigationEntriesForSections(sections).map((e) => e.sectionId), ["a", "b"]); assert.equal(normalizeNavigationConfig({ navigation: { visibilityMode: "bad", overflowMode: "bad" } }).overflowMode, "scroll"); assert.ok(validateNavigationConfig({ navigation: { autoHideDelay: 1 } }).length); });
test("navigation overflow utilities cover fit, more menu split, resize and scroll reveal", () => { assert.deepEqual(splitMoreMenuItems([1, 2], 300, 100), { visible: [1, 2], overflow: [] }); assert.deepEqual(splitMoreMenuItems([1, 2, 3, 4], 250, 100), { visible: [1], overflow: [2, 3, 4] }); assert.equal(revealOnScroll(100, 50), true); assert.equal(revealOnScroll(50, 100), false); });
import { renderBottomNavigation, BottomNavigationController } from "../src/navigation/bottom-navigation.js";
import { renderDashboard } from "../src/render/dashboard-renderer.js";

class NavNode {
  constructor(tag) { this.tagName = tag; this.children = []; this.dataset = {}; this.attributes = {}; this.hidden = false; this.className = ""; this.style = {}; this._text = ""; this.listeners = {}; this.clientWidth = 0; this.scrollWidth = 0; this.scrollLeft = 0; this.offsetWidth = 0; }
  append(...items) { this.children.push(...items); }
  replaceChildren(...items) { this.children = items; }
  setAttribute(k, v) { this.attributes[k] = String(v); if (k.startsWith("data-")) this.dataset[k.slice(5).replace(/-([a-z])/g, (_, c) => c.toUpperCase())] = String(v); }
  addEventListener(t, f) { this.listeners[t] = f; }
  removeEventListener(t) { delete this.listeners[t]; }
  get textContent() { return this._text + this.children.map((c) => c.textContent).join(""); }
  set textContent(v) { this._text = String(v); this.children = []; }
  getBoundingClientRect() { return { width: this.offsetWidth || this.clientWidth || Number(this.dataset.testWidth) || 0 }; }
  matches() { return false; }
  closest(sel) { return match(this, sel) ? this : null; }
  focus() { globalThis.document.activeElement = this; }
  click() { this.listeners.click?.({ target: this, preventDefault() {} }); }
  scrollIntoView(opts) { this.scrolledWith = opts; }
  querySelector(sel) { return this.querySelectorAll(sel)[0] || null; }
  querySelectorAll(sel) { const out = []; const walk = (n) => { if (match(n, sel)) out.push(n); for (const c of n.children) walk(c); }; walk(this); return out; }
}
function match(n, sel) { if (sel === "button") return n.tagName === "button"; if (sel === "nav") return n.tagName === "nav"; if (sel === "[data-bottom-navigation]") return Object.hasOwn(n.dataset, "bottomNavigation"); if (sel === "[data-nav-scroll]") return Object.hasOwn(n.dataset, "navScroll"); if (sel === "[data-nav-more]") return Object.hasOwn(n.dataset, "navMore"); if (sel === "[data-nav-more-summary]") return Object.hasOwn(n.dataset, "navMoreSummary"); if (sel === '[data-nav-edge="left"]') return n.dataset.navEdge === "left"; if (sel === '[data-nav-edge="right"]') return n.dataset.navEdge === "right"; if (sel === '[data-section-nav-id][data-nav-menu-item="false"]') return Object.hasOwn(n.dataset, "sectionNavId") && n.dataset.navMenuItem === "false"; if (sel === '[data-nav-menu-item="false"]') return n.dataset.navMenuItem === "false"; const byId = sel.match(/^\[data-section-nav-id="([^"]+)"\](?:\[data-nav-menu-item="([^"]+)"\])?$/); if (byId) return n.dataset.sectionNavId === byId[1] && (!byId[2] || n.dataset.navMenuItem === byId[2]); if (sel === "[data-section-nav-id]") return Object.hasOwn(n.dataset, "sectionNavId"); return false; }
globalThis.document = { activeElement: null, createElement: (tag) => new NavNode(tag) };
const navDash = { id: "d", title: "D", config: { navigation: { overflowMode: "scroll", visibilityMode: "auto-hide", autoHideDelay: 900, edgeIndicators: true } }, views: [{ id: "v1", section_ids: ["s1", "s2"] }, { id: "v2", section_ids: ["s3"] }], sections: ["s1", "s2", "s3"].map((id, i) => ({ id, title: `S${i + 1}`, navigation: { title: `N${i + 1}`, order: i } })), cards: [] };
function renderedController(dashboard = navDash, activeSectionId = "s1") { const root = new NavNode("div"); root.clientWidth = 220; renderDashboard(root, { dashboards: [dashboard], activeDashboard: dashboard, activeViewId: "v1", activeSectionId }, {}); const nav = root.querySelector("[data-bottom-navigation]"); const scroller = root.querySelector("[data-nav-scroll]"); scroller.clientWidth = 150; scroller.scrollWidth = 300; for (const [i, b] of scroller.querySelectorAll('[data-section-nav-id][data-nav-menu-item="false"]').entries()) b.offsetWidth = [70, 70, 70][i]; const store = { state: { activeDashboard: dashboard, activeViewId: "v1", activeSectionId }, setActiveSection(id) { this.state.activeSectionId = id; this.state.activeViewId = id === "s3" ? "v2" : "v1"; } }; const timers = []; const c = new BottomNavigationController(root, store, { ResizeObserverClass: class { constructor(fn) { this.fn = fn; } observe() { this.fn(); } disconnect() { this.done = true; } }, setTimer: (fn, ms) => (timers.push({ fn, ms }), timers.length), clearTimer: (id) => { timers[id - 1].cleared = true; } }); c.start(); return { root, nav, scroller, store, c, timers }; }

test("bottom navigation renders coherent ARIA and preserves activeSectionId across rerender", () => { const { root } = renderedController(navDash, "s2"); assert.equal(root.querySelector("[data-bottom-navigation]").attributes.role, undefined); assert.equal(root.querySelector('[data-section-nav-id="s2"][data-nav-menu-item="false"]').attributes["aria-current"], "page"); const root2 = new NavNode("div"); renderDashboard(root2, { dashboards: [navDash], activeDashboard: navDash, activeViewId: "v1", activeSectionId: "s2" }, {}); assert.equal(root2.querySelector('[data-section-nav-id="s2"][data-nav-menu-item="false"]').attributes["aria-current"], "page"); });
test("selecting same-view and other-view sections updates store and reveals content", () => { const { root, store } = renderedController(); const section = root.querySelector('[data-section-nav-id="s2"][data-nav-menu-item="false"]'); section.click(); root.listeners.click({ target: section }); assert.equal(store.state.activeSectionId, "s2"); const other = root.querySelector('[data-section-nav-id="s3"][data-nav-menu-item="false"]'); root.listeners.click({ target: other }); assert.equal(store.state.activeViewId, "v2"); });
test("ResizeObserver recalculates scroll fit overflow and edge indicators", () => { const { nav, scroller, c } = renderedController(); c.recalculate(); assert.equal(nav.dataset.overflowing, "true"); assert.equal(scroller.style.overflowX, "auto"); assert.equal(nav.querySelector('[data-nav-edge="right"]').hidden, false); scroller.clientWidth = 400; scroller.scrollWidth = 210; c.recalculate(); assert.equal(nav.dataset.overflowing, "false"); assert.equal(scroller.style.overflowX, "hidden"); assert.equal(nav.querySelector('[data-nav-edge="right"]').hidden, true); });
test("More menu partitions using measured item and more widths", () => { const dash = { ...navDash, config: { navigation: { overflowMode: "more-menu", visibilityMode: "fixed" } } }; const { root, c } = renderedController(dash); const summary = root.querySelector("[data-nav-more-summary]"); summary.offsetWidth = 60; c.recalculate(); assert.equal(root.querySelector("[data-nav-more]").hidden, false); assert.equal(root.querySelector('[data-section-nav-id="s3"][data-nav-menu-item="false"]').hidden, true); });
test("active item reveal honors reduced motion", () => { const old = globalThis.matchMedia; globalThis.matchMedia = () => ({ matches: true }); const { root, c, store } = renderedController(); store.state.activeSectionId = "s2"; c.revealActiveItem(); assert.equal(root.querySelector('[data-section-nav-id="s2"][data-nav-menu-item="false"]').scrolledWith.behavior, "auto"); globalThis.matchMedia = old; });
test("auto-hide delay focus upward scroll active change and cleanup", () => { const { nav, c, timers } = renderedController(); c.reveal(); assert.equal(timers.at(-1).ms, 900); nav.dataset.hidden = "true"; c.lastY = 100; c.container.scrollTop = 50; c.handleScroll(); assert.equal(nav.dataset.hidden, "false"); c.store.state.activeSectionId = "s3"; c.syncActive(); assert.equal(nav.dataset.hidden, "false"); c.destroy(); assert.ok(timers.some((t) => t.cleared)); });
test("fixed mode never auto hides", () => { const dash = { ...navDash, config: { navigation: { visibilityMode: "fixed" } } }; const { nav, c } = renderedController(dash); c.lastY = 0; c.container.scrollTop = 100; c.handleScroll(); assert.notEqual(nav.dataset.hidden, "true"); });
test("section registry renderer and unknown fallback flow through dashboard renderer", () => { const registry = createSectionRegistry(); registry.register({ type: "special", displayName: "Special", renderer: () => { const n = new NavNode("section"); n.textContent = "Special renderer"; return n; } }); const dash = { ...navDash, config: {}, views: [{ id: "v", section_ids: ["x", "y"] }], sections: [{ id: "x", type: "special", card_ids: [] }, { id: "y", type: "missing", title: "Missing", card_ids: [] }], cards: [] }; const root = new NavNode("div"); renderDashboard(root, { dashboards: [dash], activeDashboard: dash, activeViewId: "v" }, { sectionRegistry: registry }); assert.match(root.textContent, /Special renderer/); assert.match(root.textContent, /not registered/); });
