import assert from "node:assert/strict";
import test from "node:test";
import { createSectionRegistry } from "../src/sections/registry.js";
import { createWidgetRegistry, defaultWidgetContract, validateWidgetContract } from "../src/widgets/registry.js";
import { createPluginManager } from "../src/plugins/registry.js";
import { createCardRegistry } from "../src/cards/registry.js";
import { navigationEntriesForSections, normalizeNavigationConfig, revealOnScroll, splitMoreMenuItems, validateNavigationConfig } from "../src/navigation/navigation.js";

test("section registry registers, rejects duplicates, looks up, orders, and falls back", () => { const r = createSectionRegistry(); r.register({ type: "a", displayName: "A" }); r.register({ type: "b", displayName: "B" }); assert.throws(() => r.register({ type: "a", displayName: "A2" }), /already registered/); assert.equal(r.get("a").displayName, "A"); assert.deepEqual(r.types(), ["a", "b"]); assert.equal(r.resolve("missing").type, "unknown-section"); });
test("plugin manager registers modules and aggregates contributions with schema defaults", () => { const sectionRegistry = createSectionRegistry(); const cardRegistry = createCardRegistry(); const widgetRegistry = createWidgetRegistry(); const manager = createPluginManager({ sectionRegistry, cardRegistry, widgetRegistry }); const mod = manager.registerModule({ id: "home", sections: [{ type: "hero", displayName: "Hero" }], widgets: [{ type: "chip", displayName: "Chip" }], editorPanels: [{ id: "nav" }] }); assert.equal(mod.schemaVersion, 1); assert.equal(sectionRegistry.get("hero").owner, "home"); assert.equal(widgetRegistry.get("chip").owner, "home"); assert.equal(manager.contributions().editorPanels.length, 1); });
test("widget contract defaults validate and config is serialization safe", () => { const widget = defaultWidgetContract({ id: "w1", config: { entity: "light.kitchen" } }); assert.equal(widget.schemaVersion, 1); assert.deepEqual(validateWidgetContract(widget), []); assert.equal(validateWidgetContract(defaultWidgetContract({ config: { bad: BigInt(1) } })).at(-1).field, "config"); });
test("navigation filters visible sections, orders entries, tracks active-compatible ids and falls back invalid config", () => { const sections = [{ id: "b", title: "B", order: 2 }, { id: "a", title: "A", order: 1, visibleInNavbar: true }, { id: "x", enabled: false }, { id: "y", visibleInNavbar: false }]; assert.deepEqual(navigationEntriesForSections(sections).map((e) => e.sectionId), ["a", "b"]); assert.equal(normalizeNavigationConfig({ navigation: { visibilityMode: "bad", overflowMode: "bad" } }).overflowMode, "scroll"); assert.ok(validateNavigationConfig({ navigation: { autoHideDelay: 1 } }).length); });
test("navigation overflow utilities cover fit, more menu split, resize and scroll reveal", () => { assert.deepEqual(splitMoreMenuItems([1, 2], 300, 100), { visible: [1, 2], overflow: [] }); assert.deepEqual(splitMoreMenuItems([1, 2, 3, 4], 250, 100), { visible: [1], overflow: [2, 3, 4] }); assert.equal(revealOnScroll(100, 50), true); assert.equal(revealOnScroll(50, 100), false); });
