import assert from "node:assert/strict";
import test from "node:test";
import { createPluginManager } from "../src/plugins/registry.js";
import { createSectionRegistry } from "../src/sections/registry.js";
import { createWidgetRegistry } from "../src/widgets/registry.js";
import { SECURITY_MODULE, SECURITY_WIDGETS, defaultSecuritySectionConfig, normalizeSecurityItem, normalizeLockState, normalizeAlarmState, normalizeBinarySensorState, normalizePresenceState, validateSecurityAction, visibilityAllows, selectTracker, summarizeSecurity, filterSecurityItems, renderLockTile, renderLocksOverview, renderSecurityOverview, openSecurityDetail } from "../src/modules/security.js";
import { registerBuiltInModules } from "../src/modules/bootstrap.js";
import { renderWidgetSpecificEditor } from "../src/editor/widget-editor.js";

class Node{constructor(t){this.tagName=t;this.children=[];this.dataset={};this.attributes={};this.listeners={};this.disabled=false;this.value="";this.checked=false;this._text="";}append(...c){this.children.push(...c);for(const x of c)if(x)x.parentNode=this;}replaceChildren(...c){this.children=[];this.append(...c);}remove(){this.removed=true;}setAttribute(k,v){this.attributes[k]=String(v);if(k==="disabled")this.disabled=true;if(k==="value")this.value=String(v);}getAttribute(k){return this.attributes[k];}addEventListener(t,f){this.listeners[t]=f;}focus(){this.focused=true;globalThis.document.activeElement=this;}querySelectorAll(sel){const out=[];const walk=n=>{if(sel.includes(n.tagName)||sel.includes("button")&&n.tagName==="button"||sel.includes("input")&&n.tagName==="input")out.push(n);for(const c of n.children)walk(c)};walk(this);return out;}get textContent(){return this._text+this.children.map(c=>c.textContent).join("");}set textContent(v){this._text=String(v);this.children=[];}}
globalThis.document={body:new Node("body"),activeElement:null,listeners:{},createElement:t=>new Node(t),querySelector:s=>globalThis.document.body.children.find(c=>c.attributes?.["data-dashboardmodern-detail-host"]!==undefined)||null,addEventListener(t,f){this.listeners[t]=f;},removeEventListener(t){delete this.listeners[t];}};
const runtime={states:{},calls:[],sections:[],views:[],getEntityState(id){return this.states[id]||null;},callService(d,s,data){this.calls.push([d,s,data]);return Promise.resolve();},navigateToSection(id){this.sections.push(id);},navigateToView(id){this.views.push(id);}};

test("Security module registers deterministically with default section and widgets",()=>{const pm=createPluginManager({sectionRegistry:createSectionRegistry(),widgetRegistry:createWidgetRegistry()});registerBuiltInModules({pluginManager:pm});assert.ok(pm.listModules().map(m=>m.id).includes("security"));assert.deepEqual(SECURITY_MODULE.defaultLayouts[0].widgets,["security-overview","presence-overview"]);assert.deepEqual(defaultSecuritySectionConfig("sec-a").widgets.map(w=>w.id),["sec-a-security-overview","sec-a-presence-overview"]);assert.notDeepEqual(defaultSecuritySectionConfig("sec-a").widgets.map(w=>w.id),defaultSecuritySectionConfig("sec-b").widgets.map(w=>w.id));assert.deepEqual(SECURITY_MODULE.widgets.map(w=>w.type),SECURITY_WIDGETS);});

test("Security source model has exclusive states, explicit attribute fallback, stale/future and health",()=>{runtime.states={"lock.front":{state:"locked",attributes:{friendly_name:"Front",battery:10},last_updated:"2026-07-23T00:00:00Z"},"sensor.old":{state:"2000-01-01T00:00:00Z",attributes:{},last_updated:"2000-01-01T00:00:00Z"},"sensor.future":{state:"2999-01-01T00:00:00Z",attributes:{},last_updated:"2999-01-01T00:00:00Z"}};let n=normalizeSecurityItem(runtime,{entityId:"lock.front",batteryEntityId:"lock.front",attributeMappings:{battery:"battery"}},"lock");assert.equal(n.operational,true);assert.equal(n.health,"available");assert.equal(n.sources.battery.sourceType,"attribute");assert.equal(n.sources.battery.available,true);for(const s of Object.values(n.sources).filter(x=>x.configured)){assert.equal([s.available,s.missing,s.unavailable,s.malformed,s.stale].filter(Boolean).length,1);}n=normalizeSecurityItem(runtime,{entityId:"lock.front",batteryEntityId:"lock.front"},"lock");assert.equal(n.sources.battery.malformed,true);n=normalizeSecurityItem(runtime,{entityId:"lock.front",lastSeenEntityId:"sensor.old",staleAfterMs:1},"lock");assert.equal(n.operational,true);assert.equal(n.partial,true);assert.equal(n.health,"stale");n=normalizeSecurityItem(runtime,{entityId:"lock.front",lastSeenEntityId:"sensor.future",futureToleranceMs:0},"lock");assert.equal(n.sources.lastSeen.malformed,true);});

test("Security normalization covers lock alarm binary presence and tracker strategy",()=>{assert.equal(normalizeLockState("unlocking"),"unlocking");assert.equal(normalizeAlarmState("armed_night"),"armed_night");assert.equal(normalizeBinarySensorState("off"),"inactive");assert.equal(normalizePresenceState("not_home"),"away");runtime.states={"device_tracker.a":{state:"home",attributes:{},last_updated:"2026-01-01T00:00:00Z"},"device_tracker.b":{state:"away",attributes:{},last_updated:"2026-02-01T00:00:00Z"}};assert.equal(selectTracker({trackerSelectionStrategy:"most-recently-updated",trackerEntities:["device_tracker.a","device_tracker.b"]},runtime),"device_tracker.b");assert.equal(selectTracker({trackerSelectionStrategy:"configured-priority-order",trackerEntities:["device_tracker.a","device_tracker.b"],trackerPriorityOrder:["device_tracker.b","device_tracker.a"]},runtime),"device_tracker.b");runtime.states["device_tracker.b"].state="unavailable";assert.equal(selectTracker({trackerSelectionStrategy:"first-available",trackerEntities:["device_tracker.b","device_tracker.a"]},runtime),"device_tracker.a");});

test("Security actions are explicit only, validate capability, confirm and duplicate guard",async()=>{runtime.calls=[];runtime.states={"lock.front":{state:"locked",attributes:{},last_updated:"2026-07-23T00:00:00Z"}};assert.deepEqual(validateSecurityAction({type:"service",domain:"lock",service:"unlock",entityId:"lock.front"},runtime).errors,[]);assert.ok(validateSecurityAction({type:"service",domain:"lock"},runtime).errors.includes("service"));const node=renderLockTile({id:"l",type:"lock-tile",config:{entityId:"lock.front",actions:[{title:"Unlock",type:"service",domain:"lock",service:"unlock",entityId:"lock.front",confirm:true}]}},runtime);assert.equal(node.querySelectorAll("button").length,2);globalThis.confirm=()=>true;await node.querySelectorAll("button")[0].listeners.click();assert.deepEqual(runtime.calls[0],["lock","unlock",{entity_id:"lock.front"}]);});

test("Security overview filtering sorting counts empty and editor nested rows",()=>{const items=[{title:"Front",state:"locked",operational:true,sources:{battery:{normalizedValue:10}},room:"Entry",tags:["door"]},{title:"Back",state:"unlocked",operational:false,sources:{battery:{normalizedValue:90}},room:"Yard",tags:[]}];assert.equal(summarizeSecurity(items).locked,1);assert.equal(filterSecurityItems(items,{search:"front",lowBatteryOnly:true}).length,1);runtime.states={};const empty=renderLocksOverview({id:"ov",type:"locks-overview",config:{locks:[],search:"none"}},runtime);assert.match(empty.textContent,/No security items/);const updates=[],controller={state:{validationErrors:[],fieldText:{}},store:{setState(s){controller.state=s.editor;}},updateWidget(s,w,p){updates.push(p);}};const editor=renderWidgetSpecificEditor(document,{id:"s"},{id:"w",type:"locks-overview",config:{locks:[{id:"row-1",title:"Front",entityId:"lock.front",actions:[]}] }},controller);assert.match(editor.textContent,/Allow primary attributes/);assert.match(editor.textContent,/Add locks row/);editor.querySelectorAll("button").find(b=>b.textContent==="Add locks row").listeners.click();assert.notEqual(updates.at(-1).config.locks.at(-1).id,"row-1");});


test("Security forbids legacy hass fallback showUnavailable and navigation visibility",async()=>{runtime.calls=[];runtime.sections=[];runtime.views=[];runtime.states={"binary_sensor.visible":{state:"on",attributes:{},last_updated:"2026-07-23T00:00:00Z"},"lock.front":{state:"locked",attributes:{},last_updated:"2026-07-23T00:00:00Z"}};assert.equal(visibilityAllows({visibility:{entityId:"binary_sensor.visible",operator:"on"}},runtime),true);assert.equal(visibilityAllows({visibility:{entityId:"binary_sensor.visible",operator:"off"}},runtime),false);const node=renderLockTile({config:{entityId:"lock.front",actions:[{title:"Shown",type:"navigate-section",sectionId:"security",visibility:{entityId:"binary_sensor.visible",operator:"on"}},{title:"Hidden",type:"navigate-view",viewId:"v",visibility:{entityId:"binary_sensor.visible",operator:"off"}}]}},runtime);assert.match(node.textContent,/Shown/);assert.doesNotMatch(node.textContent,/Hidden/);await node.querySelectorAll("button").find(b=>b.textContent==="Shown").listeners.click();assert.deepEqual(runtime.sections,["security"]);const items=[{title:"Ok",state:"locked",operational:true,sources:{battery:{normalizedValue:99}},room:"",tags:[]},{title:"Bad",state:"unknown",operational:false,sources:{battery:{normalizedValue:99}},room:"",tags:[]}];assert.deepEqual(filterSecurityItems(items,{showUnavailable:false}).map(i=>i.title),["Ok"]);assert.deepEqual(filterSecurityItems(items,{showUnavailable:true}).map(i=>i.title),["Bad","Ok"]);});

test("Security validation coordinates counts no double normalization and details lifecycle",()=>{runtime.states={"lock.front":{state:"locked",attributes:{},last_updated:"2026-07-23T00:00:00Z"},"sensor.lat":{state:"95",attributes:{},last_updated:"2026-07-23T00:00:00Z"},"sensor.lon":{state:"-181",attributes:{},last_updated:"2026-07-23T00:00:00Z"}};let n=normalizeSecurityItem(runtime,{entityId:"lock.front",latitudeEntityId:"sensor.lat",longitudeEntityId:"sensor.lon",displayFields:["coordinates"]},"lock");assert.equal(n.sources.latitude.malformed,true);assert.equal(n.sources.longitude.malformed,true);const rendered=renderSecurityOverview({type:"security-overview",config:{items:[{title:"Door",entityId:"lock.front"}],showUnavailable:true}},runtime);assert.match(rendered.textContent,/Door/);assert.doesNotMatch(rendered.textContent,/undefined/);assert.ok(validateSecurityAction({type:"service",domain:"x",service:"y",target:[],data:[],visibility:{operator:"bad"},disabled:"no",confirm:"yes"},runtime).errors.length>=5);const counts=summarizeSecurity([{state:"locked",operational:true,sources:{}},{state:"unlocked",operational:true,sources:{}},{state:"open",operational:true,sources:{}},{state:"triggered",operational:false,sources:{}},{state:"home",operational:true,sources:{}},{state:"away",operational:true,sources:{}}]);assert.equal(counts.locked,1);assert.equal(counts.unlocked,1);assert.equal(counts.open,1);assert.equal(counts.alarmTriggered,1);assert.equal(counts.home,1);assert.equal(counts.away,1);const trigger=new Node("button"), detail=openSecurityDetail(n,runtime,trigger);globalThis.document.listeners.keydown({key:"Escape",preventDefault(){}});assert.equal(trigger.focused,true);});
