import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { actionButton } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";
const RE=/^[a-z0-9_]+\.[a-z0-9_]+$/;const state=(r,id)=>RE.test(id)?r.getEntityState?.(id):null;const bad=e=>!e||["unavailable","unknown"].includes(e.state)||!e.attributes||typeof e.attributes!=="object";
export function normalizeCamera(r={},c={}){const id=typeof c==="string"?c:c.entityId||"",e=state(r,id),a=e?.attributes||{};return{entityId:id,title:c.title||a.friendly_name||id||"Camera",status:!id?"missing":bad(e)?"unavailable":"connected",state:e?.state||"unknown",motion:Boolean(a.motion||a.motion_detected),recording:Boolean(a.recording),ptz:Boolean(a.ptz||a.supported_features),presets:Array.isArray(a.presets)?a.presets:[],snapshotRef:a.entity_picture?`runtime-image:${id}`:"",streamRef:a.stream_source?`runtime-stream:${id}`:""};}
export function cameraImage(runtime,cam){return runtime.getCameraImage?.(cam.entityId)||cam.snapshotRef||"";}export function cameraStream(runtime,cam){return runtime.getCameraStream?.(cam.entityId)||cam.streamRef||"";}export function cleanupCameraStream(runtime,ref){return runtime.releaseCameraStream?.(ref);}
export function validateCameraAction(a={}){const out=[];if(!["service","navigate-section","navigate-view","snapshot","record","ptz","preset"].includes(a.type||"service"))out.push({field:"action.type",message:"Unsupported camera action."});if(a.entityId&&!RE.test(a.entityId))out.push({field:"action.entityId",message:"Invalid camera entity ID."});return out;}
function call(r,a,c){if(a.type==="navigate-section")return r.navigateToSection?.(a.sectionId);if(a.type==="navigate-view")return r.navigateToView?.(a.viewId);if(a.type==="snapshot")return r.callService?.("camera","snapshot",{entity_id:a.entityId||c.entityId});if(a.type==="record")return r.callService?.("camera","record",{entity_id:a.entityId||c.entityId});if(a.type==="ptz")return r.callService?.("camera","ptz",{entity_id:a.entityId||c.entityId,direction:a.direction});if(a.type==="preset")return r.callService?.("camera","play_stream",{entity_id:a.entityId||c.entityId,preset:a.preset});return r.callService?.(a.domain,a.service,{entity_id:a.entityId||c.entityId,...(a.data||{})});}
const shell=(w,c="")=>el("article",{className:`dm-widget ${c}`.trim()});function imageNode(r,c,label="Snapshot"){const src=cameraImage(r,c),img=el("img",{attrs:{alt:`${label} for ${c.title}`}});if(src)img.setAttribute("src",src);return img;}function streamNode(r,c){const ref=cameraStream(r,c),v=el("div",{text:ref?`Live stream ${ref}`:"Live stream unavailable",attrs:{role:"img","aria-label":`Live stream for ${c.title}`}});v.dataset.streamRef=ref;return v;}function detailBtn(n,c,r){n.append(actionButton("Details",!c.entityId,()=>openCameraDetailPanel(c.entityId,r,n),n,"camera-action"));}
export function renderCameraTile(w,r={}){const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-tile");n.append(el("h3",{text:w.title||c.title}),imageNode(r,c),el("p",{text:`${c.title}: ${c.status}`}));detailBtn(n,c,r);return n;}
export function renderCameraGrid(w,r={}){const n=shell(w,"dm-camera-grid");n.append(el("h3",{text:w.title||"Camera grid"}));for(const id of w.config?.entityIds||[])n.append(renderCameraTile({type:"camera-tile",config:{entityId:id}},r));return n;}
export function renderCameraCarousel(w,r={}){const n=shell(w,"dm-camera-carousel");n.append(el("h3",{text:w.title||"Camera carousel"}));(w.config?.entityIds||[]).slice(0,1).forEach(id=>n.append(renderCameraTile({type:"camera-tile",config:{entityId:id}},r)));return n;}
export const renderCameraSnapshot=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-snapshot");n.append(el("h3",{text:w.title||"Camera snapshot"}),imageNode(r,c));return n;};
export const renderCameraLive=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-live");n.append(el("h3",{text:w.title||"Camera live"}),streamNode(r,c));return n;};
export const renderCameraMotion=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-motion");n.append(el("h3",{text:w.title||"Camera motion"}),el("p",{text:c.motion?"Motion detected":"No motion"}));return n;};
export const renderCameraRecording=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-recording");n.append(el("h3",{text:w.title||"Camera recording"}),el("p",{text:c.recording?"Recording":"Not recording"}));return n;};
export const renderCameraPtz=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-ptz");n.append(el("h3",{text:w.title||"Camera PTZ"}),actionButton("Pan left",!c.ptz,()=>call(r,{type:"ptz",direction:"left"},c),n,"camera-action"));return n;};
export const renderCameraPresets=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-presets");n.append(el("h3",{text:w.title||"Camera presets"}));for(const p of c.presets)n.append(actionButton(p,false,()=>call(r,{type:"preset",preset:p},c),n,"camera-action"));return n;};
export function renderCamerasOverview(w,r={}){const n=shell(w,"dm-cameras-overview");n.append(el("h3",{text:w.title||"Cameras"}));for(const id of w.config?.entityIds||[])n.append(renderCameraTile({type:"camera-tile",config:{entityId:id}},r));if(!(w.config?.entityIds||[]).length)n.append(el("p",{text:"No cameras configured."}));return n;}
export function renderCameraPanel(w,r={}){const c=normalizeCamera(r,w.config||{}),n=shell(w,"dm-camera-panel");n.setAttribute("role","dialog");const stream=streamNode(r,c);n.append(actionButton("Close",false,()=>{cleanupCameraStream(r,stream.dataset.streamRef);w.config?.close?.();},n,"camera-action"),el("h3",{text:`Camera detail: ${c.title}`}),stream);for(const a of w.config?.actions||[])n.append(actionButton(a.title||a.type,validateCameraAction(a).length,()=>call(r,a,c),n,"camera-action"));return n;}
export function openCameraDetailPanel(entityId,r={},trigger=null){return openSharedDetailPanel({trigger,label:`Camera detail ${entityId}`,render:({close})=>renderCameraPanel({type:"camera-control-panel",config:{entityId,close,actions:[{type:"snapshot",title:"Snapshot"},{type:"record",title:"Record"}]}},r)}).panel;}
export function camerasSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-cameras-section",attrs:{"data-section-id":section.id}});n.append(el("h3",{text:section.title||"Cameras"}),renderWidgetLayout(section.config?.widgets||[{id:`${section.id}-cameras-overview`,type:"cameras-overview",config:section.config||{},layout:{size:"full"}}],context,context.widgetRegistry));return n;}
const cfg=()=>({entityId:""}), val=c=>c?.entityId&&!RE.test(c.entityId)?[{field:"entityId",message:"Invalid camera entity ID."}]:[];const widgets=[["camera-tile","Camera tile",renderCameraTile,cfg],["camera-grid","Camera grid",renderCameraGrid,()=>({entityIds:[]})],["camera-carousel","Camera carousel",renderCameraCarousel,()=>({entityIds:[]})],["camera-snapshot","Camera snapshot",renderCameraSnapshot,cfg],["camera-live","Camera live",renderCameraLive,cfg],["camera-motion","Camera motion",renderCameraMotion,cfg],["camera-recording","Camera recording",renderCameraRecording,cfg],["camera-ptz","Camera PTZ",renderCameraPtz,cfg],["camera-presets","Camera presets",renderCameraPresets,cfg],["cameras-overview","Cameras overview",renderCamerasOverview,()=>({entityIds:[]})],["camera-control-panel","Camera control panel",renderCameraPanel,()=>({entityId:"",actions:[]})]];
export const CAMERAS_MODULE={id:"cameras",schemaVersion:1,sections:[{type:"cameras",displayName:"Cameras",renderer:camerasSectionRenderer}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,validator:val,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"cameras-editor",title:"Cameras editor"}],navigationEntries:[{sectionType:"cameras",icon:"camera",title:"Cameras"}],actions:["camera.snapshot","camera.record","camera.ptz","camera.preset"],detailPanels:[{type:"camera-control-panel"}],defaultLayouts:[{sectionType:"cameras",widgets:["cameras-overview"]}]};
