import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { actionButton } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";
import { ENTITY_RE } from "./shared-measurements.js";
const BAD=new Set(["unknown","unavailable",""]);const get=(r,id)=>ENTITY_RE.test(id||"")?r.getEntityState?.(id):null;
function srcBase(entityId){return{entityId:entityId||"",available:false,missing:false,unavailable:false,malformed:false,stale:false,reason:"not-evaluated",ref:null};}
export function normalizeCamera(r={},c={}){const id=c.primaryEntityId||c.entityId||"",e=get(r,id),a=e?.attributes||{},missing=!id||!e,unavailable=e&&BAD.has(String(e.state??"").trim()),malformed=id&&!ENTITY_RE.test(id);const reason=malformed?"invalid-entity-id":missing?(!id?"missing-entity-id":"entity-missing"):unavailable?String(e.state||"empty"):"ok";return{id:c.id||id||"camera",title:c.title||a.friendly_name||id||"Camera",entityId:id,available:reason==="ok",missing:Boolean(missing),unavailable:Boolean(unavailable),malformed:Boolean(malformed),stale:false,reason,state:e?.state||"unknown",onlineEntityId:c.onlineEntityId||id,motionEntityId:c.motionEntityId||"",occupancyEntityId:c.occupancyEntityId||"",recordingEntityId:c.recordingEntityId||"",privacyEntityId:c.privacyEntityId||"",batteryEntityId:c.batteryEntityId||"",signalEntityId:c.signalEntityId||"",lastUpdateEntityId:c.lastUpdateEntityId||"",actions:c.actions||[],ptzActions:c.ptzActions||[],presets:c.presets||[],rooms:c.rooms||[],tags:c.tags||[],displayFields:c.displayFields||[]};}
export function getCameraImageSource(r,c,kind="snapshot"){if(typeof r.getCameraImageSource!=="function")return{...srcBase(c.entityId),unavailable:true,reason:"runtime-image-unavailable"};const res=r.getCameraImageSource(c.entityId,{kind});return{...srcBase(c.entityId),...(res||{}),available:Boolean(res?.available),ref:res?.ref||res?.source||null,reason:res?.reason||"ok"};}
export function acquireCameraStream(r,c){if(typeof r.acquireCameraStream!=="function")return Promise.resolve({...srcBase(c.entityId),unavailable:true,reason:"runtime-stream-unavailable"});return Promise.resolve(r.acquireCameraStream(c.entityId)).then(res=>({...srcBase(c.entityId),...(res||{}),available:Boolean(res?.available),ref:res?.ref||null,reason:res?.reason||"ok"}));}
export function releaseCameraStream(r,source){if(source?.ref&&typeof r.releaseCameraStream==="function")return r.releaseCameraStream(source.ref);}
export function refreshCameraSnapshot(r,c){return r.refreshCameraSnapshot?.(c.entityId);}
export function validateCameraAction(a={},r={}){const e=[];if(!["service","navigate-section","navigate-view"].includes(a.type))e.push({field:"type",message:"Action type must be explicit."});if(a.type==="service"&&(!a.domain||!a.service))e.push({field:"service",message:"Service requires domain and service."});if(a.entityId&&!ENTITY_RE.test(a.entityId))e.push({field:"entity",message:"Invalid entity ID."});if(a.target?.entity_id&&!ENTITY_RE.test(a.target.entity_id))e.push({field:"target",message:"Invalid target entity ID."});if(a.data&&typeof a.data!=="object")e.push({field:"data",message:"Action data must be an object."});if(a.disabled!==undefined&&typeof a.disabled!=="boolean")e.push({field:"disabled",message:"Disabled must be boolean."});if(a.confirm!==undefined&&typeof a.confirm!=="boolean")e.push({field:"confirm",message:"Confirmation must be boolean."});if(a.type==="service"&&typeof r.callService!=="function")e.push({field:"runtime",message:"Runtime cannot call services."});return e;}
async function runAction(a,r){if(a.confirm&&globalThis.confirm&&!globalThis.confirm(`Run ${a.title||a.service}?`))return;if(a.type==="navigate-section")return r.navigateToSection?.(a.sectionId);if(a.type==="navigate-view")return r.navigateToView?.(a.viewId);return r.callService?.(a.domain,a.service,{...(a.target||{}),entity_id:a.entityId||a.target?.entity_id,...(a.data||{})});}
const art=c=>el("article",{className:`dm-widget ${c}`});function actionList(n,acts,r,prefix="camera-action"){acts.forEach(a=>n.append(actionButton(a.title||a.service||"Action",a.disabled||validateCameraAction(a,r).length,()=>runAction(a,r),n,prefix)));}
function img(r,c){const s=getCameraImageSource(r,c),n=el("div",{text:s.available?`Image ${s.ref}`:`Image unavailable: ${s.reason}`,attrs:{role:"img","aria-label":`Snapshot for ${c.title}: ${s.reason}`}});n.dataset.sourceState=s.reason;return n;}
function liveWidget(c,r,n,{autoStart=false}={}){let source=null,pending=false;const status=el("p",{text:autoStart?"Loading live stream":"Live stream stopped"}),start=el("button",{text:"Start live",attrs:{type:"button"}}),stop=el("button",{text:"Stop live",attrs:{type:"button",disabled:""}});async function startLive(){if(pending||source?.available)return;pending=true;start.disabled=true;status.textContent="Loading live stream";try{source=await acquireCameraStream(r,c);status.textContent=source.available?`Live stream ready ${source.ref}`:`Live stream unavailable: ${source.reason}`;stop.disabled=!source.available;}catch(e){status.textContent=e?.message||"Live stream error";}finally{pending=false;start.disabled=Boolean(source?.available);}}function stopLive(){releaseCameraStream(r,source);source=null;status.textContent="Live stream stopped";start.disabled=false;stop.disabled=true;}start.addEventListener("click",startLive);stop.addEventListener("click",stopLive);n.dataset.cleanup=()=>stopLive();n.cleanup=stopLive;n.append(status,start,stop);if(autoStart)startLive();return{start,stop,status,cleanup:stopLive};}
export function renderCameraTile(w,r={}){const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-tile");n.append(el("h3",{text:w.title||c.title}),img(r,c),el("p",{text:`${c.state} · ${c.reason}`}));actionList(n,c.actions,r);n.append(actionButton("Details",false,()=>openCameraDetailPanel(w.config,r,n),n,"camera-action"));return n;}
export function renderCameraGrid(w,r={}){const n=art("dm-camera-grid");n.append(el("h3",{text:w.title||"Camera grid"}));(w.config?.cameras||[]).forEach(c=>n.append(renderCameraTile({type:"camera-tile",config:c},r)));if(!(w.config?.cameras||[]).length)n.append(el("p",{text:"No cameras configured."}));return n;}
export function renderCameraCarousel(w,r={}){const n=art("dm-camera-carousel"),cams=w.config?.cameras||[];let index=Math.max(0,Math.min(w.config?.initialIndex||0,cams.length-1)),timer=null,paused=false;const slide=el("div",{attrs:{tabindex:"0","aria-live":"polite"}}),prev=el("button",{text:"Previous",attrs:{type:"button"}}),next=el("button",{text:"Next",attrs:{type:"button"}}),pause=el("button",{text:"Pause",attrs:{type:"button"}});function draw(){slide.replaceChildren();if(!cams.length){slide.textContent="No cameras configured.";return;}const c=normalizeCamera(r,cams[index]);slide.setAttribute("aria-label",`Slide ${index+1} of ${cams.length}: ${c.title}`);slide.append(renderCameraTile({type:"camera-tile",config:cams[index]},r));}function go(d){index=(index+d+cams.length)%cams.length;draw();}prev.addEventListener("click",()=>go(-1));next.addEventListener("click",()=>go(1));slide.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")go(-1);if(e.key==="ArrowRight")go(1);});if(w.config?.autoRotateMs){timer=globalThis.setInterval?.(()=>{if(!paused)go(1);},w.config.autoRotateMs);pause.addEventListener("click",()=>{paused=!paused;pause.textContent=paused?"Resume":"Pause";});n.cleanup=()=>globalThis.clearInterval?.(timer);}n.append(el("h3",{text:w.title||"Camera carousel"}),slide,prev,next);if(w.config?.autoRotateMs)n.append(pause);draw();return n;}
export const renderCameraSnapshot=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-snapshot");n.append(el("h3",{text:w.title||"Camera snapshot"}),img(r,c),actionButton("Refresh snapshot",false,()=>refreshCameraSnapshot(r,c),n,"camera-action"));return n;};
export const renderCameraLive=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-live");n.append(el("h3",{text:w.title||"Camera live"}));liveWidget(c,r,n,{autoStart:w.config?.autoStart===true});return n;};
const stateLine=(w,r,key,label)=>{const c=normalizeCamera(r,w.config||{}),n=art(`dm-camera-${key}`),id=c[`${key}EntityId`],e=get(r,id);n.append(el("h3",{text:w.title||label}),el("p",{text:e?`${label}: ${e.state}`:`${label}: ${id?"missing":"unconfigured"}`}));return n;};
export const renderCameraMotion=(w,r={})=>stateLine(w,r,"motion","Camera motion");export const renderCameraRecording=(w,r={})=>stateLine(w,r,"recording","Camera recording");
export const renderCameraPtz=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-ptz");n.append(el("h3",{text:w.title||"Camera PTZ"}));let last=0;for(const a of c.ptzActions){const b=actionButton(a.title||"PTZ",a.disabled||validateCameraAction(a,r).length,()=>{const t=Date.now();if(t-last<(w.config?.guardMs||250))return false;last=t;return runAction(a,r);},n,"camera-ptz");n.append(b);}if(!c.ptzActions.length)n.append(el("p",{text:"No PTZ actions configured."}));return n;};
export const renderCameraPresets=(w,r={})=>{const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-presets");n.append(el("h3",{text:w.title||"Camera presets"}));actionList(n,c.presets,r,"camera-preset");if(!c.presets.length)n.append(el("p",{text:"No presets configured."}));return n;};
export function filteredCameras(w,r={}){const c=w.config||{},q=String(c.search||"").toLowerCase(),state=c.stateFilter||"all";let xs=(c.cameras||[]).map(x=>normalizeCamera(r,x));xs=xs.filter(x=>(!q||x.title.toLowerCase().includes(q)||x.entityId.includes(q))&&(state==="all"||x.state===state));xs.sort((a,b)=>c.sort==="state"?a.state.localeCompare(b.state)||a.title.localeCompare(b.title):a.title.localeCompare(b.title));return xs;}
export function renderCamerasOverview(w,r={}){let local={...(w.config||{})};const n=art("dm-cameras-overview"),list=el("div"),summary=el("p"),search=el("input",{attrs:{type:"search","aria-label":"Search cameras",value:local.search||""}}),filter=el("select",{attrs:{"aria-label":"Camera state filter"}}),sort=el("select",{attrs:{"aria-label":"Sort cameras"}});for(const [sel,vals,cur]of[[filter,["all","idle","recording","unavailable"],local.stateFilter||"all"],[sort,["name","state"],local.sort||"name"]])for(const v of vals){const o=el("option",{text:v,attrs:{value:v}});o.selected=v===cur;sel.append(o);}filter.value=local.stateFilter||"all";sort.value=local.sort||"name";function draw(){local.search=search.value;local.stateFilter=filter.value;local.sort=sort.value;const xs=filteredCameras({config:local},r);summary.textContent=`${xs.length} shown · ${(local.cameras||[]).length} configured`;list.replaceChildren();xs.forEach(x=>list.append(el("p",{text:`${x.title} · ${x.state} · ${x.reason}`})));if(!xs.length)list.append(el("p",{text:"No cameras match the current filters."}));}search.addEventListener("input",draw);filter.addEventListener("change",draw);sort.addEventListener("change",draw);n.append(el("h3",{text:w.title||"Cameras"}),search,filter,sort,summary,list);draw();return n;}
export function renderCameraPanel(w,r={}){const c=normalizeCamera(r,w.config||{}),n=art("dm-camera-panel");n.setAttribute("role","dialog");n.append(actionButton("Close",false,()=>{n.cleanup?.();w.config?.close?.();},n,"camera-action"),el("h3",{text:`Camera detail: ${c.title}`}),el("p",{text:`Source ${c.entityId||"none"} · ${c.reason}`}),img(r,c));if(w.config?.detailLive)n.live=liveWidget(c,r,n,{autoStart:false});["onlineEntityId","motionEntityId","occupancyEntityId","recordingEntityId","privacyEntityId","batteryEntityId","signalEntityId","lastUpdateEntityId"].forEach(k=>n.append(el("p",{text:`${k}: ${c[k]||"unconfigured"}`})));actionList(n,c.actions,r);return n;}
export function openCameraDetailPanel(config,r={},trigger=null){let panel;const opened=openSharedDetailPanel({trigger,label:"Camera detail",render:({close})=>{panel=renderCameraPanel({type:"camera-control-panel",config:{...config,close}},r);return panel;}});const old=opened.close;opened.close=()=>{panel?.cleanup?.();old();};return opened.panel;}
export function camerasSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-cameras-section",attrs:{"data-section-id":section.id}});n.append(el("h3",{text:section.title||"Cameras"}),renderWidgetLayout(section.config?.widgets||[{id:`${section.id}-cameras-overview`,type:"cameras-overview",config:section.config||{},layout:{size:"full"}},{id:`${section.id}-camera-grid`,type:"camera-grid",config:section.config||{},layout:{size:"large"}}],context,context.widgetRegistry));return n;}
const cfg=()=>({cameras:[],actions:[],ptzActions:[],presets:[],autoStart:false}),one=()=>({entityId:"",...cfg()}),validator=c=>Object.values(c||{}).some(v=>String(v).includes("{{"))?[{field:"config",message:"Templates are not supported."}]:[];const widgets=[["camera-tile","Camera tile",renderCameraTile,one],["camera-grid","Camera grid",renderCameraGrid,cfg],["camera-carousel","Camera carousel",renderCameraCarousel,cfg],["camera-snapshot","Camera snapshot",renderCameraSnapshot,one],["camera-live","Camera live",renderCameraLive,one],["camera-motion","Camera motion",renderCameraMotion,one],["camera-recording","Camera recording",renderCameraRecording,one],["camera-ptz","Camera PTZ",renderCameraPtz,one],["camera-presets","Camera presets",renderCameraPresets,one],["cameras-overview","Cameras overview",renderCamerasOverview,cfg],["camera-control-panel","Camera control panel",renderCameraPanel,one]];
export const CAMERAS_MODULE={id:"cameras",schemaVersion:1,sections:[{type:"cameras",displayName:"Cameras",renderer:camerasSectionRenderer,defaultConfig:()=>({widgets:[{type:"cameras-overview",config:cfg(),layout:{size:"full"}},{type:"camera-grid",config:cfg(),layout:{size:"large"}}]})}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,validator,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"cameras-editor",title:"Cameras editor"}],navigationEntries:[{sectionType:"cameras",icon:"camera",title:"Cameras"}],actions:["camera.service"],detailPanels:[{type:"camera-control-panel"}],defaultLayouts:[{sectionType:"cameras",widgets:["cameras-overview","camera-grid"]}]};
