import { el, emptyState } from "../render/dom.js"; import { renderWidgetLayout } from "../widgets/runtime.js"; import { normalizeMeasurement, convertUnit, safePercentage, formatNumber, clamp } from "./shared-measurements.js"; import { openSharedDetailPanel } from "./detail-panel-controller.js";
export const ENERGY_WIDGET_TYPES=["energy-flow","energy-summary","power-gauge","energy-history","battery-summary","grid-summary","solar-summary","energy-control-panel"];
export const defaultEnergyConfig=()=>({});
export const convertPower=(v,f,t)=>convertUnit(v,f,t,"power"); export const convertEnergy=(v,f,t)=>convertUnit(v,f,t,"energy");
function dir(value,positiveConvention,positiveName,negativeName,deadband=0){ if(!Number.isFinite(value))return "malformed"; if(Math.abs(value)<=deadband)return "idle"; return value>0?positiveName:negativeName; }
export const gridDirection=(v,{signConvention="positive-import",deadband=0}={})=>dir(v,signConvention,signConvention==="positive-import"?"importing":"exporting",signConvention==="positive-import"?"exporting":"importing",deadband);
export const batteryDirection=(v,{signConvention="positive-charge",deadband=0}={})=>dir(v,signConvention,signConvention==="positive-charge"?"charging":"discharging",signConvention==="positive-charge"?"discharging":"charging",deadband);
export function deriveHomeLoad(i,{unit="kW",allowNegative=false}={}){ const keys=["solarProduction","gridImport","batteryDischarge","gridExport","batteryCharge"], missing=[]; let vals={}; for(const k of keys){const x=i[k]; if(!x||!Number.isFinite(x.value)||!x.unit){missing.push(k);continue;} const c=convertPower(x.value,x.unit,unit); if(!c.ok){return {complete:false,reason:"incompatible-unit",input:k,missingInputs:missing};} vals[k]=c.value;} if(missing.length)return {complete:false,reason:"missing-input",missingInputs:missing}; let value=vals.solarProduction+vals.gridImport+vals.batteryDischarge-vals.gridExport-vals.batteryCharge; if(value<0&&!allowNegative)return {complete:false,reason:"negative-consumption",value,missingInputs:[]}; return {complete:true,value,unit,formula:"solar + grid import + battery discharge - grid export - battery charge"};}
export const selfConsumptionPercentage=({solarProduction,gridExport})=>safePercentage(solarProduction-gridExport,solarProduction); export const selfSufficiencyPercentage=({solarProduction,batteryDischarge,homeConsumption})=>safePercentage(solarProduction+batteryDischarge,homeConsumption); export const capacityUtilization=(power,capacity)=>safePercentage(power,capacity); export function thresholdState(v,{warning,critical}={}){ if(!Number.isFinite(v))return "unavailable"; if(Number.isFinite(critical)&&v>=critical)return "critical"; if(Number.isFinite(warning)&&v>=warning)return "warning"; return "normal";}
const state=(r,id,o)=>normalizeMeasurement(r,id,o);
function article(w,cls){const n=el("article",{className:`dm-widget ${cls}`}); n.append(el("h3",{text:w.title||w.type})); return n;}
export function openEnergyDetailPanel(item,r,trigger){return openSharedDetailPanel({trigger,label:item.title||"Energy detail",render(){const p=el("section",{attrs:{role:"dialog"}}), d=el("div"); d.append(el("p",{text:`Status: ${item.status||"read-only"}`}),el("p",{text:`Entity: ${item.entityId||"not configured"}`}),el("p",{text:`Value: ${item.displayValue||"Unavailable"}`})); p.append(d,el("button",{text:"Close",attrs:{type:"button"}})); return p;}}).panel;}
export function renderEnergyFlow(w,r={}){const c=w.config||{},unit=c.displayUnit||"kW",p=c.precision??1,n=article(w,"dm-energy-flow"); const rows=[['solar','Solar',c.solarEntityId],['grid','Grid',c.gridEntityId||c.gridImportEntityId],['home','Home',c.homeEntityId],['battery','Battery',c.batteryEntityId||c.batteryChargeEntityId],['load','Load',c.loadEntityId]].filter(x=>x[2]); const svg=el("svg",{attrs:{role:"img","aria-label":"Energy flow diagram with textual source values",viewBox:"0 0 320 160"}}); rows.forEach((x,i)=>{const m=state(r,x[2],{kind:"power",unit,precision:p,locale:r.locale}); const g=el("g",{attrs:{"data-source":x[0],"data-status":m.available?"available":m.missing?"missing":m.unavailable?"unavailable":"malformed"}}); g.append(el("text",{text:`${x[1]} ${m.displayValue}`,attrs:{x:10,y:25+i*25}})); svg.append(g); n.append(el("p",{text:`${x[1]}: ${m.displayValue}`}));}); if(!rows.length)n.append(emptyState("No energy entities configured.")); else n.append(svg); return n;}
export function renderEnergySummary(w,r={}){const n=article(w,"dm-energy-summary"), metrics=w.config?.metrics||[]; if(!metrics.length)n.append(emptyState("No summary metrics configured.")); for(const m of metrics.filter(x=>x.visible!==false)){const kind=m.kind||m.metricType||"power", mm=state(r,m.entityId,{kind:kind.includes("energy")?"energy":kind,unit:m.unit,precision:m.precision??1,locale:r.locale}); n.append(el("p",{text:`${m.title||m.id||m.entityId}: ${mm.displayValue}`}));} return n;}
export function renderPowerGauge(w,r={}){const c=w.config||{},m=state(r,c.entityId,{kind:"power",unit:c.unit||"kW",precision:c.precision??1,locale:r.locale}),n=article(w,"dm-power-gauge"); n.dataset.thresholdState=thresholdState(m.normalizedValue,{warning:Number(c.warning),critical:Number(c.critical)}); n.append(el("p",{text:`Current power: ${m.displayValue}`,attrs:{"aria-label":`Current power ${m.displayValue}`}})); return n;}
export function renderEnergyHistory(w,r={}){const n=article(w,"dm-energy-history"), table=el("table",{attrs:{"aria-label":"Energy history summary"}}); let count=0; for(const s of w.config?.series||[]){const pts=(s.points||r.history?.[s.datasetKey]||[]).filter(p=>Number.isFinite(Number(p.value))&&Number.isFinite(new Date(p.timestamp).getTime())); count+=pts.length; for(const p of pts)table.append(el("tr",{},[el("td",{text:new Date(p.timestamp).toLocaleString(r.locale||"en-US")}),el("td",{text:String(p.value)})]));} n.append(count?table:emptyState("No history data configured.")); return n;}
export function renderBatterySummary(w,r={}){const c=w.config||{},soc=state(r,c.socEntityId,{kind:"percent",precision:0,locale:r.locale}),pow=state(r,c.powerEntityId||c.chargeEntityId,{kind:"power",unit:c.unit||"kW",locale:r.locale}); const n=article(w,"dm-battery-summary"); n.append(el("p",{text:`State of charge: ${soc.displayValue}`}),el("p",{text:`Power: ${pow.displayValue}`}),el("p",{text:`Direction: ${batteryDirection(pow.normalizedValue,{signConvention:c.signConvention,deadband:c.deadband})}`})); return n;}
export function renderGridSummary(w,r={}){const c=w.config||{},pow=state(r,c.powerEntityId||c.importEntityId,{kind:"power",unit:c.unit||"kW",locale:r.locale}),n=article(w,"dm-grid-summary"); n.append(el("p",{text:`Direction: ${gridDirection(pow.normalizedValue,{signConvention:c.signConvention,deadband:c.deadband})}`}),el("p",{text:`Current power: ${pow.displayValue}`})); return n;}
export function renderSolarSummary(w,r={}){const c=w.config||{},pow=state(r,c.powerEntityId,{kind:"power",unit:c.unit||"kW",locale:r.locale}),n=article(w,"dm-solar-summary"); n.append(el("p",{text:`Production: ${pow.displayValue}`}),el("p",{text:`Capacity utilization: ${capacityUtilization(pow.normalizedValue,Number(c.capacity)).ok?formatNumber(capacityUtilization(pow.normalizedValue,Number(c.capacity)).value,{precision:0,unit:"%"}):"Unavailable"}`})); return n;}
export function renderEnergyControlPanel(w){const n=article(w,"dm-energy-control-panel"); n.append(emptyState("Energy controls are read-only unless a navigation or detail action is configured.")); return n;}
const renderers={"energy-flow":renderEnergyFlow,"energy-summary":renderEnergySummary,"power-gauge":renderPowerGauge,"energy-history":renderEnergyHistory,"battery-summary":renderBatterySummary,"grid-summary":renderGridSummary,"solar-summary":renderSolarSummary,"energy-control-panel":renderEnergyControlPanel};
export function energySectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-energy-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Energy"}),renderWidgetLayout(section.config?.widgets||[],context,context.widgetRegistry)); return n;}
export const ENERGY_MODULE={id:"energy",schemaVersion:1,sections:[{type:"energy",displayName:"Energy",icon:"energy",renderer:energySectionRenderer,supportedWidgets:ENERGY_WIDGET_TYPES}],widgets:ENERGY_WIDGET_TYPES.map(type=>({type,displayName:type.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "),renderer:renderers[type],defaultConfig:defaultEnergyConfig,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"energy-editor",title:"Energy editor"}],navigationEntries:[{sectionType:"energy",icon:"energy",title:"Energy"}],actions:["navigate.view","navigate.section","detail.open"],detailPanels:[{id:"energy-detail",title:"Energy detail"}],defaultLayouts:[{sectionType:"energy",widgets:["energy-flow","energy-summary"]}]};
