import { el, emptyState } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { normalizeMeasurement, convertUnit, safePercentage, formatNumber } from "./shared-measurements.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";

export const ENERGY_WIDGET_TYPES = ["energy-flow", "energy-summary", "power-gauge", "energy-history", "battery-summary", "grid-summary", "solar-summary", "energy-control-panel"];
export const defaultEnergyConfig = () => ({});
export const convertPower = (v, f, t) => convertUnit(v, f, t, "power");
export const convertEnergy = (v, f, t) => convertUnit(v, f, t, "energy");
const statusOf = (m) => m?.available ? "available" : m?.missing ? "missing" : m?.unavailable ? "unavailable" : m?.stale ? "stale" : "malformed";
function direction(value, positiveConvention, positiveName, negativeName, deadband = 0) { if (!Number.isFinite(value)) return "malformed"; if (Math.abs(value) <= Number(deadband || 0)) return "idle"; return value > 0 ? positiveName : negativeName; }
export const gridDirection = (v, { signConvention = "positive-import", deadband = 0 } = {}) => direction(v, signConvention, signConvention === "positive-import" ? "importing" : "exporting", signConvention === "positive-import" ? "exporting" : "importing", deadband);
export const batteryDirection = (v, { signConvention = "positive-charge", deadband = 0 } = {}) => direction(v, signConvention, signConvention === "positive-charge" ? "charging" : "discharging", signConvention === "positive-charge" ? "discharging" : "charging", deadband);
function measurement(runtime, id, options) { return normalizeMeasurement(runtime, id, { locale: runtime.locale, ...options }); }
export function normalizeGrid(runtime, c = {}) {
  const unit = c.displayUnit || c.unit || "kW", precision = c.precision ?? 1, deadband = Number(c.deadband || 0);
  if (c.gridModel === "separate" || c.gridImportEntityId || c.gridExportEntityId) {
    const imp = measurement(runtime, c.gridImportEntityId, { kind: "power", unit, precision }), exp = measurement(runtime, c.gridExportEntityId, { kind: "power", unit, precision });
    const value = (imp.available ? imp.normalizedValue : 0) - (exp.available ? exp.normalizedValue : 0);
    return { model: "separate", import: imp, export: exp, direction: imp.available || exp.available ? (Math.abs(value) <= deadband ? "idle" : value >= 0 ? "importing" : "exporting") : statusOf(imp.missing ? exp : imp), value };
  }
  const signed = measurement(runtime, c.gridEntityId, { kind: "power", unit, precision });
  return { model: "signed", signed, import: signed, export: signed, direction: signed.available ? gridDirection(signed.normalizedValue, { signConvention: c.gridSignConvention || c.signConvention, deadband }) : statusOf(signed), value: signed.normalizedValue };
}
export function normalizeBattery(runtime, c = {}) {
  const unit = c.displayUnit || c.unit || "kW", precision = c.precision ?? 1, deadband = Number(c.deadband || 0);
  const soc = measurement(runtime, c.batterySocEntityId || c.socEntityId, { kind: "percent", precision: 0 });
  if (c.batteryModel === "separate" || c.batteryChargeEntityId || c.batteryDischargeEntityId) {
    const charge = measurement(runtime, c.batteryChargeEntityId || c.chargeEntityId, { kind: "power", unit, precision }), discharge = measurement(runtime, c.batteryDischargeEntityId || c.dischargeEntityId, { kind: "power", unit, precision });
    const value = (charge.available ? charge.normalizedValue : 0) - (discharge.available ? discharge.normalizedValue : 0);
    return { model: "separate", soc, charge, discharge, direction: charge.available || discharge.available ? (Math.abs(value) <= deadband ? "idle" : value >= 0 ? "charging" : "discharging") : statusOf(charge.missing ? discharge : charge), value };
  }
  const signed = measurement(runtime, c.batteryEntityId || c.powerEntityId, { kind: "power", unit, precision });
  return { model: "signed", soc, charge: signed, discharge: signed, signed, direction: signed.available ? batteryDirection(signed.normalizedValue, { signConvention: c.batterySignConvention || c.signConvention, deadband }) : statusOf(signed), value: signed.normalizedValue };
}
export function deriveHomeLoad(inputs, { unit = "kW", allowNegative = false } = {}) {
  const keys = ["solarProduction", "gridImport", "batteryDischarge", "gridExport", "batteryCharge"], missingInputs = [], vals = {};
  for (const key of keys) { const x = inputs[key]; if (!x || !Number.isFinite(x.value) || !x.unit) { missingInputs.push(key); continue; } const c = convertPower(x.value, x.unit, unit); if (!c.ok) return { complete: false, reason: "incompatible-unit", input: key, missingInputs }; vals[key] = c.value; }
  if (missingInputs.length) return { complete: false, reason: "missing-input", missingInputs };
  const value = vals.solarProduction + vals.gridImport + vals.batteryDischarge - vals.gridExport - vals.batteryCharge; // home = solar + grid import + battery discharge - grid export - battery charge
  if (value < 0 && !allowNegative) return { complete: false, reason: "negative-consumption", value, missingInputs: [] };
  return { complete: true, value, unit, formula: "solar + grid import + battery discharge - grid export - battery charge" };
}
export const selfConsumptionPercentage = ({ solarProduction, gridExport }) => safePercentage(solarProduction - gridExport, solarProduction);
export const selfSufficiencyPercentage = ({ solarProduction, batteryDischarge, homeConsumption }) => safePercentage(solarProduction + batteryDischarge, homeConsumption);
export const capacityUtilization = (power, capacity) => safePercentage(power, capacity);
export function thresholdState(v, { warning, critical } = {}) { if (!Number.isFinite(v)) return "unavailable"; if (Number.isFinite(Number(critical)) && v >= Number(critical)) return "critical"; if (Number.isFinite(Number(warning)) && v >= Number(warning)) return "warning"; return "normal"; }
function article(w, cls) { const n = el("article", { className: `dm-widget ${cls}` }); n.append(el("h3", { text: w.title || w.config?.title || w.type })); return n; }
function power(runtime, id, config = {}) { return measurement(runtime, id, { kind: "power", unit: config.displayUnit || config.unit || "kW", precision: config.precision ?? 1, staleAfterMs: config.staleAfterMs }); }
export function homeLoad(runtime, c = {}) { if (c.homeMode === "direct" || c.homeLoadMode === "direct" || c.homeEntityId) return { mode: "direct", measurement: power(runtime, c.homeEntityId, c) }; if (c.homeMode !== "derived" && c.homeLoadMode !== "derived") return { mode: "none", complete: false, reason: "home-mode-not-configured" }; const src = { solarProduction: power(runtime, c.solarEntityId, c), gridImport: power(runtime, c.gridImportEntityId, c), gridExport: power(runtime, c.gridExportEntityId, c), batteryCharge: power(runtime, c.batteryChargeEntityId, c), batteryDischarge: power(runtime, c.batteryDischargeEntityId, c) }; return { mode: "derived", sources: src, ...deriveHomeLoad(Object.fromEntries(Object.entries(src).map(([k, m]) => [k, { value: m.normalizedValue, unit: m.normalizedUnit }])) , { unit: c.displayUnit || c.unit || "kW", allowNegative: c.allowNegativeHomeLoad }) }; }
export function openEnergyDetailPanel(item, runtime = {}, trigger) { return openSharedDetailPanel({ trigger, label: item.title || "Energy detail", render: ({ close }) => { const p = el("section", { attrs: { role: "dialog" } }); const closeButton = el("button", { text: "Close", attrs: { type: "button" } }); closeButton.addEventListener("click", close); p.append(closeButton, el("h3", { text: item.title || "Energy detail" }), el("p", { text: `Status: ${item.status || item.reason || "read-only"}` }), el("p", { text: `Direction: ${item.direction || "not applicable"}` }), el("p", { text: `Entity: ${item.entityId || item.sourceEntityId || "not configured"}` }), el("p", { text: `Unit: ${item.normalizedUnit || item.unit || "not configured"}` }), el("p", { text: `Value: ${item.displayValue || "Unavailable"}` }), el("pre", { text: JSON.stringify(item.attributes || {}, null, 2) })); return p; } }).panel; }
export function renderEnergyFlow(w, runtime = {}) { const c = w.config || {}, unit = c.displayUnit || "kW", precision = c.precision ?? 1, n = article(w, "dm-energy-flow"); const reduced = runtime.reducedMotion === true || globalThis.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches; const grid = normalizeGrid(runtime, c), battery = normalizeBattery(runtime, c), home = homeLoad(runtime, c); const rows = [{ key: "solar", label: c.solarLabel || "Solar", icon: c.solarIcon || "☀", m: power(runtime, c.solarEntityId, { unit, precision }) }, { key: "grid", label: c.gridLabel || "Grid", icon: c.gridIcon || "↔", m: grid.import, direction: grid.direction }, { key: "battery", label: c.batteryLabel || "Battery", icon: c.batteryIcon || "🔋", m: battery.charge, direction: battery.direction }, { key: "home", label: c.homeLabel || "Home", icon: c.homeIcon || "⌂", m: home.measurement || { displayValue: home.complete ? formatNumber(home.value, { precision, unit }) : "Unavailable", available: Boolean(home.complete), reason: home.reason }, direction: home.complete ? "consuming" : home.reason }, { key: "load", label: c.loadLabel || "Load", icon: c.loadIcon || "•", m: power(runtime, c.loadEntityId, { unit, precision }) }].filter((x) => x.key !== "load" || c.loadEntityId); const svg = el("svg", { attrs: { role: "img", "aria-label": "Energy flow diagram with textual directions and source values", viewBox: "0 0 360 180", "data-reduced-motion": String(Boolean(reduced)) } }); rows.forEach((row, index) => { const moving = row.direction && !["idle", "missing", "unavailable", "malformed", "incompatible-unit"].includes(row.direction) && !reduced; const g = el("g", { attrs: { "data-source": row.key, "data-status": statusOf(row.m), "data-direction": row.direction || "none", "data-animated": String(Boolean(moving)) } }); g.append(el("text", { text: `${row.icon} ${row.label}: ${row.m.displayValue} ${row.direction ? `(${row.direction})` : ""}`, attrs: { x: 8, y: 24 + index * 28 } })); if (moving) g.append(el("path", { attrs: { d: `M 220 ${20 + index * 28} L 340 ${20 + index * 28}`, class: "dm-flow-moving" } })); svg.append(g); n.append(el("p", { text: `${row.label}: ${row.m.displayValue}${row.direction ? ` · ${row.direction}` : ""}${row.m.reason ? ` · ${row.m.reason}` : ""}` })); }); n.append(rows.length ? svg : emptyState("No energy entities configured.")); return n; }
export function renderEnergySummary(w, runtime = {}) { const c = w.config || {}, n = article(w, "dm-energy-summary"), metrics = c.metrics || []; if (!metrics.length) n.append(emptyState("No summary metrics configured.")); for (const metric of metrics.filter((x) => x.visible !== false)) { let display = "Unavailable", raw = null; const precision = metric.precision ?? c.precision ?? 1; if (["self-consumption", "self-sufficiency"].includes(metric.metricType)) { const pct = metric.metricType === "self-consumption" ? selfConsumptionPercentage(metric.values || {}) : selfSufficiencyPercentage(metric.values || {}); display = pct.ok ? formatNumber(pct.value, { precision, unit: "%" }) : `Unavailable (${pct.reason})`; raw = pct.value; } else { const kind = metric.kind || (metric.metricType?.includes("energy") ? "energy" : metric.metricType === "cost" ? "currency" : metric.metricType === "carbon-intensity" ? "carbon" : "power"); const m = measurement(runtime, metric.entityId, { kind, unit: metric.unit, precision }); display = m.displayValue; raw = m.normalizedValue; } const th = thresholdState(raw, metric.thresholds || metric); n.append(el("p", { text: `${metric.icon || ""} ${metric.title || metric.metricType || metric.entityId}: ${display} · ${th}`.trim(), attrs: { "data-metric-id": metric.id || "", "data-threshold-state": th } })); } return n; }
export function renderPowerGauge(w, runtime = {}) { const c = w.config || {}, m = power(runtime, c.entityId, c), n = article(w, "dm-power-gauge"), min = Number(c.min ?? 0), max = Number(c.max ?? 100), state = thresholdState(m.normalizedValue, c); const pct = Number.isFinite(m.normalizedValue) && max > min ? Math.max(0, Math.min(100, (m.normalizedValue - min) / (max - min) * 100)) : 0; let peakText = "Peak: not configured"; const peak = c.peakValue ?? runtime.energyPeaks?.[c.entityId]; if (peak !== undefined && peak !== null && peak !== "") { const converted = convertPower(Number(peak), c.peakUnit || c.unit || m.normalizedUnit, m.normalizedUnit || c.unit || "kW"); peakText = converted.ok ? `Peak: ${formatNumber(converted.value, { precision: c.precision ?? 1, unit: converted.unit })}` : `Peak unavailable (${converted.reason})`; } n.dataset.thresholdState = state; n.append(el("meter", { attrs: { min: String(min), max: String(max), value: String(Number.isFinite(m.normalizedValue) ? m.normalizedValue : min), "aria-label": `Current power ${m.displayValue}; threshold ${state}` } }), el("p", { text: `Current power: ${m.displayValue} · ${state} · ${pct.toFixed(0)}%` }), el("p", { text: peakText })); if (!(max > min)) n.append(emptyState("Invalid gauge configuration: min must be less than max.")); return n; }
export function renderEnergyHistory(w, runtime = {}) { const c = w.config || {}, n = article(w, "dm-energy-history"), controls = el("div"), table = el("table", { attrs: { "aria-label": "Energy history summary" } }), legend = el("ul", { attrs: { "aria-label": "Energy history legend" } }), chart = el("svg", { attrs: { role: "img", "aria-label": "Energy history chart", viewBox: "0 0 320 120", "data-chart-type": c.chartType || "line" } }); const ranges = c.timeframes || [c.defaultTimeframe || "all"]; const selector = el("select", { attrs: { "aria-label": "Energy history timeframe" } }); for (const range of ranges) selector.append(el("option", { text: range, attrs: { value: range } })); selector.value = c.defaultTimeframe || ranges[0] || "all"; controls.append(selector); const render = () => { table.replaceChildren?.(); legend.replaceChildren?.(); chart.replaceChildren?.(); let count = 0; for (const series of (c.series || []).filter((s) => s.visible !== false)) { const chartType = series.chartType || c.chartType || "line"; legend.append(el("li", { text: `${series.title || series.id}: ${chartType} axis ${series.axis || "left"} ${series.unit || ""}` })); const source = series.points || runtime.history?.[series.datasetKey] || runtime.datasets?.[series.datasetKey] || []; const rangePoints = source.filter((p) => !p.timeframe || selector.value === "all" || p.timeframe === selector.value); const points = rangePoints.filter((p) => Number.isFinite(Number(p.value)) && Number.isFinite(new Date(p.timestamp).getTime())); points.forEach((p, index) => { count++; table.append(el("tr", {}, [el("td", { text: series.title || series.id || "Series" }), el("td", { text: new Date(p.timestamp).toLocaleString(runtime.locale || "en-US") }), el("td", { text: formatNumber(Number(p.value), { precision: series.precision ?? 1, unit: series.unit || "" }) })])); chart.append(el(chartType === "bar" ? "rect" : "circle", { attrs: { "data-series-id": series.id || "", x: String(10 + index * 20), y: String(100 - Number(p.value)), width: "8", height: String(Number(p.value)), r: "3" } })); }); } if (!count) table.append(el("tr", {}, [el("td", { text: "No history data configured." })])); }; selector.addEventListener("change", render); render(); n.append(controls, legend, chart, table); return n; }
export function renderBatterySummary(w, runtime = {}) { const c = w.config || {}, b = normalizeBattery(runtime, c), n = article(w, "dm-battery-summary"); n.append(el("p", { text: `State of charge: ${b.soc.displayValue}` }), el("p", { text: `Direction: ${b.direction}` }), el("p", { text: `Power: ${(b.signed || b.charge)?.displayValue || "Unavailable"}` }), el("p", { text: `Capacity: ${c.capacity ?? "not configured"} · usable ${c.usableCapacity ?? "not configured"} · reserve ${c.minReserve ?? "not configured"}` }), el("p", { text: `ETA: ${c.eta || runtime.energyRuntime?.batteryEta || "not configured"}` })); return n; }
export function renderGridSummary(w, runtime = {}) { const c = w.config || {}, g = normalizeGrid(runtime, c), n = article(w, "dm-grid-summary"); n.append(el("p", { text: `Direction: ${g.direction}` }), el("p", { text: `Current import/export: ${g.import?.displayValue || "Unavailable"} / ${g.export?.displayValue || "Unavailable"}` }), el("p", { text: `Daily import/export: ${measurement(runtime, c.dailyImportEntityId, { kind: "energy", unit: c.energyUnit || "kWh" }).displayValue} / ${measurement(runtime, c.dailyExportEntityId, { kind: "energy", unit: c.energyUnit || "kWh" }).displayValue}` }), el("p", { text: `Tariff: ${c.tariff || "not configured"} · Cost: ${c.costEntityId ? measurement(runtime, c.costEntityId, { kind: "currency" }).displayValue : "Unavailable"}` })); return n; }
export function renderSolarSummary(w, runtime = {}) { const c = w.config || {}, prod = power(runtime, c.solarEntityId || c.powerEntityId, c), daily = measurement(runtime, c.dailySolarEntityId || c.dailyProductionEntityId, { kind: "energy", unit: c.energyUnit || "kWh" }), n = article(w, "dm-solar-summary"), util = capacityUtilization(prod.normalizedValue, Number(c.capacity)); n.append(el("p", { text: `Production: ${prod.displayValue}` }), el("p", { text: `Daily production: ${daily.displayValue}` }), el("p", { text: `Capacity utilization: ${util.ok ? formatNumber(util.value, { precision: 0, unit: "%" }) : "Unavailable"}` }), el("p", { text: `Forecast: ${c.forecast || runtime.energyRuntime?.solarForecast || "not configured"}` })); return n; }
export function renderEnergyControlPanel(w) { const n = article(w, "dm-energy-control-panel"); n.append(emptyState("Energy controls are read-only unless a navigation or detail action is configured.")); return n; }
const renderers = { "energy-flow": renderEnergyFlow, "energy-summary": renderEnergySummary, "power-gauge": renderPowerGauge, "energy-history": renderEnergyHistory, "battery-summary": renderBatterySummary, "grid-summary": renderGridSummary, "solar-summary": renderSolarSummary, "energy-control-panel": renderEnergyControlPanel };
export function energySectionRenderer(section, cards, context) { const n = el("section", { className: "dashboardmodern-section dm-energy-section", attrs: { "data-section-id": section.id } }); n.append(el("h3", { text: section.title || "Energy" }), renderWidgetLayout(section.config?.widgets || [], context, context.widgetRegistry)); return n; }
function defaultEnergySectionConfig() { return { widgets: [{ id: "energy-flow", type: "energy-flow", config: {} }, { id: "energy-summary", type: "energy-summary", config: { metrics: [] } }], card_ids: [] }; }
export const ENERGY_MODULE = { id: "energy", schemaVersion: 1, sections: [{ type: "energy", displayName: "Energy", icon: "energy", renderer: energySectionRenderer, supportedWidgets: ENERGY_WIDGET_TYPES, defaultConfig: defaultEnergySectionConfig }], widgets: ENERGY_WIDGET_TYPES.map((type) => ({ type, displayName: type.split("-").map((x) => x[0].toUpperCase() + x.slice(1)).join(" "), renderer: renderers[type], defaultConfig: defaultEnergyConfig, schemaVersion: 1, supportedLayoutSizes: ["small", "medium", "large", "full"] })), editorPanels: [{ id: "energy-editor", title: "Energy editor" }], navigationEntries: [{ sectionType: "energy", icon: "energy", title: "Energy" }], actions: ["navigate.view", "navigate.section", "detail.open"], detailPanels: [{ id: "energy-detail", title: "Energy detail" }], defaultLayouts: [{ sectionType: "energy", widgets: ["energy-flow", "energy-summary"] }] };
