import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { summarizeLights } from "./lights.js";
const ENTITY_RE=/^[a-z0-9_]+\.[a-z0-9_]+$/; const OPS=new Set(["equals","not-equals","on","off","home","unavailable","numeric-above","numeric-below"]);
const stateOf=(r,id)=>ENTITY_RE.test(id)?r.getEntityState?.(id):null; const unavailable=e=>!e||["unavailable","unknown"].includes(e.state); const num=v=>Number.isFinite(Number(v))?Number(v):null;
function activeBy(rule={},e){const op=OPS.has(rule.operator)?rule.operator:"equals", s=e?.state; if(op==="unavailable")return unavailable(e); if(!e)return false; if(op==="on")return s==="on"; if(op==="off")return s==="off"; if(op==="home")return s==="home"; if(op==="equals")return s===String(rule.expected); if(op==="not-equals")return s!==String(rule.expected); const n=num(s), ex=num(rule.expected); if(n===null||ex===null)return false; return op==="numeric-above"?n>ex:n<ex;}
export function evaluateAlertRule(rule,runtime={}){return Boolean(rule?.enabled!==false&&activeBy(rule,stateOf(runtime,rule.entityId||"")));}
let actionSeq=0; function callAction(action={},runtime={}){if(action.type==="navigate-section")return runtime.navigateToSection?.(action.sectionId); if(action.type==="navigate-view")return runtime.navigateToView?.(action.viewId); if(action.type==="toggle"){const [d]=String(action.entityId||"").split("."); return runtime.callService?.(d,"toggle",{entity_id:action.entityId});} if(action.type==="scene")return runtime.callService?.("scene","turn_on",{entity_id:action.entityId}); if(action.type==="script")return runtime.callService?.("script","turn_on",{entity_id:action.entityId}); if(action.type==="service")return runtime.callService?.(action.domain,action.service,{...(action.data||{}),...(action.target||{})}); return Promise.resolve();}
function actionButton(action={},runtime={},label="Run"){const id=`home-action-${++actionSeq}`, live=el("p",{text:"",attrs:{id:`${id}-live`,"aria-live":"polite"}}), b=el("button",{text:label,attrs:{type:"button",disabled:action.disabled?"":null,"aria-describedby":`${id}-live`,"aria-busy":"false"}}); b.dataset.actionId=id; b.addEventListener("click",async()=>{if(b.dataset.pending==="true"||action.disabled)return; if(action.confirm&&globalThis.confirm&&!globalThis.confirm(`Run ${label}?`))return; live.textContent=""; b.dataset.pending="true"; b.disabled=true; b.setAttribute("aria-busy","true"); try{await callAction(action,runtime); live.textContent=`${label} complete`; b.dataset.status="success";}catch(e){live.textContent=e?.message||`${label} failed`; b.dataset.status="error";}finally{b.dataset.pending="false"; b.disabled=Boolean(action.disabled); b.setAttribute("aria-busy","false");}}); const wrap=el("span",{className:"dm-action-wrap"}); wrap.append(b,live); return wrap;}
export function renderHomeHero(w,r={}){const c=w.config||{}, loc=r.locale||"en-US", now=new Date(), n=el("article",{className:`dm-widget dm-home-hero dm-${c.presentation||"expanded"}`}); n.append(el("h3",{text:c.title||w.title||"Home"})); if(c.subtitle)n.append(el("p",{text:c.subtitle})); const greeting=c.greetingText||({morning:"Good morning",evening:"Good evening"}[c.greetingMode]||""); if(greeting)n.append(el("p",{text:greeting})); if(c.showDate||c.showDateTime)n.append(el("time",{text:now.toLocaleDateString(loc)})); if(c.showTime||c.showDateTime)n.append(el("time",{text:now.toLocaleTimeString(loc)})); if(c.householdSummary)n.append(el("p",{text:c.householdSummary})); return n;}
export function renderWeatherSummary(w,r={}){const id=w.config?.entityId||"", fields=new Set(w.config?.displayedFields||["condition","temperature"]), e=stateOf(r,id), status=r.connectionStatus==="loading"?"loading":!id?"missing":unavailable(e)?"unavailable":"connected", n=el("article",{className:"dm-widget dm-weather-summary",attrs:{"data-status":status}}); n.append(el("h3",{text:w.title||"Weather"})); if(status!=="connected"){n.append(el("p",{text:status==="loading"?"Weather loading…":status==="missing"?"No weather entity configured.":"Weather unavailable."})); return n;} const a=e.attributes||{}, unit=a.temperature_unit||""; if(fields.has("condition"))n.append(el("p",{text:`Condition: ${e.state}`})); for(const [key,label] of [["temperature","Temperature"],["apparent_temperature","Feels like"],["humidity","Humidity"]]) if(fields.has(key)&&num(a[key])!==null)n.append(el("p",{text:`${label}: ${Number(a[key]).toLocaleString(r.locale||"en-US")}${key==="humidity"?"%":unit}`})); if(fields.has("forecast")&&Array.isArray(a.forecast)){const list=el("ul"); for(const f of a.forecast.slice(0,5))list.append(el("li",{text:`${f.datetime||f.date||"Forecast"}: ${f.condition||""} ${num(f.temperature)!==null?`${f.temperature}${unit}`:""}`.trim()})); n.append(list);} return n;}
export function aggregateHomeStatus(config={},r={}){const out={}; for(const m of config.metrics||[]){if(m.hidden)continue; const rules=m.rules||[{operator:m.operator||"on",expected:m.expected}]; const states=(m.entityIds||[]).map(id=>stateOf(r,id)); out[m.id]={title:m.title||m.id,count:states.filter(e=>rules.some(rule=>activeBy(rule,e))).length,unavailable:states.filter(unavailable).length};} return out;}
export function renderHomeStatus(w,r={}){const n=el("article",{className:"dm-widget dm-home-status"}); n.append(el("h3",{text:w.title||"Home status"})); const m=aggregateHomeStatus(w.config,r); for(const v of Object.values(m))n.append(el("p",{text:`${v.title}: ${v.count} active · ${v.unavailable} unavailable`})); if(!Object.keys(m).length)n.append(el("p",{text:"No status metrics configured."})); return n;}
export function renderAlerts(w,r={}){const n=el("article",{className:"dm-widget dm-alerts"}); n.append(el("h3",{text:w.title||"Alerts"})); const active=(w.config?.rules||[]).filter(rule=>evaluateAlertRule(rule,r)); for(const rule of active){const row=el("div",{attrs:{role:rule.severity==="critical"?"alert":"status","data-severity":rule.severity||"info"}}); row.append(el("span",{text:rule.icon||"!"}),el("strong",{text:rule.title||rule.id}),el("p",{text:rule.message||""})); if(rule.action)row.append(actionButton(rule.action,r,rule.action.title||"Run alert action")); if(rule.navigationTarget)row.append(actionButton({type:rule.navigationTarget.type||"navigate-section",sectionId:rule.navigationTarget.sectionId,viewId:rule.navigationTarget.viewId},r,"Open")); n.append(row);} if(!active.length)n.append(el("p",{text:"No active alerts."})); return n;}
function visible(a,r){if(a.visibility?.entityId)return activeBy(a.visibility,stateOf(r,a.visibility.entityId)); return a.visible!==false;}
export function renderQuickActions(w,r={}){const n=el("article",{className:"dm-widget dm-quick-actions"}); n.append(el("h3",{text:w.title||"Quick actions"})); for(const a of w.config?.actions||[]) if(visible(a,r)){const row=el("div",{className:"dm-quick-action-row"}); row.append(el("span",{text:a.icon||""}),actionButton(a,r,a.title||"Action")); if(a.badge)row.append(el("span",{text:a.badge,attrs:{"aria-label":`Badge ${a.badge}`}})); if(a.accent)row.dataset.accent=a.accent; n.append(row);} if(!(w.config?.actions||[]).length)n.append(el("p",{text:"No quick actions configured."})); return n;}
export function renderFavorites(w,r={}){const n=el("article",{className:"dm-widget dm-favorites"}); n.append(el("h3",{text:w.title||"Favorites"})); for(const f of w.config?.items||[]){const e=f.entityId?stateOf(r,f.entityId):null, missing=f.kind==="entity"&&!e; const row=el("div",{attrs:{"data-kind":f.kind||f.type||"entity","data-status":missing?"missing":unavailable(e)?"unavailable":"connected"}}); row.append(el("strong",{text:f.title||f.entityId||f.targetId||"Favorite"}),el("span",{text:e?.state||f.targetId||f.kind||"shortcut"})); if(f.primaryAction)row.append(actionButton(f.primaryAction,r,f.primaryAction.title||"Open favorite")); n.append(row);} if(!(w.config?.items||[]).length)n.append(el("p",{text:"No favorites configured."})); return n;}
export function renderLightsSummary(w,r={}){const s=summarizeLights(r,w.config?.entityIds||[]); const n=el("article",{className:"dm-widget dm-lights-summary"}); n.append(el("h3",{text:w.title||"Lights summary"}),el("p",{text:`${s.active} on · ${s.unavailable} unavailable · ${s.total} configured`})); if(w.config?.navigationTarget)n.append(actionButton({type:"navigate-section",sectionId:w.config.navigationTarget},r,"Open Lights")); if(w.config?.quickToggle)n.append(actionButton({type:"service",domain:"light",service:s.active?"turn_off":"turn_on",target:{entity_id:w.config.entityIds||[]},confirm:w.config.confirm},r,s.active?"Turn lights off":"Turn lights on")); return n;}
export function homeSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-home-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Home"})); n.append(renderWidgetLayout(section.config?.widgets||[],context,context.widgetRegistry)); return n;}
const widgets=[["home-hero","Home hero",renderHomeHero,()=>({title:"Home",subtitle:"",greetingText:"",showDate:true,showTime:false})],["weather-summary","Weather summary",renderWeatherSummary,()=>({entityId:"",displayedFields:["condition","temperature"]})],["home-status","Home status",renderHomeStatus,()=>({metrics:[]})],["alerts-summary","Alerts summary",renderAlerts,()=>({rules:[]})],["quick-actions","Quick actions",renderQuickActions,()=>({actions:[]})],["favorites","Favorites",renderFavorites,()=>({items:[]})],["lights-summary","Lights summary",renderLightsSummary,()=>({entityIds:[],quickToggle:false})]];
export const HOME_MODULE={id:"home",schemaVersion:1,sections:[{type:"home",displayName:"Home",renderer:homeSectionRenderer}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"home-editor",title:"Home editor"}],navigationEntries:[{sectionType:"home",icon:"home",title:"Home"}],actions:["navigate.view","navigate.section","service.call","entity.toggle","scene.turn_on","script.turn_on"],defaultLayouts:[{sectionType:"home",widgets:widgets.map(w=>w[0])}]};
