import { DEFAULT_PLUGIN_MANAGER } from "../plugins/registry.js";
import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { summarizeLights } from "./lights.js";
const ENTITY_RE=/^[a-z0-9_]+\.[a-z0-9_]+$/; const OPS=new Set(["equals","not-equals","numeric-above","numeric-below","unavailable","on","off"]);
const stateOf=(r,id)=>ENTITY_RE.test(id)?r.getEntityState?.(id):null; const unavailable=(e)=>!e||["unavailable","unknown"].includes(e.state);
export function evaluateAlertRule(rule,runtime={}){if(!rule?.enabled)return false; const e=stateOf(runtime,rule.entityId||""); const op=OPS.has(rule.operator)?rule.operator:"equals"; const s=e?.state; if(op==="unavailable")return unavailable(e); if(!e)return false; if(op==="on")return s==="on"; if(op==="off")return s==="off"; if(op==="equals")return s===String(rule.expected); if(op==="not-equals")return s!==String(rule.expected); const n=Number(s), ex=Number(rule.expected); if(!Number.isFinite(n)||!Number.isFinite(ex))return false; return op==="numeric-above"?n>ex:n<ex;}
function actionButton(action={},runtime={},label="Run"){const b=el("button",{text:label,attrs:{type:"button",disabled:action.disabled?"":null}}); b.addEventListener("click",async()=>{if(b.dataset.pending==="true")return; if(action.confirm&&globalThis.confirm&&!globalThis.confirm(`Run ${label}?`))return; b.dataset.pending="true"; try{ if(action.type==="navigate-section") runtime.navigateToSection?.(action.sectionId); else if(action.type==="navigate-view") runtime.navigateToView?.(action.viewId); else if(action.type==="toggle") { const [domain]=String(action.entityId||"").split("."); await runtime.callService?.(domain,"toggle",{entity_id:action.entityId}); } else if(action.type==="scene") await runtime.callService?.("scene","turn_on",{entity_id:action.entityId}); else if(action.type==="script") await runtime.callService?.("script","turn_on",{entity_id:action.entityId}); else if(action.type==="service") await runtime.callService?.(action.domain,action.service,{...(action.data||{}),...(action.target||{})}); b.dataset.status="success";}catch{b.dataset.status="error"; b.textContent=`${label} failed`;}finally{b.dataset.pending="false";}}); return b;}
export function renderHomeHero(w){const c=w.config||{}; const n=el("article",{className:`dm-widget dm-home-hero dm-${c.presentation||"expanded"}`}); n.append(el("h3",{text:c.title||w.title||"Home"})); if(c.subtitle)n.append(el("p",{text:c.subtitle})); if(c.showGreeting)n.append(el("p",{text:"Welcome home"})); if(c.showDateTime)n.append(el("time",{text:new Date().toLocaleString()})); if(c.householdSummary)n.append(el("p",{text:c.householdSummary})); return n;}
export function renderWeatherSummary(w,r={}){const id=w.config?.entityId||""; const e=stateOf(r,id); const n=el("article",{className:"dm-widget dm-weather-summary",attrs:{"data-status":!id?"missing":unavailable(e)?"unavailable":"connected"}}); n.append(el("h3",{text:w.title||"Weather"})); if(!id){n.append(el("p",{text:"No weather entity configured."})); return n;} if(unavailable(e)){n.append(el("p",{text:"Weather unavailable."})); return n;} const a=e.attributes||{}; n.append(el("p",{text:`${e.state} · ${a.temperature??"—"}${a.temperature_unit||""}`})); if(a.apparent_temperature!==undefined)n.append(el("p",{text:`Feels like ${a.apparent_temperature}`})); if(a.humidity!==undefined)n.append(el("p",{text:`Humidity ${a.humidity}%`})); if(Array.isArray(a.forecast))n.append(el("p",{text:`Forecast entries ${a.forecast.length}`})); return n;}
export function aggregateHomeStatus(config={},r={}){const out={}; for(const m of config.metrics||[]){ if(m.hidden)continue; const ids=m.entityIds||[]; const states=ids.map(id=>stateOf(r,id)); out[m.id]={title:m.title||m.id,count:states.filter(e=>e&&!unavailable(e)&&e.state!==(m.inactiveState||"off")).length,unavailable:states.filter(unavailable).length}; } return out;}
export function renderHomeStatus(w,r={}){const n=el("article",{className:"dm-widget dm-home-status"}); n.append(el("h3",{text:w.title||"Home status"})); const m=aggregateHomeStatus(w.config,r); for(const v of Object.values(m))n.append(el("p",{text:`${v.title}: ${v.count} active · ${v.unavailable} unavailable`})); if(!Object.keys(m).length)n.append(el("p",{text:"No status metrics configured."})); return n;}
export function renderAlerts(w,r={}){const n=el("article",{className:"dm-widget dm-alerts"}); n.append(el("h3",{text:w.title||"Alerts"})); const active=(w.config?.rules||[]).filter(rule=>evaluateAlertRule(rule,r)); for(const rule of active)n.append(el("p",{text:`${rule.severity||"info"}: ${rule.title} ${rule.message||""}`,attrs:{role:rule.severity==="critical"?"alert":"status"}})); if(!active.length)n.append(el("p",{text:"No active alerts."})); return n;}
export function renderQuickActions(w,r={}){const n=el("article",{className:"dm-widget dm-quick-actions"}); n.append(el("h3",{text:w.title||"Quick actions"})); for(const a of w.config?.actions||[]) if(a.visible!==false)n.append(actionButton(a,r,a.title||"Action")); if(!(w.config?.actions||[]).length)n.append(el("p",{text:"No quick actions configured."})); return n;}
export function renderFavorites(w,r={}){const n=el("article",{className:"dm-widget dm-favorites"}); n.append(el("h3",{text:w.title||"Favorites"})); for(const f of w.config?.items||[]){const e=f.entityId?stateOf(r,f.entityId):null; n.append(el("p",{text:`${f.title||f.entityId||f.targetId}: ${e?.state||f.kind||"shortcut"}`})); if(f.action)n.append(actionButton(f.action,r,`Open ${f.title||"favorite"}`));} if(!(w.config?.items||[]).length)n.append(el("p",{text:"No favorites configured."})); return n;}
export function renderLightsSummary(w,r={}){const s=summarizeLights(r,w.config?.entityIds||[]); const n=el("article",{className:"dm-widget dm-lights-summary"}); n.append(el("h3",{text:w.title||"Lights summary"}),el("p",{text:`${s.active} on · ${s.unavailable} unavailable · ${s.total} configured`})); if(w.config?.quickToggle)n.append(actionButton({type:"service",domain:"light",service:s.active?"turn_off":"turn_on",target:{entity_id:w.config.entityIds||[]},confirm:w.config.confirm},r,s.active?"Turn lights off":"Turn lights on")); return n;}
export function homeSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-home-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Home"})); n.append(renderWidgetLayout(section.config?.widgets||[],context,context.widgetRegistry)); return n;}
const widgets=[ ["home-hero","Home hero",renderHomeHero,()=>({title:"Home",subtitle:"",showGreeting:true,showDateTime:false})], ["weather-summary","Weather summary",renderWeatherSummary,()=>({entityId:"",displayedFields:["condition","temperature"]})], ["home-status","Home status",renderHomeStatus,()=>({metrics:[]})], ["alerts-summary","Alerts summary",renderAlerts,()=>({rules:[]})], ["quick-actions","Quick actions",renderQuickActions,()=>({actions:[]})], ["favorites","Favorites",renderFavorites,()=>({items:[]})], ["lights-summary","Lights summary",renderLightsSummary,()=>({entityIds:[],quickToggle:false})] ];
export const HOME_MODULE={id:"home",schemaVersion:1,sections:[{type:"home",displayName:"Home",renderer:homeSectionRenderer}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"home-editor",title:"Home editor"}],navigationEntries:[{sectionType:"home",icon:"home",title:"Home"}],actions:["navigate.view","navigate.section","service.call","entity.toggle","scene.turn_on","script.turn_on"],defaultLayouts:[{sectionType:"home",widgets:widgets.map(w=>w[0])}]};
export function registerHomeModule(manager=DEFAULT_PLUGIN_MANAGER){if(manager.listModules().some(m=>m.id==="home"))return HOME_MODULE; try{manager.registerModule(HOME_MODULE);}catch(error){if(!/already registered/.test(error.message))throw error;} return HOME_MODULE;}
registerHomeModule();
