import { DEFAULT_PLUGIN_MANAGER } from "../plugins/registry.js";
import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
export const LIGHT_WIDGETS = ["light-tile", "light-group", "lights-overview", "light-control-panel"];
const ENTITY_RE = /^[a-z0-9_]+\.[a-z0-9_]+$/; const clamp=(n,min,max)=>Math.min(max,Math.max(min,n)); const num=(v)=>Number.isFinite(Number(v))?Number(v):null;
export function lightCapabilities(entity){const a=entity?.attributes&&typeof entity.attributes==="object"?entity.attributes:{}; const modes=Array.isArray(a.supported_color_modes)?a.supported_color_modes:[]; return {onOff:true,brightness:modes.includes("brightness")||modes.some((m)=>["color_temp","hs","xy","rgb","rgbw","rgbww"].includes(m))||num(a.brightness)!==null,colorTemp:modes.includes("color_temp"),rgb:modes.includes("rgb"),rgbw:modes.includes("rgbw"),rgbww:modes.includes("rgbww"),hs:modes.includes("hs"),xy:modes.includes("xy"),effects:Array.isArray(a.effect_list)&&a.effect_list.length>0,transition:a.supported_features?Boolean(Number(a.supported_features)&32):false};}
export function normalizeLight(runtime={},entityId=""){const entity=ENTITY_RE.test(entityId)?runtime.getEntityState?.(entityId):null; if(!entity)return{entityId,status:"missing",name:entityId||"Unconfigured light",on:false,unavailable:true,capabilities:lightCapabilities(null),attributes:{}}; const malformed=!entity.attributes||typeof entity.attributes!=="object"||typeof entity.state!=="string"; const unavailable=malformed||["unavailable","unknown"].includes(entity.state); const b=num(entity.attributes?.brightness); return{entityId,status:malformed?"malformed":unavailable?"unavailable":"connected",name:entity.attributes?.friendly_name||entityId,on:entity.state==="on",unavailable,brightnessPct:b===null?null:clamp(Math.round((b/255)*100),0,100),color:entity.attributes?.rgb_color||entity.attributes?.rgbw_color||entity.attributes?.rgbww_color||null,capabilities:lightCapabilities(entity),attributes:entity.attributes||{}};}
export function summarizeLights(runtime,entityIds=[]){const lights=entityIds.map((id)=>normalizeLight(runtime,id)); return{lights,total:lights.length,active:lights.filter((l)=>l.on).length,unavailable:lights.filter((l)=>l.unavailable).length};}
async function callLight(runtime,service,entityId,data={}){if(typeof runtime.callService!=="function")throw new Error("No action runtime available."); return runtime.callService("light",service,{entity_id:entityId,...data});}
function button(label,disabled,fn){const b=el("button",{text:label,attrs:{type:"button",disabled:disabled?"":null,"aria-label":label}}); if(!disabled)b.addEventListener("click",async()=>{if(b.dataset.pending==="true")return; b.dataset.pending="true"; try{await fn(); b.dataset.status="success";}catch{b.dataset.status="error"; b.textContent=`${label} failed`;}finally{b.dataset.pending="false";}}); return b;}
export function renderLightTile(widget,runtime={}){const l=normalizeLight(runtime,widget.config?.entityId||""); const n=el("article",{className:"dm-widget dm-light-tile",attrs:{"data-status":l.status}}); n.append(el("h3",{text:widget.title||l.name}),el("p",{text:`${l.name}: ${l.unavailable?l.status:(l.on?"on":"off")}${l.brightnessPct!==null?` · ${l.brightnessPct}%`:""}`})); if(l.color)n.append(el("span",{text:`Color ${l.color.slice(0,3).join(",")}`})); n.append(button(l.on?"Turn off":"Turn on",l.unavailable,()=>callLight(runtime,l.on?"turn_off":"turn_on",l.entityId))); return n;}
export function renderLightGroup(widget,runtime={}){const s=summarizeLights(runtime,widget.config?.entityIds||[]); const n=el("article",{className:"dm-widget dm-light-group"}); n.append(el("h3",{text:widget.title||"Light group"}),el("p",{text:`${s.active} on · ${s.unavailable} unavailable · ${s.total} total`})); n.append(button("Toggle group",!s.total,()=>Promise.all(s.lights.filter(l=>!l.unavailable).map(l=>callLight(runtime,s.active?"turn_off":"turn_on",l.entityId))))); return n;}
export function renderLightsOverview(widget,runtime={}){const s=summarizeLights(runtime,widget.config?.entityIds||[]); const n=el("article",{className:"dm-widget dm-lights-overview"}); n.append(el("h3",{text:widget.title||"Lights"}),el("p",{text:`${s.active} active · ${s.unavailable} unavailable · ${s.total} configured`})); const list=el("div",{className:"dm-light-list"}); for(const id of widget.config?.entityIds||[])list.append(renderLightTile({id:`${widget.id}-${id}`,type:"light-tile",config:{entityId:id}},runtime)); n.append(list,button("Turn all off",!s.active,async()=>{if(widget.config?.confirmAllOff&&globalThis.confirm&&!globalThis.confirm("Turn all configured lights off?"))return; await Promise.all(s.lights.filter(l=>l.on&&!l.unavailable).map(l=>callLight(runtime,"turn_off",l.entityId)));})); return n;}
export function renderLightPanel(widget,runtime={}){const l=normalizeLight(runtime,widget.config?.entityId||""); const n=el("article",{className:"dm-widget dm-light-panel",attrs:{role:"dialog","aria-label":`Light detail ${l.name}`,tabindex:"-1"}}); n.append(el("h3",{text:`Light detail: ${l.name}`}),button(l.on?"Turn off":"Turn on",l.unavailable,()=>callLight(runtime,l.on?"turn_off":"turn_on",l.entityId))); if(l.capabilities.brightness)n.append(el("label",{text:"Brightness"}),el("input",{attrs:{type:"range",min:"0",max:"100",value:String(l.brightnessPct??0),"aria-label":"Brightness"}})); if(l.capabilities.colorTemp)n.append(el("label",{text:"Color temperature"}),el("input",{attrs:{type:"range",min:"153",max:"500",value:String(clamp(num(l.attributes.color_temp)||250,153,500)),"aria-label":"Color temperature"}})); if(l.capabilities.effects){const s=el("select",{attrs:{"aria-label":"Effect"}}); for(const e of l.attributes.effect_list)s.append(el("option",{text:e,attrs:{value:e}})); n.append(s);} n.addEventListener("keydown",e=>{if(e.key==="Escape")n.hidden=true;}); return n;}
export function lightsSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-lights-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Lights"})); n.append(renderWidgetLayout(section.config?.widgets||[{id:`${section.id}-overview`,type:"lights-overview",config:section.config||{},layout:{size:"full"}}],context,context.widgetRegistry)); return n;}
const validator=(c)=>c?.entityId&&!ENTITY_RE.test(c.entityId)?[{field:"entityId",message:"Invalid entity ID."}]:[];
export const LIGHTS_MODULE={id:"lights",schemaVersion:1,sections:[{type:"lights",displayName:"Lights",renderer:lightsSectionRenderer}],widgets:[{type:"light-tile",displayName:"Light tile",renderer:renderLightTile,validator,defaultConfig:()=>({entityId:""}),schemaVersion:1,supportedLayoutSizes:["small","medium"]},{type:"light-group",displayName:"Light group",renderer:renderLightGroup,defaultConfig:()=>({entityIds:[]}),schemaVersion:1,supportedLayoutSizes:["medium","large"]},{type:"lights-overview",displayName:"Lights overview",renderer:renderLightsOverview,defaultConfig:()=>({entityIds:[],confirmAllOff:true}),schemaVersion:1,supportedLayoutSizes:["large","full"]},{type:"light-control-panel",displayName:"Light detail panel",renderer:renderLightPanel,validator,defaultConfig:()=>({entityId:""}),schemaVersion:1,supportedLayoutSizes:["medium","large"]}],editorPanels:[{id:"lights-editor",title:"Lights editor"}],navigationEntries:[{sectionType:"lights",icon:"light",title:"Lights"}],actions:["light.toggle","light.turn_on","light.turn_off","scene.turn_on"],detailPanels:[{type:"light-control-panel"}],defaultLayouts:[{sectionType:"lights",widgets:["lights-overview"]}]};
export function registerLightsModule(manager=DEFAULT_PLUGIN_MANAGER){if(manager.listModules().some(m=>m.id==="lights"))return LIGHTS_MODULE; try{manager.registerModule(LIGHTS_MODULE);}catch(error){if(!/already registered/.test(error.message))throw error;} return LIGHTS_MODULE;}
registerLightsModule();
