import { el, emptyState } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { createActionState } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";

export const SECURITY_WIDGETS=["lock-tile","locks-overview","lock-control-panel","alarm-status","alarm-control-panel","binary-sensor-tile","security-sensors-overview","presence-tile","presence-overview","people-overview","access-overview","security-overview","security-control-panel"];
const ENTITY_RE=/^[a-z0-9_]+\.[a-z0-9_]+$/; const BAD=new Set(["unavailable","unknown"]);
const LOCK=new Set(["locked","unlocked","locking","unlocking","jammed","open","closed","unavailable","unknown"]), ALARM=new Set(["disarmed","armed_home","armed_away","armed_night","armed_vacation","arming","disarming","pending","triggered","unavailable","unknown"]), BIN={on:"active",off:"inactive",open:"open",closed:"closed",detected:"detected",clear:"clear",occupied:"occupied",unoccupied:"unoccupied",active:"active",inactive:"inactive",unavailable:"unavailable",unknown:"unknown"}, PRES={home:"home",away:"away",not_home:"away",present:"present",absent:"absent",stationary:"stationary",moving:"moving",unavailable:"unavailable",unknown:"unknown"};
const fields={primary:"entityId",state:"stateEntityId",availability:"availabilityEntityId",battery:"batteryEntityId",tamper:"tamperEntityId",jammed:"jammedEntityId",openClosed:"openClosedEntityId",lockedUnlocked:"lockedUnlockedEntityId",alarm:"alarmEntityId",alarmState:"alarmStateEntityId",alarmChangedAt:"alarmChangedAtEntityId",lastChanged:"lastChangedEntityId",lastSeen:"lastSeenEntityId",person:"personEntityId",tracker:"deviceTrackerEntityId",presence:"presenceStateEntityId",homeAway:"homeAwayEntityId",zone:"zoneEntityId",latitude:"latitudeEntityId",longitude:"longitudeEntityId",location:"locationEntityId",proximity:"proximityEntityId",source:"sourceEntityId"};
const now=()=>Date.now(); const ent=(r,id)=>id&&ENTITY_RE.test(id)?r.getEntityState?.(id)||r.hass?.states?.[id]||null:null; const raw=(e)=>e?.state; const title=(cfg,e)=>cfg.title||e?.attributes?.friendly_name||cfg.entityId||"Security item";
export function source(runtime,cfg={},key,{required=false,normalizer=(v)=>v,unit="",attr=null}={}){const attrMap=cfg.attributeMappings||{}, explicitId=cfg[fields[key]]||(required?cfg.entityId:""), id=explicitId, attrName=attr||attrMap[key]||(cfg.allowPrimaryAttributes===true&&explicitId?key:null); const configured=Boolean(explicitId||attrName), optional=!required; let sourceType="entity", e=id?ent(runtime,id):null, rv;
 if(!configured)return {configured:false,available:false,missing:false,unavailable:false,malformed:false,stale:false,reason:"not configured",rawValue:null,normalizedValue:null,sourceUnit:null,normalizedUnit:unit,lastUpdated:null,displayValue:"",entityId:id||"",sourceType,optional,excluded:false};
 if(attrName){sourceType="attribute"; e=ent(runtime,id||cfg.entityId); rv=e?.attributes?.[attrName];} else rv=raw(e);
 let state=!e?"missing":BAD.has(e.state)?"unavailable":rv===undefined||rv===null||rv===""?"missing":"available"; let nv=state==="available"?normalizer(rv):null; if(nv===null&&state==="available")state="malformed"; const ts=e?.last_updated||e?.last_changed||null, t=ts?Date.parse(ts):NaN; if(state==="available"&&Number.isFinite(t)&&!required){ if(cfg.futureToleranceMs>=0&&t>now()+cfg.futureToleranceMs)state="malformed"; else if(cfg.staleAfterMs>0&&now()-t>cfg.staleAfterMs)state="stale"; }
 return {configured,available:state==="available",missing:state==="missing",unavailable:state==="unavailable",malformed:state==="malformed",stale:state==="stale",reason:state,rawValue:rv??null,normalizedValue:nv,sourceUnit:e?.attributes?.unit_of_measurement||null,normalizedUnit:unit,lastUpdated:ts,displayValue:nv===null?state:String(unit?`${nv}${unit}`:nv),entityId:id||cfg.entityId||"",sourceType,attributeName:attrName||undefined,optional,excluded:cfg.enabled===false};}
const normSet=(set)=>(v)=>set.has(String(v))?String(v):String(v||"unknown"); const pct=(v)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):null}; const ts=(v)=>Number.isFinite(Date.parse(v))?new Date(v).toISOString():null; const text=(v)=>String(v??"").trim()||null; const coord=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null};
export function normalizeSecurityItem(runtime={},cfg={},kind="sensor"){const s={primary:source(runtime,cfg,"primary",{required:true,normalizer:text}),state:source(runtime,cfg,"state",{required:true,normalizer:kind==="lock"?normSet(LOCK):kind==="alarm"?normSet(ALARM):kind==="presence"?v=>PRES[String(v)]||String(v):v=>BIN[String(v)]||String(v)}),availability:source(runtime,cfg,"availability",{normalizer:v=>!BAD.has(String(v))}),battery:source(runtime,cfg,"battery",{normalizer:pct,unit:"%"}),tamper:source(runtime,cfg,"tamper",{normalizer:text}),jammed:source(runtime,cfg,"jammed",{normalizer:text}),lastChanged:source(runtime,cfg,"lastChanged",{normalizer:ts}),lastSeen:source(runtime,cfg,"lastSeen",{normalizer:ts}),zone:source(runtime,cfg,"zone",{normalizer:v=>cfg.zoneNameMapping?.[v]||String(v)}),proximity:source(runtime,cfg,"proximity",{normalizer:coord}),latitude:source(runtime,cfg,"latitude",{normalizer:coord}),longitude:source(runtime,cfg,"longitude",{normalizer:coord}),location:source(runtime,cfg,"location",{normalizer:text}),source:source(runtime,cfg,"source",{normalizer:text})}; if(!cfg.stateEntityId&&cfg.entityId)s.state=source(runtime,{...cfg,stateEntityId:cfg.entityId},"state",{required:true,normalizer:kind==="lock"?normSet(LOCK):kind==="alarm"?normSet(ALARM):kind==="presence"?v=>PRES[String(v)]||String(v):v=>BIN[String(v)]||String(v)});
 const arr=Object.values(s), configured=arr.filter(x=>x.configured&&!x.excluded), available=configured.filter(x=>x.available), required=[s.primary,s.state]; const operational=required.every(x=>x.available||(!x.configured&&x.optional)); const health=operational&&configured.every(x=>x.available||x.missing&&x.optional) ? "healthy" : operational ? "degraded" : "down"; return {id:cfg.id||cfg.entityId,title:title(cfg,ent(runtime,cfg.entityId)),kind,sources:s,state:s.state.normalizedValue,primaryAvailable:s.primary.available,stateAvailable:s.state.available,operational,health,complete:configured.every(x=>x.available),partial:operational&&!configured.every(x=>x.available),configuredCount:configured.length,availableCount:available.length,excludedCount:arr.filter(x=>x.excluded).length,optionalConfiguredCount:configured.filter(x=>x.optional).length,room:cfg.room||cfg.area||"",tags:cfg.tags||[],displayFields:cfg.displayFields||[]};}
export const normalizeLockState=(v)=>normSet(LOCK)(v); export const normalizeAlarmState=(v)=>normSet(ALARM)(v); export const normalizeBinarySensorState=(v)=>BIN[String(v)]||String(v||"unknown"); export const normalizePresenceState=(v)=>PRES[String(v)]||String(v||"unknown");
export function validateSecurityAction(a={},runtime={}){const e=[]; if(!["service","navigate-section","navigate-view"].includes(a.type))e.push("type"); if(a.type==="service"){if(!a.domain)e.push("domain"); if(!a.service)e.push("service"); if(a.entityId&&!ENTITY_RE.test(a.entityId))e.push("entityId"); if(typeof runtime.callService!=="function")e.push("runtime");} if(a.disabled)e.push("disabled"); return {valid:e.length===0,errors:e};}
function doAction(a,r){if(a.confirm&&globalThis.confirm&&!globalThis.confirm(a.confirm===true?"Confirm action?":String(a.confirm)))return Promise.resolve(false); if(a.type==="service")return r.callService(a.domain,a.service,{entity_id:a.entityId,...(a.target||{}),...(a.data||{})}); r.navigate?.(a); return Promise.resolve(true);} function actionButtons(n,actions=[],r){for(const a of actions.filter(x=>x&&x.visible!==false)){const v=validateSecurityAction(a,r), b=el("button",{text:a.title||a.service||a.type,attrs:{type:"button",disabled:!v.valid?"":null,"aria-label":a.title||a.type}}); b.dataset.structuralDisabled=String(!v.valid); const st=createActionState(b,n,()=>doAction(a,r),{prefix:"security-action"}); b.addEventListener("click",st.execute); n.append(b);} }
function tile(widget,runtime,kind){const item=normalizeSecurityItem(runtime,widget.config||{},kind), n=el("article",{className:`dm-widget dm-security-${kind}`,attrs:{"data-health":item.health}}); n.append(el("h3",{text:widget.title||item.title}),el("p",{text:`State: ${item.state||item.health}`}),el("p",{text:`Health: ${item.health} · operational ${item.operational}`})); if(item.room)n.append(el("p",{text:`Room: ${item.room}`})); if(item.sources.battery.configured)n.append(el("p",{text:`Battery: ${item.sources.battery.displayValue}`})); if(item.displayFields.includes("coordinates"))n.append(el("p",{text:`Coordinates: ${item.sources.latitude.displayValue}, ${item.sources.longitude.displayValue}`})); actionButtons(n,widget.config?.actions||[],runtime); const detail=el("button",{text:"Details",attrs:{type:"button","aria-label":`Details for ${item.title}`}}); detail.addEventListener("click",()=>openSecurityDetail(item,runtime,detail)); n.append(detail); return n;}
export const renderLockTile=(w,r)=>tile(w,r,"lock"); export const renderAlarmStatus=(w,r)=>tile(w,r,"alarm"); export const renderBinarySensorTile=(w,r)=>tile(w,r,"sensor"); export const renderPresenceTile=(w,r)=>tile(w,r,"presence");
export function filterSecurityItems(items=[],cfg={}){let out=[...items]; const q=String(cfg.search||"").toLowerCase(); out=out.filter(i=>(!q||i.title.toLowerCase().includes(q)||i.id?.includes(q))&&(!cfg.room||i.room===cfg.room)&&(!cfg.tag||i.tags.includes(cfg.tag))&&(!cfg.stateFilter||cfg.stateFilter==="all"||i.state===cfg.stateFilter)&&(!cfg.showUnavailable===false||i.operational)); if(cfg.activeOnly)out=out.filter(i=>["triggered","jammed","open","active","detected"].includes(i.state)); if(cfg.staleOnly)out=out.filter(i=>Object.values(i.sources).some(s=>s.stale)); if(cfg.lowBatteryOnly)out=out.filter(i=>(i.sources.battery.normalizedValue??101)<(cfg.lowBatteryThreshold??20)); out.sort((a,b)=>String(a[cfg.sort]||a.title).localeCompare(String(b[cfg.sort]||b.title))); return out;}
export function summarizeSecurity(items=[]){return {configured:items.length,operational:items.filter(i=>i.operational).length,locked:items.filter(i=>i.state==="locked").length,unlocked:items.filter(i=>i.state==="unlocked").length,transitioning:items.filter(i=>["locking","unlocking","arming","disarming","pending"].includes(i.state)).length,jammed:items.filter(i=>i.state==="jammed").length,active:items.filter(i=>["active","detected","open","triggered"].includes(i.state)).length,stale:items.filter(i=>Object.values(i.sources).some(s=>s.stale)).length,lowBattery:items.filter(i=>(i.sources.battery.normalizedValue??101)<20).length,unavailable:items.filter(i=>!i.operational).length,home:items.filter(i=>i.state==="home").length,away:items.filter(i=>i.state==="away").length,moving:items.filter(i=>i.state==="moving").length,stationary:items.filter(i=>i.state==="stationary").length,open:items.filter(i=>i.state==="open").length,alarmTriggered:items.filter(i=>i.state==="triggered").length};}
function overview(widget,runtime,kind,key="items"){const items=(widget.config?.[key]||[]).map(c=>normalizeSecurityItem(runtime,c,kind)); const filtered=filterSecurityItems(items,widget.config||{}), s=summarizeSecurity(items); const n=el("article",{className:`dm-widget dm-${widget.type}`}); n.append(el("h3",{text:widget.title||"Security"}),el("p",{text:`${s.operational} operational · ${s.unavailable} unavailable · ${s.configured} configured`})); if(!filtered.length)n.append(emptyState("No security items match the current filters.")); for(const it of filtered)n.append(tile({title:it.title,config:{...it,...(widget.config||{}),actions:it.actions||[]}},runtime,kind)); return n;}
export const renderLocksOverview=(w,r)=>overview(w,r,"lock","locks"); export const renderSecuritySensorsOverview=(w,r)=>overview(w,r,"sensor","sensors"); export const renderPresenceOverview=(w,r)=>overview(w,r,"presence","presence"); export const renderPeopleOverview=(w,r)=>overview(w,r,"presence","people"); export const renderAccessOverview=(w,r)=>overview(w,r,"sensor","access"); export const renderSecurityOverview=(w,r)=>overview(w,r,"sensor","items");
export function selectTracker(person={},runtime={}){const ids=person.trackerEntities||[]; if(person.trackerSelectionStrategy==="explicit")return person.deviceTrackerEntityId||ids[0]||""; if(person.trackerSelectionStrategy==="most-recently-updated")return ids.slice().sort((a,b)=>Date.parse(ent(runtime,b)?.last_updated||0)-Date.parse(ent(runtime,a)?.last_updated||0))[0]||""; if(person.trackerSelectionStrategy==="configured-priority-order")return ids.find(id=>ent(runtime,id))||ids[0]||""; return ids.find(id=>ent(runtime,id)&&!BAD.has(ent(runtime,id).state))||ids[0]||"";}
export function renderControlPanel(w,r){const n=tile(w,r,w.type.includes("alarm")?"alarm":w.type.includes("presence")?"presence":"lock"); n.append(el("p",{text:"Source diagnostics"})); return n;} export const renderLockPanel=renderControlPanel, renderAlarmPanel=renderControlPanel, renderSecurityPanel=renderControlPanel;
export function openSecurityDetail(item,runtime,trigger){return openSharedDetailPanel({trigger,label:`Security detail ${item.title}`,render:({close})=>{const n=el("article",{className:"dm-security-detail",attrs:{tabindex:"-1"}}); n.append(el("button",{text:"Close",attrs:{type:"button"}}),el("h3",{text:item.title}),el("p",{text:`Operational ${item.operational}; health ${item.health}; configured ${item.configuredCount}; available ${item.availableCount}`})); n.children[0].addEventListener("click",close); for(const [k,s] of Object.entries(item.sources)) if(s.configured)n.append(el("p",{text:`${k}: ${s.displayValue} (${s.sourceType}${s.attributeName?`.`+s.attributeName:""}) ${s.reason}`})); return n;}});}
export function securitySectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-security-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Security"}),renderWidgetLayout(section.config?.widgets||defaultSecuritySectionConfig().widgets,context,context.widgetRegistry)); return n;}
export function defaultSecuritySectionConfig(){return {schemaVersion:1,widgets:[{id:"security-overview",type:"security-overview",title:"Security overview",config:{items:[]},layout:{size:"full"}},{id:"presence-overview",type:"presence-overview",title:"Presence overview",config:{presence:[]},layout:{size:"full"}}]};}
const def=(type,name,renderer,key="items")=>({type,displayName:name,renderer,validator:()=>[],defaultConfig:()=>({schemaVersion:1,[key]:[],allowPrimaryAttributes:false,actions:[],displayFields:[],missingPolicy:"show",unavailablePolicy:"show",visibility:{}}),schemaVersion:1,supportedLayoutSizes:["medium","large","full"]});
export const SECURITY_MODULE={id:"security",schemaVersion:1,sections:[{type:"security",displayName:"Security",renderer:securitySectionRenderer,defaultConfig:defaultSecuritySectionConfig}],widgets:[def("lock-tile","Lock tile",renderLockTile),def("locks-overview","Locks overview",renderLocksOverview,"locks"),def("lock-control-panel","Lock control panel",renderLockPanel),def("alarm-status","Alarm status",renderAlarmStatus),def("alarm-control-panel","Alarm control panel",renderAlarmPanel),def("binary-sensor-tile","Binary sensor tile",renderBinarySensorTile),def("security-sensors-overview","Security sensors overview",renderSecuritySensorsOverview,"sensors"),def("presence-tile","Presence tile",renderPresenceTile),def("presence-overview","Presence overview",renderPresenceOverview,"presence"),def("people-overview","People overview",renderPeopleOverview,"people"),def("access-overview","Access overview",renderAccessOverview,"access"),def("security-overview","Security overview",renderSecurityOverview,"items"),def("security-control-panel","Security control panel",renderSecurityPanel)],editorPanels:[{id:"security-editor",title:"Security editor"}],navigationEntries:[{sectionType:"security",icon:"security",title:"Security"}],actions:[],detailPanels:[{type:"security-control-panel"}],defaultLayouts:[{sectionType:"security",widgets:["security-overview","presence-overview"]}]};
