import { el, emptyState } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { createActionState } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";

export const SECURITY_WIDGETS=["lock-tile","locks-overview","lock-control-panel","alarm-status","alarm-control-panel","binary-sensor-tile","security-sensors-overview","presence-tile","presence-overview","people-overview","access-overview","security-overview","security-control-panel"];
const ENTITY_RE=/^[a-z0-9_]+\.[a-z0-9_]+$/; const BAD=new Set(["unavailable","unknown"]);
const LOCK=new Set(["locked","unlocked","locking","unlocking","jammed","open","closed","unavailable","unknown"]), ALARM=new Set(["disarmed","armed_home","armed_away","armed_night","armed_vacation","arming","disarming","pending","triggered","unavailable","unknown"]), BIN={on:"active",off:"inactive",open:"open",closed:"closed",detected:"detected",clear:"clear",occupied:"occupied",unoccupied:"unoccupied",active:"active",inactive:"inactive",unavailable:"unavailable",unknown:"unknown"}, PRES={home:"home",away:"away",not_home:"away",present:"present",absent:"absent",stationary:"stationary",moving:"moving",unavailable:"unavailable",unknown:"unknown"};
const fields={primary:"entityId",state:"stateEntityId",availability:"availabilityEntityId",battery:"batteryEntityId",tamper:"tamperEntityId",jammed:"jammedEntityId",openClosed:"openClosedEntityId",lockedUnlocked:"lockedUnlockedEntityId",alarm:"alarmEntityId",alarmState:"alarmStateEntityId",alarmChangedAt:"alarmChangedAtEntityId",lastChanged:"lastChangedEntityId",lastSeen:"lastSeenEntityId",person:"personEntityId",tracker:"deviceTrackerEntityId",presence:"presenceStateEntityId",homeAway:"homeAwayEntityId",zone:"zoneEntityId",latitude:"latitudeEntityId",longitude:"longitudeEntityId",location:"locationEntityId",proximity:"proximityEntityId",source:"sourceEntityId"};
const now=()=>Date.now(); const ent=(r,id)=>id&&ENTITY_RE.test(id)&&typeof r.getEntityState==="function"?r.getEntityState(id)||null:null; const raw=(e)=>e?.state; const title=(cfg,e)=>cfg.title||e?.attributes?.friendly_name||cfg.entityId||"Security item";
export function source(runtime,cfg={},key,{required=false,normalizer=(v)=>v,unit="",attr=null}={}){const attrMap=cfg.attributeMappings||{}, explicitId=cfg[fields[key]]||(required?cfg.entityId:""), id=explicitId, attrName=attr||attrMap[key]||(cfg.allowPrimaryAttributes===true&&explicitId?key:null); const configured=Boolean(explicitId||attrName), optional=!required; let sourceType="entity", e=id?ent(runtime,id):null, rv;
 if(!configured)return {configured:false,available:false,missing:false,unavailable:false,malformed:false,stale:false,reason:"not configured",rawValue:null,normalizedValue:null,sourceUnit:null,normalizedUnit:unit,lastUpdated:null,displayValue:"",entityId:id||"",sourceType,optional,excluded:false};
 if(attrName){sourceType="attribute"; e=ent(runtime,id||cfg.entityId); rv=e?.attributes?.[attrName];} else rv=raw(e);
 let state=!e?"missing":BAD.has(e.state)?"unavailable":rv===undefined||rv===null||rv===""?"missing":"available"; let nv=state==="available"?normalizer(rv):null; if(nv===null&&state==="available")state="malformed"; const ts=e?.last_updated||e?.last_changed||null, t=ts?Date.parse(ts):NaN; if(state==="available"&&Number.isFinite(t)&&!required){ if(cfg.futureToleranceMs>=0&&t>now()+cfg.futureToleranceMs)state="malformed"; else if(cfg.staleAfterMs>0&&now()-t>cfg.staleAfterMs)state="stale"; }
 return {configured,available:state==="available",missing:state==="missing",unavailable:state==="unavailable",malformed:state==="malformed",stale:state==="stale",reason:state,rawValue:rv??null,normalizedValue:nv,sourceUnit:e?.attributes?.unit_of_measurement||null,normalizedUnit:unit,lastUpdated:ts,displayValue:nv===null?state:String(unit?`${nv}${unit}`:nv),entityId:id||cfg.entityId||"",sourceType,attributeName:attrName||undefined,optional,excluded:cfg.enabled===false};}
const normSet=(set)=>(v)=>set.has(String(v))?String(v):String(v||"unknown"); const pct=(v)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,Math.round(n))):null}; const ts=(v)=>Number.isFinite(Date.parse(v))?new Date(v).toISOString():null; const text=(v)=>String(v??"").trim()||null; const lat=(v)=>{const n=Number(v);return Number.isFinite(n)&&n>=-90&&n<=90?n:null}; const lon=(v)=>{const n=Number(v);return Number.isFinite(n)&&n>=-180&&n<=180?n:null}; const coord=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null};
export function normalizeSecurityItem(runtime={},cfg={},kind="sensor"){const s={primary:source(runtime,cfg,"primary",{required:true,normalizer:text}),state:source(runtime,cfg,"state",{required:true,normalizer:kind==="lock"?normSet(LOCK):kind==="alarm"?normSet(ALARM):kind==="presence"?v=>PRES[String(v)]||String(v):v=>BIN[String(v)]||String(v)}),availability:source(runtime,cfg,"availability",{normalizer:v=>!BAD.has(String(v))}),battery:source(runtime,cfg,"battery",{normalizer:pct,unit:"%"}),tamper:source(runtime,cfg,"tamper",{normalizer:text}),jammed:source(runtime,cfg,"jammed",{normalizer:text}),lastChanged:source(runtime,cfg,"lastChanged",{normalizer:ts}),lastSeen:source(runtime,cfg,"lastSeen",{normalizer:ts}),zone:source(runtime,cfg,"zone",{normalizer:v=>cfg.zoneNameMapping?.[v]||String(v)}),proximity:source(runtime,cfg,"proximity",{normalizer:coord}),latitude:source(runtime,cfg,"latitude",{normalizer:lat}),longitude:source(runtime,cfg,"longitude",{normalizer:lon}),location:source(runtime,cfg,"location",{normalizer:text}),source:source(runtime,cfg,"source",{normalizer:text})}; if(!cfg.stateEntityId&&cfg.entityId)s.state=source(runtime,{...cfg,stateEntityId:cfg.entityId},"state",{required:true,normalizer:kind==="lock"?normSet(LOCK):kind==="alarm"?normSet(ALARM):kind==="presence"?v=>PRES[String(v)]||String(v):v=>BIN[String(v)]||String(v)});
 const arr=Object.values(s), configured=arr.filter(x=>x.configured&&!x.excluded), available=configured.filter(x=>x.available), required=[s.primary,s.state]; const operational=required.every(x=>x.available||(!x.configured&&x.optional)); const bad=configured.filter(x=>!x.available&&!(x.missing&&x.optional)); const health=bad.some(x=>x.malformed)?"malformed":bad.some(x=>x.unavailable)?"unavailable":bad.some(x=>x.missing)?"missing":bad.some(x=>x.stale)?"stale":operational&&configured.some(x=>!x.available)?"degraded":operational?"available":"unavailable"; return {id:cfg.id||cfg.entityId,title:title(cfg,ent(runtime,cfg.entityId)),kind,sources:s,state:s.state.normalizedValue,primaryAvailable:s.primary.available,stateAvailable:s.state.available,operational,health,complete:configured.every(x=>x.available),partial:operational&&!configured.every(x=>x.available),configuredCount:configured.length,availableCount:available.length,excludedCount:arr.filter(x=>x.excluded).length,optionalConfiguredCount:configured.filter(x=>x.optional).length,room:cfg.room||cfg.area||"",tags:cfg.tags||[],displayFields:cfg.displayFields||[]};}
export const normalizeLockState=(v)=>normSet(LOCK)(v); export const normalizeAlarmState=(v)=>normSet(ALARM)(v); export const normalizeBinarySensorState=(v)=>BIN[String(v)]||String(v||"unknown"); export const normalizePresenceState=(v)=>PRES[String(v)]||String(v||"unknown");
const VIS_OPS=new Set(["equals","not-equals","on","off","home","unavailable","available"]);
export function visibilityAllows(a={},runtime={}){const v=a.visibility||{}; if(v.hidden===true)return false; if(!v.entityId)return true; const s=source(runtime,{entityId:v.entityId},"primary",{required:true,normalizer:text}); const op=VIS_OPS.has(v.operator)?v.operator:"equals", raw=String(s.normalizedValue??s.rawValue??""); if(op==="available")return s.available; if(op==="unavailable")return !s.available; if(op==="on")return /^(on|true|yes)$/i.test(raw); if(op==="off")return /^(off|false|no)$/i.test(raw); if(op==="home")return raw==="home"; return op==="not-equals"?raw!==String(v.expected??""):raw===String(v.expected??"");}
export function validateSecurityAction(a={},runtime={}){const e=[]; if(!["service","navigate-section","navigate-view"].includes(a.type))e.push("type"); if(a.type==="service"){if(!a.domain||typeof a.domain!=="string")e.push("domain"); if(!a.service||typeof a.service!=="string")e.push("service"); if(typeof runtime.callService!=="function")e.push("runtime");} if(a.type==="navigate-section"&&typeof runtime.navigateToSection!=="function")e.push("runtime"); if(a.type==="navigate-view"&&typeof runtime.navigateToView!=="function")e.push("runtime"); if(a.entityId&&!ENTITY_RE.test(a.entityId))e.push("entityId"); if(a.target!==undefined&&(typeof a.target!=="object"||Array.isArray(a.target)||a.target===null))e.push("target"); if(a.target?.entity_id&&!ENTITY_RE.test(a.target.entity_id))e.push("target.entity_id"); if(a.data!==undefined&&(typeof a.data!=="object"||Array.isArray(a.data)||a.data===null))e.push("data"); if(a.visibility!==undefined&&(typeof a.visibility!=="object"||Array.isArray(a.visibility)||a.visibility===null||(a.visibility.entityId&&!ENTITY_RE.test(a.visibility.entityId))||(a.visibility.operator&&!VIS_OPS.has(a.visibility.operator))))e.push("visibility"); if(a.disabled!==undefined&&typeof a.disabled!=="boolean")e.push("disabled"); if(a.confirm!==undefined&&typeof a.confirm!=="boolean")e.push("confirm"); return {valid:e.length===0,errors:e};}
function doAction(a,r){if(a.confirm&&globalThis.confirm&&!globalThis.confirm(`Run ${a.title||a.service||a.type}?`))return Promise.resolve(false); if(a.type==="navigate-section")return Promise.resolve(r.navigateToSection(a.sectionId)); if(a.type==="navigate-view")return Promise.resolve(r.navigateToView(a.viewId)); return r.callService(a.domain,a.service,{...(a.target||{}),entity_id:a.entityId||a.target?.entity_id,...(a.data||{})});} function actionButtons(n,actions=[],r){for(const a of actions.filter(x=>x&&x.visible!==false&&visibilityAllows(x,r))){const v=validateSecurityAction(a,r), b=el("button",{text:a.title||a.service||a.type,attrs:{type:"button",disabled:!v.valid?"":null,"aria-label":a.title||a.type}}); b.dataset.structuralDisabled=String(!v.valid); const st=createActionState(b,n,()=>doAction(a,r),{prefix:"security-action"}); b.addEventListener("click",st.execute); n.append(b);} }
export function renderNormalizedSecurityItem(item,runtime,actions=[]){const n=el("article",{className:`dm-widget dm-security-${item.kind}`,attrs:{"data-health":item.health}}); n.append(el("h3",{text:item.title}),el("p",{text:`State: ${item.state||item.health}`}),el("p",{text:`Health: ${item.health} · operational ${item.operational}`})); if(item.room)n.append(el("p",{text:`Room: ${item.room}`})); if(item.sources.battery.configured)n.append(el("p",{text:`Battery: ${item.sources.battery.displayValue}`})); if(item.displayFields.includes("coordinates")&&item.sources.latitude.available&&item.sources.longitude.available)n.append(el("p",{text:`Coordinates: ${item.sources.latitude.displayValue}, ${item.sources.longitude.displayValue}`})); actionButtons(n,actions||item.actions||[],runtime); const detail=el("button",{text:"Details",attrs:{type:"button","aria-label":`Details for ${item.title}`}}); detail.addEventListener("click",()=>openSecurityDetail(item,runtime,detail)); n.append(detail); return n;}
function tile(widget,runtime,kind){return renderNormalizedSecurityItem(normalizeSecurityItem(runtime,widget.config||{},kind),runtime,widget.config?.actions||[]);}
export const renderLockTile=(w,r)=>tile(w,r,"lock"); export const renderAlarmStatus=(w,r)=>tile(w,r,"alarm"); export const renderBinarySensorTile=(w,r)=>tile(w,r,"sensor"); export const renderPresenceTile=(w,r)=>tile(w,r,"presence");
export function filterSecurityItems(items=[],cfg={}){let out=[...items]; const q=String(cfg.search||"").toLowerCase(); out=out.filter(i=>(!q||i.title.toLowerCase().includes(q)||i.id?.includes(q))&&(!cfg.room||i.room===cfg.room)&&(!cfg.tag||i.tags.includes(cfg.tag))&&(!cfg.stateFilter||cfg.stateFilter==="all"||i.state===cfg.stateFilter)&&(cfg.showUnavailable===true||i.operational)); if(cfg.activeOnly)out=out.filter(i=>["triggered","jammed","open","active","detected"].includes(i.state)); if(cfg.staleOnly)out=out.filter(i=>Object.values(i.sources).some(s=>s.stale)); if(cfg.lowBatteryOnly)out=out.filter(i=>(i.sources?.battery?.normalizedValue??101)<(cfg.lowBatteryThreshold??20)); out.sort((a,b)=>String(a[cfg.sort]||a.title).localeCompare(String(b[cfg.sort]||b.title))); return out;}
export function summarizeSecurity(items=[]){return {configured:items.length,operational:items.filter(i=>i.operational).length,locked:items.filter(i=>i.state==="locked").length,unlocked:items.filter(i=>i.state==="unlocked").length,transitioning:items.filter(i=>["locking","unlocking","arming","disarming","pending"].includes(i.state)).length,jammed:items.filter(i=>i.state==="jammed").length,active:items.filter(i=>["active","detected","open","triggered"].includes(i.state)).length,stale:items.filter(i=>Object.values(i.sources).some(s=>s.stale)).length,lowBattery:items.filter(i=>(i.sources?.battery?.normalizedValue??101)<20).length,unavailable:items.filter(i=>!i.operational).length,home:items.filter(i=>i.state==="home").length,away:items.filter(i=>i.state==="away").length,moving:items.filter(i=>i.state==="moving").length,stationary:items.filter(i=>i.state==="stationary").length,open:items.filter(i=>i.state==="open").length,alarmTriggered:items.filter(i=>i.state==="triggered").length};}
function overview(widget,runtime,kind,key="items"){const items=(widget.config?.[key]||[]).map(c=>normalizeSecurityItem(runtime,c,kind)); const filtered=filterSecurityItems(items,widget.config||{}), s=summarizeSecurity(items); const n=el("article",{className:`dm-widget dm-${widget.type}`}); n.append(el("h3",{text:widget.title||"Security"}),el("p",{text:`${s.operational} operational · ${s.unavailable} unavailable · ${s.configured} configured`})); if(!filtered.length)n.append(emptyState("No security items match the current filters.")); for(const it of filtered)n.append(renderNormalizedSecurityItem(it,runtime,it.actions||[])); return n;}
export const renderLocksOverview=(w,r)=>overview(w,r,"lock","locks"); export const renderSecuritySensorsOverview=(w,r)=>overview(w,r,"sensor","sensors"); export const renderPresenceOverview=(w,r)=>overview(w,r,"presence","presence"); export const renderPeopleOverview=(w,r)=>overview(w,r,"presence","people"); export const renderAccessOverview=(w,r)=>overview(w,r,"sensor","access"); export const renderSecurityOverview=(w,r)=>overview(w,r,"sensor","items");
export function selectTracker(person={},runtime={}){const ids=person.trackerEntities||[]; if(person.trackerSelectionStrategy==="explicit")return person.deviceTrackerEntityId||ids[0]||""; if(person.trackerSelectionStrategy==="most-recently-updated")return ids.slice().sort((a,b)=>Date.parse(ent(runtime,b)?.last_updated||0)-Date.parse(ent(runtime,a)?.last_updated||0))[0]||""; if(person.trackerSelectionStrategy==="configured-priority-order"){const order=person.trackerPriorityOrder||ids;return order.find(id=>ids.includes(id)&&ent(runtime,id)&&!BAD.has(ent(runtime,id).state))||order.find(id=>ids.includes(id))||ids[0]||"";} return ids.find(id=>ent(runtime,id)&&!BAD.has(ent(runtime,id).state))||ids[0]||"";}
export function renderControlPanel(w,r){const n=tile(w,r,w.type.includes("alarm")?"alarm":w.type.includes("presence")?"presence":"lock"); n.append(el("p",{text:"Source diagnostics"})); return n;} export const renderLockPanel=renderControlPanel, renderAlarmPanel=renderControlPanel, renderSecurityPanel=renderControlPanel;
export function openSecurityDetail(item,runtime,trigger){return openSharedDetailPanel({trigger,label:`Security detail ${item.title}`,render:({close})=>{const n=el("article",{className:"dm-security-detail",attrs:{tabindex:"-1"}}); n.append(el("button",{text:"Close",attrs:{type:"button"}}),el("h3",{text:item.title}),el("p",{text:`Operational ${item.operational}; health ${item.health}; configured ${item.configuredCount}; available ${item.availableCount}`})); n.children[0].addEventListener("click",close); for(const [k,s] of Object.entries(item.sources)) if(s.configured)n.append(el("p",{text:`${k}: ${s.displayValue} (${s.sourceType}${s.attributeName?`.`+s.attributeName:""}) ${s.reason}`})); return n;}});}
export function securitySectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-security-section",attrs:{"data-section-id":section.id}}); n.append(el("h3",{text:section.title||"Security"}),renderWidgetLayout(section.config?.widgets||defaultSecuritySectionConfig(section.id).widgets,context,context.widgetRegistry)); return n;}
export function defaultSecuritySectionConfig(sectionId="security"){return {schemaVersion:1,widgets:[{id:`${sectionId}-security-overview`,type:"security-overview",title:"Security overview",config:{items:[]},layout:{size:"full"}},{id:`${sectionId}-presence-overview`,type:"presence-overview",title:"Presence overview",config:{presence:[]},layout:{size:"full"}}]};}
const def=(type,name,renderer,key="items")=>({type,displayName:name,renderer,validator:()=>[],defaultConfig:()=>({schemaVersion:1,[key]:[],allowPrimaryAttributes:false,actions:[],displayFields:[],missingPolicy:"show",unavailablePolicy:"show",visibility:{}}),schemaVersion:1,supportedLayoutSizes:["medium","large","full"]});
export const SECURITY_MODULE={id:"security",schemaVersion:1,sections:[{type:"security",displayName:"Security",renderer:securitySectionRenderer,defaultConfig:defaultSecuritySectionConfig}],widgets:[def("lock-tile","Lock tile",renderLockTile),def("locks-overview","Locks overview",renderLocksOverview,"locks"),def("lock-control-panel","Lock control panel",renderLockPanel),def("alarm-status","Alarm status",renderAlarmStatus),def("alarm-control-panel","Alarm control panel",renderAlarmPanel),def("binary-sensor-tile","Binary sensor tile",renderBinarySensorTile),def("security-sensors-overview","Security sensors overview",renderSecuritySensorsOverview,"sensors"),def("presence-tile","Presence tile",renderPresenceTile),def("presence-overview","Presence overview",renderPresenceOverview,"presence"),def("people-overview","People overview",renderPeopleOverview,"people"),def("access-overview","Access overview",renderAccessOverview,"access"),def("security-overview","Security overview",renderSecurityOverview,"items"),def("security-control-panel","Security control panel",renderSecurityPanel)],editorPanels:[{id:"security-editor",title:"Security editor"}],navigationEntries:[{sectionType:"security",icon:"security",title:"Security"}],actions:[],detailPanels:[{type:"security-control-panel"}],defaultLayouts:[{sectionType:"security",widgets:["security-overview","presence-overview"]}]};
