import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { actionButton } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";
import { ENTITY_RE, normalizeMeasurement } from "./shared-measurements.js";
const BAD=new Set(["unknown","unavailable",""]);const now=()=>Date.now();
const get=(r,id)=>ENTITY_RE.test(id||"")?r.getEntityState?.(id):null;
const UNIT={distance:{m:0.001,km:1,mi:1.609344},pressure:{Pa:0.001,kPa:1,bar:100,psi:6.8947572932},temperature:{C:[1,0],F:[5/9,-32*5/9],K:[1,-273.15]},current:{mA:0.001,A:1},voltage:{V:1,kV:1000},percent:{"%":1,percent:1},duration:{s:1,min:60,h:3600}};
export function convertVehicleUnit(value,from,to,kind){const v=Number(value);if(!Number.isFinite(v))return{available:false,malformed:true,reason:"malformed"};if(kind==="temperature"){if(!UNIT.temperature[from]||!UNIT.temperature[to])return{available:false,malformed:true,reason:"incompatible-unit"};const c=v*UNIT.temperature[from][0]+UNIT.temperature[from][1];return{available:true,value:(c-UNIT.temperature[to][1])/UNIT.temperature[to][0],unit:to,reason:"ok"};}const t=UNIT[kind];if(!t?.[from]||!t?.[to])return{available:false,malformed:true,reason:"incompatible-unit"};return{available:true,value:v*t[from]/t[to],unit:to,reason:"ok"};}
function timestampState(lastUpdated,staleAfterMs,nowMs,futureToleranceMs){if(!lastUpdated)return{stale:false,malformed:false,reason:"timestamp-missing"};const t=new Date(lastUpdated).getTime();if(!Number.isFinite(t))return{stale:false,malformed:true,reason:"timestamp-invalid"};if(t-nowMs>Number(futureToleranceMs??5000))return{stale:false,malformed:true,reason:"timestamp-future"};if(Number.isFinite(staleAfterMs)&&staleAfterMs>0&&nowMs-t>staleAfterMs)return{stale:true,malformed:false,reason:"timestamp-stale"};return{stale:false,malformed:false,reason:"ok"};}
function base(id,kind,unit){return{entityId:id||"",kind,available:false,missing:false,unavailable:false,malformed:false,stale:false,reason:"not-evaluated",rawValue:null,normalizedValue:null,sourceUnit:"",normalizedUnit:unit||"",lastUpdated:null,displayValue:"Unavailable"};}
export function normalizeVehicleSource(r,id,{kind="text",unit="",staleAfterMs,futureToleranceMs,nowMs=now()}={}){const b=base(id,kind,unit);if(!id)return{...b,missing:true,reason:"missing-entity-id"};if(!ENTITY_RE.test(id))return{...b,malformed:true,reason:"invalid-entity-id"};const e=get(r,id);if(!e)return{...b,missing:true,reason:"entity-missing"};const raw=e.state,sourceUnit=e.attributes?.unit_of_measurement||unit||"",lastUpdated=e.last_updated||e.lastUpdated||null;const ts=timestampState(lastUpdated,staleAfterMs,nowMs,futureToleranceMs);if(ts.malformed)return{...b,malformed:true,reason:ts.reason,rawValue:raw,sourceUnit,lastUpdated};if(BAD.has(String(raw??"").trim()))return{...b,unavailable:true,reason:String(raw||"empty"),rawValue:raw,sourceUnit,lastUpdated};if(kind==="power"||kind==="energy"||kind==="percent"){const m=normalizeMeasurement(r,id,{kind,unit:unit||sourceUnit,staleAfterMs,now:nowMs,futureToleranceMs});return{...b,...m,rawValue:raw,normalizedValue:m.normalizedValue,sourceUnit:m.sourceUnit,normalizedUnit:m.normalizedUnit,lastUpdated:m.lastUpdated,stale:m.stale,available:m.available,displayValue:m.displayValue};}
let val=raw,outUnit=unit||sourceUnit,malformed=false,reason=ts.stale?"timestamp-stale":"ok";if(["numeric","coordinates","consumption"].includes(kind)){val=Number(raw);malformed=!Number.isFinite(val);}else if(["distance","pressure","temperature","current","voltage","duration"].includes(kind)){const c=convertVehicleUnit(raw,sourceUnit,outUnit,kind);malformed=!c.available;reason=c.reason;val=c.value;}else if(kind==="timestamp"){const t=new Date(raw).getTime();malformed=!Number.isFinite(t);val=malformed?null:new Date(t).toISOString();outUnit="ISO8601";}else if(kind==="duration"){const c=convertVehicleUnit(raw,sourceUnit||"s",outUnit||"s","duration");malformed=!c.available;reason=c.reason;val=c.value;}else if(kind==="text"){val=String(raw);outUnit="";}if(malformed)return{...b,malformed:true,reason:reason||"malformed",rawValue:raw,sourceUnit,normalizedUnit:outUnit,lastUpdated};return{...b,available:!ts.stale,stale:ts.stale,reason,rawValue:raw,normalizedValue:val,sourceUnit,normalizedUnit:outUnit,lastUpdated,displayValue:outUnit&&typeof val==="number"?`${val.toFixed(1)} ${outUnit}`:String(val)};}
const mapKeys=["primaryEntityId","statusEntityId","socEntityId","rangeEntityId","odometerEntityId","chargingConnectedEntityId","chargingStateEntityId","chargingPowerEntityId","chargingEnergyEntityId","currentEntityId","voltageEntityId","chargeLimitEntityId","etaEntityId","latitudeEntityId","longitudeEntityId","locationEntityId","lastUpdateEntityId","tripDistanceEntityId","tripEnergyEntityId","averageConsumptionEntityId","cabinTemperatureEntityId","outsideTemperatureEntityId","climateStateEntityId","lockStateEntityId","trunkStateEntityId"];
export function collectVehicleSources(node,out=[]){if(!node)return out;if(Array.isArray(node)){node.forEach(x=>collectVehicleSources(x,out));return out;}if(typeof node==="object"&&"available"in node&&"reason"in node&&"rawValue"in node){out.push(node);return out;}if(typeof node==="object")Object.values(node).forEach(x=>collectVehicleSources(x,out));return out;}
export function aggregateVehicleSources(sources){const vals=collectVehicleSources(sources);return{available:vals.some(x=>x.available),missing:vals.some(x=>x.missing),unavailable:vals.some(x=>x.unavailable),malformed:vals.some(x=>x.malformed),stale:vals.some(x=>x.stale),reason:vals.find(x=>x.malformed||x.unavailable||x.missing||x.stale)?.reason||"ok",count:vals.length};}
export function normalizeVehicle(r={},c={}){const units={distance:c.distanceUnit||"km",pressure:c.pressureUnit||"psi",temperature:c.temperatureUnit||"C",current:c.currentUnit||"A",voltage:c.voltageUnit||"V",power:c.powerUnit||"kW",energy:c.energyUnit||"kWh",duration:c.durationUnit||"min",consumption:c.consumptionUnit||"kWh/100km"},o={staleAfterMs:c.staleAfterMs,futureToleranceMs:c.futureToleranceMs};const src=(id,kind="text",unit="")=>normalizeVehicleSource(r,id,{...o,kind,unit});const s={primary:src(c.primaryEntityId||c.entityId),status:src(c.statusEntityId||c.primaryEntityId||c.entityId),soc:src(c.socEntityId,"percent","%"),range:src(c.rangeEntityId,"distance",units.distance),odometer:src(c.odometerEntityId,"distance",units.distance),chargingConnected:src(c.chargingConnectedEntityId),chargingState:src(c.chargingStateEntityId),chargingPower:src(c.chargingPowerEntityId,"power",units.power),chargingEnergy:src(c.chargingEnergyEntityId,"energy",units.energy),current:src(c.currentEntityId,"current",units.current),voltage:src(c.voltageEntityId,"voltage",units.voltage),chargeLimit:src(c.chargeLimitEntityId,"percent","%"),eta:src(c.etaEntityId,c.etaKind||"duration",units.duration),latitude:src(c.latitudeEntityId,"coordinates"),longitude:src(c.longitudeEntityId,"coordinates"),location:src(c.locationEntityId),lastUpdate:src(c.lastUpdateEntityId,"timestamp"),tripDistance:src(c.tripDistanceEntityId,"distance",units.distance),tripEnergy:src(c.tripEnergyEntityId,"energy",units.energy),averageConsumption:src(c.averageConsumptionEntityId,"consumption",units.consumption),cabinTemperature:src(c.cabinTemperatureEntityId,"temperature",units.temperature),outsideTemperature:src(c.outsideTemperatureEntityId,"temperature",units.temperature),climateState:src(c.climateStateEntityId),lockState:src(c.lockStateEntityId),trunkState:src(c.trunkStateEntityId)};const rows=(xs=[],kind="text",unit)=>xs.map(x=>({id:x.id,title:x.title||x.id,source:src(x.entityId,kind,unit)}));s.doors=rows(c.doors);s.windows=rows(c.windows);s.tyrePressure=rows(c.tyrePressure,"pressure",units.pressure);s.tyreTemperature=rows(c.tyreTemperature,"temperature",units.temperature);s.customMetrics=(c.customMetrics||[]).map(m=>({id:m.id,title:m.title||m.id,source:src(m.entityId,m.kind||"text",m.unit)}));const agg=aggregateVehicleSources(s);return{id:c.id||c.primaryEntityId||c.entityId||"vehicle",title:c.title||s.primary.normalizedValue||"Vehicle",manufacturer:c.manufacturer||"",model:c.model||"",entityIds:Object.fromEntries(mapKeys.map(k=>[k,c[k]||""])),sources:s,...agg,actions:c.actions||[],tags:c.tags||[],lowBatteryThreshold:c.lowBatteryThreshold??20};}
export function validateVehicleAction(a={},r={}){const e=[];if(!["service","navigate-section","navigate-view"].includes(a.type))e.push({field:"type",message:"Action type must be explicit."});if(a.type==="service"&&(!a.domain||!a.service))e.push({field:"service",message:"Service action requires domain and service."});if(a.entityId&&!ENTITY_RE.test(a.entityId))e.push({field:"entity",message:"Invalid entity ID."});if(a.target?.entity_id&&!ENTITY_RE.test(a.target.entity_id))e.push({field:"target",message:"Invalid target entity ID."});if(a.visibility?.entityId&&!ENTITY_RE.test(a.visibility.entityId))e.push({field:"visibility",message:"Invalid visibility entity ID."});if(a.data&&typeof a.data!=="object")e.push({field:"data",message:"Action data must be an object."});if(a.disabled!==undefined&&typeof a.disabled!=="boolean")e.push({field:"disabled",message:"Disabled must be boolean."});if(a.confirm!==undefined&&typeof a.confirm!=="boolean")e.push({field:"confirm",message:"Confirmation must be boolean."});if(a.type==="service"&&typeof r.callService!=="function")e.push({field:"runtime",message:"Runtime cannot call services."});return e;}
function visible(a,r){return !a.visibility?.entityId||normalizeVehicleSource(r,a.visibility.entityId).normalizedValue===String(a.visibility.expected??"on");}async function runAction(a,r){if(a.confirm&&globalThis.confirm&&!globalThis.confirm(`Run ${a.title||a.service}?`))return;if(a.type==="navigate-section")return r.navigateToSection?.(a.sectionId);if(a.type==="navigate-view")return r.navigateToView?.(a.viewId);return r.callService?.(a.domain,a.service,{...(a.target||{}),entity_id:a.entityId||a.target?.entity_id,...(a.data||{})});}
const art=c=>el("article",{className:`dm-widget ${c}`});const line=(n,k,s)=>n.append(el("p",{text:`${k}: ${s.displayValue} (${s.reason})`}));const btns=(n,acts,r)=>acts.filter(a=>visible(a,r)).forEach(a=>n.append(actionButton(a.title||a.service||"Action",a.disabled||validateVehicleAction(a,r).length,()=>runAction(a,r),n,"vehicle-action")));
export function renderVehicleTile(w,r={}){const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-tile");n.append(el("h3",{text:w.title||v.title}),el("p",{text:`${v.sources.status.displayValue} · ${v.reason}`}));line(n,"SOC",v.sources.soc);line(n,"Range",v.sources.range);btns(n,v.actions,r);n.append(actionButton("Details",false,()=>openVehicleDetailPanel(w.config,r,n),n,"vehicle-action"));return n;}
export function renderVehicleStatus(w,r={}){const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-status");n.append(el("h3",{text:w.title||"Vehicle status"}));["status","lastUpdate"].forEach(k=>line(n,k,v.sources[k]));return n;}
export const renderVehicleBattery=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-battery");n.append(el("h3",{text:w.title||"Vehicle battery"}));["soc","chargingPower","chargingEnergy","current","voltage","chargeLimit"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleCharging=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-charging");n.append(el("h3",{text:w.title||"Vehicle charging"}));["chargingState","chargingPower","eta"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleRange=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-range");n.append(el("h3",{text:w.title||"Vehicle range"}));["range","odometer"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleTrip=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-trip");n.append(el("h3",{text:w.title||"Vehicle trip"}));["tripDistance","tripEnergy","averageConsumption"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleTyres=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-tyres");n.append(el("h3",{text:w.title||"Vehicle tyres"}));[...v.sources.tyrePressure,...v.sources.tyreTemperature].forEach(x=>line(n,x.title,x.source));return n;};
export const renderVehicleLocation=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-location");n.append(el("h3",{text:w.title||"Vehicle location"}));["latitude","longitude","location"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleClimate=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-climate");n.append(el("h3",{text:w.title||"Vehicle climate"}));["climateState","cabinTemperature","outsideTemperature"].forEach(k=>line(n,k,v.sources[k]));return n;};
export const renderVehicleSecurity=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-security");n.append(el("h3",{text:w.title||"Vehicle security"}));line(n,"lock",v.sources.lockState);[...v.sources.doors,...v.sources.windows,{title:"trunk",source:v.sources.trunkState}].forEach(x=>line(n,x.title,x.source));return n;};
export function filteredVehicles(w,r={}){const c=w.config||{},q=String(c.search||"").toLowerCase(),status=c.statusFilter||"all";let xs=(c.vehicles||[]).map(v=>normalizeVehicle(r,v));xs=xs.filter(v=>(!q||v.title.toLowerCase().includes(q))&&(status==="all"||v.sources.status.normalizedValue===status));xs.sort((a,b)=>c.sort==="soc"?(b.sources.soc.normalizedValue??-1)-(a.sources.soc.normalizedValue??-1):c.sort==="range"?(b.sources.range.normalizedValue??-1)-(a.sources.range.normalizedValue??-1):a.title.localeCompare(b.title));return xs;}
export function renderVehiclesOverview(w,r={}){let local={...(w.config||{})};const n=art("dm-vehicles-overview"),list=el("div"),summary=el("p"),search=el("input",{attrs:{type:"search","aria-label":"Search vehicles",value:local.search||""}}),filter=el("select",{attrs:{"aria-label":"Vehicle status filter"}}),sort=el("select",{attrs:{"aria-label":"Sort vehicles"}});for(const [sel,vals,cur]of[[filter,["all","home","away","charging"],local.statusFilter||"all"],[sort,["name","soc","range"],local.sort||"name"]])for(const v of vals){const o=el("option",{text:v,attrs:{value:v}});o.selected=v===cur;sel.append(o);}filter.value=local.statusFilter||"all";sort.value=local.sort||"name";function draw(){local.search=search.value;local.statusFilter=filter.value;local.sort=sort.value;const xs=filteredVehicles({config:local},r);list.replaceChildren();summary.textContent=`${xs.length} shown · ${(local.vehicles||[]).length} configured`;xs.forEach(v=>list.append(el("p",{text:`${v.title} · ${v.sources.status.displayValue} · ${v.sources.soc.displayValue}`})));if(!xs.length)list.append(el("p",{text:"No vehicles match the current filters."}));}search.addEventListener("input",draw);filter.addEventListener("change",draw);sort.addEventListener("change",draw);n.append(el("h3",{text:w.title||"Vehicles"}),search,filter,sort,summary,list);draw();return n;}
export function renderVehiclePanel(w,r={}){const v=normalizeVehicle(r,w.config||{}),n=art("dm-vehicle-panel");n.setAttribute("role","dialog");n.append(actionButton("Close",false,()=>w.config?.close?.(),n,"vehicle-action"),el("h3",{text:`Vehicle detail: ${v.title}`}),el("p",{text:`Sources: ${Object.values(v.entityIds).filter(Boolean).join(", ")||"none"}`}),el("p",{text:`Status ${v.reason} · available ${v.available}`}));["soc","range","odometer","chargingState","tripDistance","climateState","lockState","latitude","longitude","lastUpdate"].forEach(k=>line(n,k,v.sources[k]));v.sources.tyrePressure.forEach(x=>line(n,`Tyre ${x.title}`,x.source));btns(n,v.actions,r);return n;}
export function openVehicleDetailPanel(config,r={},trigger=null){return openSharedDetailPanel({trigger,label:"Vehicle detail",render:({close})=>renderVehiclePanel({type:"vehicle-control-panel",config:{...config,close}},r)}).panel;}
export function vehiclesSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-vehicles-section",attrs:{"data-section-id":section.id}});n.append(el("h3",{text:section.title||"Vehicles"}),renderWidgetLayout(section.config?.widgets||[{id:`${section.id}-vehicles-overview`,type:"vehicles-overview",config:section.config||{},layout:{size:"full"}},{id:`${section.id}-vehicle-status`,type:"vehicle-status",config:{},layout:{size:"medium"}}],context,context.widgetRegistry));return n;}
const cfg=()=>({vehicles:[],actions:[],distanceUnit:"km",pressureUnit:"psi",temperatureUnit:"C",powerUnit:"kW",energyUnit:"kWh"}),one=()=>({actions:[],...cfg()}),validator=c=>Object.values(c||{}).some(v=>String(v).includes("{{"))?[{field:"config",message:"Templates are not supported."}]:[];const widgets=[["vehicle-tile","Vehicle tile",renderVehicleTile,one],["vehicle-status","Vehicle status",renderVehicleStatus,one],["vehicle-battery","Vehicle battery",renderVehicleBattery,one],["vehicle-charging","Vehicle charging",renderVehicleCharging,one],["vehicle-range","Vehicle range",renderVehicleRange,one],["vehicle-trip","Vehicle trip",renderVehicleTrip,one],["vehicle-tyres","Vehicle tyres",renderVehicleTyres,one],["vehicle-location","Vehicle location",renderVehicleLocation,one],["vehicle-climate","Vehicle climate",renderVehicleClimate,one],["vehicle-security","Vehicle security",renderVehicleSecurity,one],["vehicles-overview","Vehicles overview",renderVehiclesOverview,cfg],["vehicle-control-panel","Vehicle control panel",renderVehiclePanel,one]];
export const VEHICLES_MODULE={id:"vehicles",schemaVersion:1,sections:[{type:"vehicles",displayName:"Vehicles",renderer:vehiclesSectionRenderer,defaultConfig:()=>({widgets:[{type:"vehicles-overview",config:cfg(),layout:{size:"full"}},{type:"vehicle-status",config:one(),layout:{size:"medium"}}]})}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,validator,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"vehicles-editor",title:"Vehicles editor"}],navigationEntries:[{sectionType:"vehicles",icon:"vehicle",title:"Vehicles"}],actions:["vehicle.service"],detailPanels:[{type:"vehicle-control-panel"}],defaultLayouts:[{sectionType:"vehicles",widgets:["vehicles-overview","vehicle-status"]}]};
