import { el } from "../render/dom.js";
import { renderWidgetLayout } from "../widgets/runtime.js";
import { actionButton } from "./action-state.js";
import { openSharedDetailPanel } from "./detail-panel-controller.js";
const RE=/^[a-z0-9_]+\.[a-z0-9_]+$/;const num=v=>Number.isFinite(Number(v))?Number(v):null;const state=(r,id)=>RE.test(id)?r.getEntityState?.(id):null;const bad=e=>!e||["unavailable","unknown"].includes(e.state)||!e.attributes||typeof e.attributes!=="object";const pct=v=>num(v)===null?null:Math.max(0,Math.min(100,Number(v)));
export function normalizeVehicle(r={},c={}){const id=typeof c==="string"?c:c.entityId||"",e=state(r,id),a=e?.attributes||{};return{entityId:id,title:c.title||a.friendly_name||id||"Vehicle",status:!id?"missing":bad(e)?"unavailable":"connected",state:e?.state||"unknown",battery:pct(a.battery_level??a.battery),charging:["charging","on"].includes(String(a.charging_state??a.charging??"")),range:num(a.range),odometer:num(a.odometer),trip:num(a.trip_distance),latitude:num(a.latitude),longitude:num(a.longitude),locked:a.locked??a.lock_state==="locked",climate:a.climate_state||a.hvac_state||"unknown",tyres:{frontLeft:num(a.tyre_front_left??a.tire_front_left),frontRight:num(a.tyre_front_right??a.tire_front_right),rearLeft:num(a.tyre_rear_left??a.tire_rear_left),rearRight:num(a.tyre_rear_right??a.tire_rear_right)},attributes:a};}
export function validateVehicleAction(a={}){const out=[];if(!["service","navigate-section","navigate-view","lock","unlock","climate-on","climate-off"].includes(a.type||"service"))out.push({field:"action.type",message:"Unsupported vehicle action."});if(a.entityId&&!RE.test(a.entityId))out.push({field:"action.entityId",message:"Invalid vehicle entity ID."});return out;}
function call(r,a,v){if(a.type==="navigate-section")return r.navigateToSection?.(a.sectionId);if(a.type==="navigate-view")return r.navigateToView?.(a.viewId);const svc={lock:["lock","lock"],unlock:["lock","unlock"],"climate-on":["climate","turn_on"],"climate-off":["climate","turn_off"]}[a.type];if(svc)return r.callService?.(svc[0],svc[1],{entity_id:a.entityId||v.entityId});return r.callService?.(a.domain,a.service,{entity_id:a.entityId||v.entityId,...(a.data||{})});}
function shell(w,c=""){return el("article",{className:`dm-widget ${c}`.trim()});}function vehicleLine(v){return `${v.title}: ${v.status==="connected"?v.state:v.status}`;}function detailBtn(n,v,r){n.append(actionButton("Details",!v.entityId,()=>openVehicleDetailPanel(v.entityId,r,n),n,"vehicle-action"));}
export function renderVehicleTile(w,r={}){const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-tile");n.append(el("h3",{text:w.title||v.title}),el("p",{text:vehicleLine(v)}));detailBtn(n,v,r);return n;}
export const renderVehicleStatus=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-status");n.append(el("h3",{text:w.title||"Vehicle status"}),el("p",{text:`${v.title}: ${v.state} · ${v.status}`}));detailBtn(n,v,r);return n;};
export const renderVehicleBattery=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-battery");n.append(el("h3",{text:w.title||"Vehicle battery"}),el("p",{text:`Battery: ${v.battery??"unknown"}%`}));return n;};
export const renderVehicleCharging=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-charging");n.append(el("h3",{text:w.title||"Vehicle charging"}),el("p",{text:v.charging?"Charging":"Not charging"}));return n;};
export const renderVehicleRange=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-range");n.append(el("h3",{text:w.title||"Vehicle range"}),el("p",{text:`Range: ${v.range??"unknown"}`}));return n;};
export const renderVehicleTrip=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-trip");n.append(el("h3",{text:w.title||"Vehicle trip"}),el("p",{text:`Trip: ${v.trip??"unknown"} · Odometer: ${v.odometer??"unknown"}`}));return n;};
export const renderVehicleTyres=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),t=v.tyres,n=shell(w,"dm-vehicle-tyres");n.append(el("h3",{text:w.title||"Vehicle tyres"}),el("p",{text:`FL ${t.frontLeft??"?"} · FR ${t.frontRight??"?"} · RL ${t.rearLeft??"?"} · RR ${t.rearRight??"?"}`}));return n;};
export const renderVehicleLocation=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-location");n.append(el("h3",{text:w.title||"Vehicle location"}),el("p",{text:v.latitude!==null&&v.longitude!==null?`Location ${v.latitude}, ${v.longitude}`:"Location unknown"}));return n;};
export const renderVehicleClimate=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-climate");n.append(el("h3",{text:w.title||"Vehicle climate"}),el("p",{text:`Climate: ${v.climate}`}));return n;};
export const renderVehicleSecurity=(w,r={})=>{const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-security");n.append(el("h3",{text:w.title||"Vehicle security"}),el("p",{text:v.locked?"Locked":"Unlocked"}));return n;};
export function renderVehiclesOverview(w,r={}){const ids=w.config?.entityIds||[],n=shell(w,"dm-vehicles-overview");n.append(el("h3",{text:w.title||"Vehicles"}));ids.map(id=>normalizeVehicle(r,{entityId:id})).forEach(v=>n.append(el("p",{text:`${vehicleLine(v)} · battery ${v.battery??"?"}% · range ${v.range??"?"}`})));if(!ids.length)n.append(el("p",{text:"No vehicles configured."}));return n;}
export function renderVehiclePanel(w,r={}){const v=normalizeVehicle(r,w.config||{}),n=shell(w,"dm-vehicle-panel");n.setAttribute("role","dialog");n.append(actionButton("Close",false,()=>w.config?.close?.(),n,"vehicle-action"),el("h3",{text:`Vehicle detail: ${v.title}`}),el("p",{text:`${v.state} · battery ${v.battery??"?"}% · range ${v.range??"?"}`}));for(const a of w.config?.actions||[])n.append(actionButton(a.title||a.type,validateVehicleAction(a).length,()=>call(r,a,v),n,"vehicle-action"));return n;}
export function openVehicleDetailPanel(entityId,r={},trigger=null){return openSharedDetailPanel({trigger,label:`Vehicle detail ${entityId}`,render:({close})=>renderVehiclePanel({type:"vehicle-control-panel",config:{entityId,close,actions:[{type:"lock",title:"Lock"},{type:"unlock",title:"Unlock"}]}},r)}).panel;}
export function vehiclesSectionRenderer(section,cards,context){const n=el("section",{className:"dashboardmodern-section dm-vehicles-section",attrs:{"data-section-id":section.id}});n.append(el("h3",{text:section.title||"Vehicles"}),renderWidgetLayout(section.config?.widgets||[{id:`${section.id}-vehicles-overview`,type:"vehicles-overview",config:section.config||{},layout:{size:"full"}}],context,context.widgetRegistry));return n;}
const vcfg=()=>({entityId:""}), validator=c=>c?.entityId&&!RE.test(c.entityId)?[{field:"entityId",message:"Invalid vehicle entity ID."}]:[];const widgets=[["vehicle-tile","Vehicle tile",renderVehicleTile,vcfg],["vehicle-status","Vehicle status",renderVehicleStatus,vcfg],["vehicle-battery","Vehicle battery",renderVehicleBattery,vcfg],["vehicle-charging","Vehicle charging",renderVehicleCharging,vcfg],["vehicle-range","Vehicle range",renderVehicleRange,vcfg],["vehicle-trip","Vehicle trip",renderVehicleTrip,vcfg],["vehicle-tyres","Vehicle tyres",renderVehicleTyres,vcfg],["vehicle-location","Vehicle location",renderVehicleLocation,vcfg],["vehicle-climate","Vehicle climate",renderVehicleClimate,vcfg],["vehicle-security","Vehicle security",renderVehicleSecurity,vcfg],["vehicles-overview","Vehicles overview",renderVehiclesOverview,()=>({entityIds:[]})],["vehicle-control-panel","Vehicle control panel",renderVehiclePanel,()=>({entityId:"",actions:[]})]];
export const VEHICLES_MODULE={id:"vehicles",schemaVersion:1,sections:[{type:"vehicles",displayName:"Vehicles",renderer:vehiclesSectionRenderer}],widgets:widgets.map(([type,displayName,renderer,defaultConfig])=>({type,displayName,renderer,defaultConfig,validator,schemaVersion:1,supportedLayoutSizes:["small","medium","large","full"]})),editorPanels:[{id:"vehicles-editor",title:"Vehicles editor"}],navigationEntries:[{sectionType:"vehicles",icon:"vehicle",title:"Vehicles"}],actions:["vehicle.lock","vehicle.unlock","vehicle.climate_on","vehicle.climate_off"],detailPanels:[{type:"vehicle-control-panel"}],defaultLayouts:[{sectionType:"vehicles",widgets:["vehicles-overview"]}]};
