export const NAV_DEFAULTS = Object.freeze({ placement: "bottom", visibilityMode: "fixed", overflowMode: "scroll", showLabels: true, compactMode: false, itemSize: "medium", autoHideDelay: 2500, edgeIndicators: true });
const allowed = { placement: ["bottom"], visibilityMode: ["fixed", "auto-hide"], overflowMode: ["scroll", "more-menu"], itemSize: ["small", "medium", "large"] };
export function normalizeNavigationConfig(config = {}) { const nav = config?.navigation || config || {}; return { ...NAV_DEFAULTS, placement: allowed.placement.includes(nav.placement) ? nav.placement : NAV_DEFAULTS.placement, visibilityMode: allowed.visibilityMode.includes(nav.visibilityMode) ? nav.visibilityMode : NAV_DEFAULTS.visibilityMode, overflowMode: allowed.overflowMode.includes(nav.overflowMode) ? nav.overflowMode : NAV_DEFAULTS.overflowMode, showLabels: typeof nav.showLabels === "boolean" ? nav.showLabels : NAV_DEFAULTS.showLabels, compactMode: typeof nav.compactMode === "boolean" ? nav.compactMode : NAV_DEFAULTS.compactMode, itemSize: allowed.itemSize.includes(nav.itemSize) ? nav.itemSize : NAV_DEFAULTS.itemSize, autoHideDelay: Number.isFinite(nav.autoHideDelay) && nav.autoHideDelay >= 500 && nav.autoHideDelay <= 10000 ? nav.autoHideDelay : NAV_DEFAULTS.autoHideDelay, edgeIndicators: typeof nav.edgeIndicators === "boolean" ? nav.edgeIndicators : NAV_DEFAULTS.edgeIndicators }; }
export function validateNavigationConfig(config = {}) { const nav = config?.navigation || config || {}; const errors = []; for (const key of ["visibilityMode", "overflowMode", "itemSize"]) if (nav[key] !== undefined && !allowed[key].includes(nav[key])) errors.push({ field: `dashboard.config.navigation.${key}`, message: `Invalid ${key}.` }); if (nav.autoHideDelay !== undefined && (!Number.isFinite(Number(nav.autoHideDelay)) || Number(nav.autoHideDelay) < 500 || Number(nav.autoHideDelay) > 10000)) errors.push({ field: "dashboard.config.navigation.autoHideDelay", message: "Auto-hide delay must be between 500 and 10000 ms." }); return errors; }
export function sectionNavigationEntry(section, index = 0) { const nav = section?.navigation || {}; return { sectionId: section?.id || "", type: section?.type || "custom", title: nav.title ?? section?.title ?? section?.id ?? "Section", icon: nav.icon ?? section?.icon ?? section?.type ?? "section", accent: nav.accent ?? section?.accent ?? "", enabled: nav.enabled ?? section?.enabled ?? true, visibleInNavbar: nav.visibleInNavbar ?? section?.visibleInNavbar ?? true, order: Number.isFinite(Number(nav.order ?? section?.order)) ? Number(nav.order ?? section.order) : index, badge: nav.badge ?? section?.badge ?? null, visibility: nav.visibility ?? section?.visibility ?? { enabled: true, condition: "always" } }; }
export function navigationEntriesForSections(sections = []) { return (sections || []).map(sectionNavigationEntry).filter((entry) => entry.enabled !== false && entry.visibleInNavbar !== false && entry.visibility?.enabled !== false).sort((a, b) => a.order - b.order || a.title.localeCompare(b.title) || a.sectionId.localeCompare(b.sectionId)); }
export function measureOverflow(container) { return Boolean(container && container.scrollWidth > container.clientWidth + 1); }
export function splitMoreMenuItems(entries, availableWidth, itemWidth = 96) { if (!Number.isFinite(availableWidth) || availableWidth <= 0) return { visible: entries, overflow: [] }; if (entries.length * itemWidth <= availableWidth) return { visible: entries, overflow: [] }; const moreWidth = itemWidth; const count = Math.max(0, Math.floor((availableWidth - moreWidth) / itemWidth)); return { visible: entries.slice(0, count), overflow: entries.slice(count) }; }
export function revealOnScroll(prevY, nextY) { return nextY < prevY; }
export function reducedMotion() { return typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches; }
