import { el, emptyState } from "../render/dom.js";
export const UNKNOWN_SECTION_TYPE = "unknown-section";
export function renderUnknownSection(section) { const shell = el("section", { className: "dashboardmodern-section dashboardmodern-section-unknown", attrs: { "data-section-id": section?.id || "", "data-unsupported-section-type": section?.type || "" } }); shell.append(el("h3", { text: section?.title || "Unsupported section" })); shell.append(emptyState("This section type is not registered. It remains editable and safe.")); return shell; }
export function assertSectionDefinition(definition) { if (!definition || typeof definition !== "object") throw new Error("Section definition is required."); if (typeof definition.type !== "string" || !definition.type.trim()) throw new Error("Section definition type must be a non-empty string."); if (typeof definition.displayName !== "string" || !definition.displayName.trim()) throw new Error(`Section definition ${definition.type} needs a display name.`); for (const [name, value] of Object.entries({ validator: definition.validator, editor: definition.editor, renderer: definition.renderer, layout: definition.layout, badgeResolver: definition.badgeResolver, defaultConfig: definition.defaultConfig })) if (value !== undefined && typeof value !== "function") throw new Error(`Section definition ${definition.type} ${name} must be a function.`); if (definition.supportedCards !== undefined && !Array.isArray(definition.supportedCards)) throw new Error(`Section definition ${definition.type} supportedCards must be an array.`); if (definition.supportedWidgets !== undefined && !Array.isArray(definition.supportedWidgets)) throw new Error(`Section definition ${definition.type} supportedWidgets must be an array.`); if (definition.schemaVersion !== undefined && (!Number.isInteger(definition.schemaVersion) || definition.schemaVersion < 1)) throw new Error(`Section definition ${definition.type} schemaVersion must be a positive integer.`); }
export function createSectionRegistry() { const definitions = new Map(); let sequence = 0; return { register(definition) { assertSectionDefinition(definition); if (definitions.has(definition.type)) throw new Error(`Section type already registered: ${definition.type}`); const normalized = Object.freeze({ icon: "section", defaultTitle: definition.displayName, defaultConfig: () => ({}), supportedCards: [], supportedWidgets: [], navigation: {}, owner: "builtin", schemaVersion: 1, ...definition, registrationOrder: sequence++ }); definitions.set(normalized.type, normalized); return normalized; }, get(type) { return definitions.get(type) || definitions.get(UNKNOWN_SECTION_TYPE) || null; }, resolve(type) { return this.get(type) || { type: UNKNOWN_SECTION_TYPE, displayName: "Unknown section", icon: "warning", renderer: renderUnknownSection, owner: "system", schemaVersion: 1, registrationOrder: Number.MAX_SAFE_INTEGER }; }, list() { return [...definitions.values()].sort((a, b) => a.registrationOrder - b.registrationOrder || a.type.localeCompare(b.type)); }, types() { return this.list().map((definition) => definition.type); }, clear() { definitions.clear(); sequence = 0; } }; }
export function registerBuiltInSectionTypes(registry) { registry.register({ type: UNKNOWN_SECTION_TYPE, displayName: "Unknown section", icon: "warning", renderer: renderUnknownSection, owner: "system" }); for (const type of ["home", "rooms", "lights", "climate", "covers", "energy", "appliances", "irrigation", "pool", "security", "cameras", "vehicles", "server", "media", "people", "statistics", "configuration", "custom"]) registry.register({ type, displayName: type[0].toUpperCase() + type.slice(1), icon: type, defaultTitle: type[0].toUpperCase() + type.slice(1), owner: "builtin", navigation: { enabled: true, visibleInNavbar: true } }); return registry; }
export const DEFAULT_SECTION_REGISTRY = registerBuiltInSectionTypes(createSectionRegistry());
export const registerSectionType = (definition, registry = DEFAULT_SECTION_REGISTRY) => registry.register(definition);
export const getSectionType = (type, registry = DEFAULT_SECTION_REGISTRY) => registry.get(type);
export const listSectionTypes = (registry = DEFAULT_SECTION_REGISTRY) => registry.list();
