import { el, emptyState } from "../render/dom.js";
import { fieldError, textInput } from "../editor/dashboard-form.js";
import { renderIcon } from "./icon-registry.js";

export const ENERGY_OVERVIEW_TYPE = "energy-overview";
export const ENERGY_FLOWS_TYPE = "energy-flows";
export const BATTERY_STATUS_TYPE = "battery-status";
export const SOLAR_PRODUCTION_TYPE = "solar-production";
export const GRID_STATUS_TYPE = "grid-status";
const BAD = new Set(["", "unknown", "unavailable"]);
const TEMPLATE = /\{\{|\}\}|\{%|%\}|<script|javascript:/i;
const ENTITY_FIELDS = ["productionEntityId", "houseConsumptionEntityId", "gridImportEntityId", "gridExportEntityId", "batterySocEntityId", "batteryPowerEntityId", "batteryCapacityEntityId", "dailyProductionEntityId", "peakProductionEntityId", "dailyImportEntityId", "dailyExportEntityId"];
const LABELS = { productionEntityId: "PV current production", houseConsumptionEntityId: "House consumption", gridImportEntityId: "Grid import", gridExportEntityId: "Grid export", batterySocEntityId: "Battery SOC", batteryPowerEntityId: "Battery power", batteryCapacityEntityId: "Battery remaining capacity", dailyProductionEntityId: "Daily solar production", peakProductionEntityId: "Peak solar production", dailyImportEntityId: "Daily import total", dailyExportEntityId: "Daily export total" };
const OPTIONAL = new Set(["batteryCapacityEntityId", "dailyProductionEntityId", "peakProductionEntityId", "dailyImportEntityId", "dailyExportEntityId"]);
function base() { return { productionEntityId: "", houseConsumptionEntityId: "", gridImportEntityId: "", gridExportEntityId: "", batterySocEntityId: "", batteryPowerEntityId: "", batteryCapacityEntityId: "", dailyProductionEntityId: "", peakProductionEntityId: "", dailyImportEntityId: "", dailyExportEntityId: "", powerUnit: "kW", energyUnit: "kWh", socUnit: "%" }; }
export const defaultEnergyOverviewConfig = base;
export const defaultEnergyFlowsConfig = base;
export const defaultBatteryStatusConfig = () => ({ batterySocEntityId: "", batteryPowerEntityId: "", batteryCapacityEntityId: "", powerUnit: "kW", energyUnit: "kWh", socUnit: "%" });
export const defaultSolarProductionConfig = () => ({ productionEntityId: "", dailyProductionEntityId: "", peakProductionEntityId: "", powerUnit: "kW", energyUnit: "kWh" });
export const defaultGridStatusConfig = () => ({ gridImportEntityId: "", gridExportEntityId: "", dailyImportEntityId: "", dailyExportEntityId: "", powerUnit: "kW", energyUnit: "kWh" });
function parseNumber(raw) { const n = Number(String(raw ?? "").trim().replace(",", ".")); return Number.isFinite(n) ? n : null; }
function fmt(value, locale, unit) { return value === null ? "Unavailable" : `${new Intl.NumberFormat(locale, { maximumFractionDigits: 2 }).format(value)} ${unit}`.trim(); }
function metric(runtime, entityId, unit, label, optional = false) { if (!entityId?.trim()) return { label, status: optional ? "not-configured" : "missing-config", available: false, value: null, display: optional ? "Optional" : "Unavailable", entityId }; const state = runtime.getEntityState?.(entityId); if (!state) return { label, status: "missing-entity", available: false, value: null, display: "Unavailable", entityId }; const raw = String(state.state ?? "").trim(); if (BAD.has(raw)) return { label, status: raw || "unavailable", available: false, value: null, display: "Unavailable", entityId }; const value = parseNumber(raw); if (value === null) return { label, status: "malformed", available: false, value: null, display: "Unavailable", entityId }; const actualUnit = state.attributes?.unit_of_measurement || unit; return { label, status: "ok", available: true, value, display: fmt(value, runtime.locale || "it-IT", actualUnit), entityId }; }
export function normalizeEnergy(runtime = {}, config = {}) { const c = { ...base(), ...config }; const power = c.powerUnit || "kW", energy = c.energyUnit || "kWh", soc = c.socUnit || "%"; const m = { production: metric(runtime, c.productionEntityId, power, "Production"), house: metric(runtime, c.houseConsumptionEntityId, power, "House"), import: metric(runtime, c.gridImportEntityId, power, "Import"), export: metric(runtime, c.gridExportEntityId, power, "Export"), soc: metric(runtime, c.batterySocEntityId, soc, "SOC"), batteryPower: metric(runtime, c.batteryPowerEntityId, power, "Battery power"), capacity: metric(runtime, c.batteryCapacityEntityId, energy, "Remaining capacity", true), dailyProduction: metric(runtime, c.dailyProductionEntityId, energy, "Daily production", true), peak: metric(runtime, c.peakProductionEntityId, power, "Peak", true), dailyImport: metric(runtime, c.dailyImportEntityId, energy, "Daily import", true), dailyExport: metric(runtime, c.dailyExportEntityId, energy, "Daily export", true) }; const self = m.production.available && m.house.available ? Math.max(0, Math.min(m.production.value, m.house.value)) : null; const batteryMode = !m.batteryPower.available ? "unavailable" : m.batteryPower.value > 0 ? "charging" : m.batteryPower.value < 0 ? "discharging" : "idle"; return { metrics: m, selfConsumption: { label: "Self-consumption", status: self === null ? "unavailable" : "ok", available: self !== null, value: self, display: fmt(self, runtime.locale || "it-IT", power) }, batteryMode, flows: { pvToHouse: m.production.available && m.house.available ? Math.min(m.production.value, m.house.value) : null, gridToHouse: m.import.available ? Math.max(0, m.import.value) : null, houseToGrid: m.export.available ? Math.max(0, m.export.value) : null, battery: m.batteryPower.available ? Math.abs(m.batteryPower.value) : null } }; }
export function validateEnergyConfig(c = {}, required = []) { const e = []; if (!c || typeof c !== "object" || Array.isArray(c)) return [{ field: "config", message: "Config must be an object." }]; for (const k of ENTITY_FIELDS) { if (c[k] !== undefined && typeof c[k] !== "string") e.push({ field: `config.${k}`, message: `${k} must be a string.` }); if (typeof c[k] === "string" && TEMPLATE.test(c[k])) e.push({ field: `config.${k}`, message: `${k} cannot contain templates or executable expressions.` }); } for (const k of required) if (typeof c[k] !== "string" || !c[k].trim()) e.push({ field: `config.${k}`, message: `${k} is required.` }); for (const k of ["powerUnit", "energyUnit", "socUnit"]) if (c[k] !== undefined && typeof c[k] !== "string") e.push({ field: `config.${k}`, message: `${k} must be a string.` }); return e; }
const ovReq = ["productionEntityId", "houseConsumptionEntityId", "gridImportEntityId", "gridExportEntityId", "batterySocEntityId", "batteryPowerEntityId"];
export const validateEnergyOverviewConfig = (c) => validateEnergyConfig(c, ovReq);
export const validateEnergyFlowsConfig = (c) => validateEnergyConfig(c, ["productionEntityId", "houseConsumptionEntityId", "gridImportEntityId", "gridExportEntityId", "batteryPowerEntityId"]);
export const validateBatteryStatusConfig = (c) => validateEnergyConfig(c, ["batterySocEntityId", "batteryPowerEntityId"]);
export const validateSolarProductionConfig = (c) => validateEnergyConfig(c, ["productionEntityId"]);
export const validateGridStatusConfig = (c) => validateEnergyConfig(c, ["gridImportEntityId", "gridExportEntityId"]);
function statusAttrs(metric) { return { "data-status": metric.status, "aria-label": `${metric.label}: ${metric.display}` }; }
function tile(icon, metric, accent = "energy") { const node = el("button", { className: "dm-energy-tile", attrs: { type: "button", "data-accent": accent, ...statusAttrs(metric) } }); node.append(renderIcon(icon, { label: metric.label }), el("span", { className: "dm-energy-label", text: metric.label }), el("strong", { text: metric.display })); return node; }
function clickable(node, metric, runtime) { if (metric.available) node.addEventListener("click", () => runtime.interactions?.openHistory?.(metric.entityId, metric.label)); return node; }
export function renderEnergyOverviewCard(card, runtime = {}) { const n = normalizeEnergy(runtime, card.config); const shell = el("article", { className: "dashboardmodern-card dm-energy-card dm-energy-overview", attrs: { "data-card-kind": ENERGY_OVERVIEW_TYPE } }); shell.append(el("h3", { className: "section-title", text: card.title || "Energy overview" })); const grid = el("div", { className: "dm-energy-grid" }); [["sun", n.metrics.production, "solar"], ["heating", n.metrics.house, "load"], ["grid", n.metrics.import, "grid"], ["grid", n.metrics.export, "grid"], ["battery", n.metrics.soc, "battery"], ["battery", n.metrics.batteryPower, "battery"], ["sun", n.selfConsumption, "green"]].forEach(([i, m, a]) => grid.append(clickable(tile(i, m, a), m, runtime))); shell.append(grid); return shell; }
export function renderEnergyFlowsCard(card, runtime = {}) { const n = normalizeEnergy(runtime, card.config); const shell = el("article", { className: "dashboardmodern-card dm-energy-card dm-energy-flows", attrs: { "data-card-kind": ENERGY_FLOWS_TYPE } }); shell.append(el("h3", { className: "section-title", text: card.title || "Energy flows" })); const flows = [["PV", "→", "House", n.flows.pvToHouse], ["Grid", "→", "House", n.flows.gridToHouse], ["House", "→", "Grid", n.flows.houseToGrid], [n.batteryMode === "charging" ? "House" : "Battery", "→", n.batteryMode === "charging" ? "Battery" : "House", n.flows.battery]]; flows.forEach(([from, arrow, to, v]) => shell.append(el("div", { className: "dm-energy-flow", attrs: { "data-status": v === null ? "unavailable" : "ok" } }, [el("span", { text: from }), el("b", { className: "dm-flow-arrow", text: arrow }), el("span", { text: to }), el("strong", { text: fmt(v, runtime.locale || "it-IT", card.config?.powerUnit || "kW") })]))); return shell; }
export function renderBatteryStatusCard(card, runtime = {}) { const n = normalizeEnergy(runtime, card.config); const shell = el("article", { className: "dashboardmodern-card dm-energy-card", attrs: { "data-card-kind": BATTERY_STATUS_TYPE, "data-mode": n.batteryMode } }); shell.append(el("h3", { className: "section-title", text: card.title || "Battery status" }), tile("battery", n.metrics.soc, "battery"), tile("battery", { ...n.metrics.batteryPower, label: `Power (${n.batteryMode})` }, "battery"), tile("battery", n.metrics.capacity, "battery")); return shell; }
export function renderSolarProductionCard(card, runtime = {}) { const n = normalizeEnergy(runtime, card.config); const shell = el("article", { className: "dashboardmodern-card dm-energy-card", attrs: { "data-card-kind": SOLAR_PRODUCTION_TYPE } }); shell.append(el("h3", { className: "section-title", text: card.title || "Solar production" }), tile("sun", n.metrics.production, "solar"), tile("sun", n.metrics.dailyProduction, "solar"), tile("sun", n.metrics.peak, "solar")); return shell; }
export function renderGridStatusCard(card, runtime = {}) { const n = normalizeEnergy(runtime, card.config); const shell = el("article", { className: "dashboardmodern-card dm-energy-card", attrs: { "data-card-kind": GRID_STATUS_TYPE } }); shell.append(el("h3", { className: "section-title", text: card.title || "Grid status" }), tile("grid", n.metrics.import, "grid"), tile("grid", n.metrics.export, "grid"), tile("grid", n.metrics.dailyImport, "grid"), tile("grid", n.metrics.dailyExport, "grid")); return shell; }
function energyEditor(fields) { return (documentRef, card, controller, errors = []) => { const form = documentRef.createElement("section"); form.className = "dashboardmodern-plugin-editor"; fields.forEach((k) => form.append(textInput(documentRef, LABELS[k] || k, card.config?.[k] || "", (v) => controller.updateCardConfigPatch(card.id, { [k]: v }), `card:${card.id}:config.${k}`))); ["powerUnit", "energyUnit", "socUnit"].forEach((k) => form.append(textInput(documentRef, k, card.config?.[k] || "", (v) => controller.updateCardConfigPatch(card.id, { [k]: v }), `card:${card.id}:config.${k}`))); errors.forEach((error) => form.append(fieldError(documentRef, error.message))); return form; }; }
export const renderEnergyOverviewEditor = energyEditor(ovReq.concat(["batteryCapacityEntityId", "dailyProductionEntityId", "peakProductionEntityId", "dailyImportEntityId", "dailyExportEntityId"]));
export const renderEnergyFlowsEditor = energyEditor(["productionEntityId", "houseConsumptionEntityId", "gridImportEntityId", "gridExportEntityId", "batteryPowerEntityId"]);
export const renderBatteryStatusEditor = energyEditor(["batterySocEntityId", "batteryPowerEntityId", "batteryCapacityEntityId"]);
export const renderSolarProductionEditor = energyEditor(["productionEntityId", "dailyProductionEntityId", "peakProductionEntityId"]);
export const renderGridStatusEditor = energyEditor(["gridImportEntityId", "gridExportEntityId", "dailyImportEntityId", "dailyExportEntityId"]);
