import { el, emptyState } from "../render/dom.js";
import { fieldError, textInput } from "../editor/dashboard-form.js";

export const WEATHER_CURRENT_TYPE = "weather-current";
export const WEATHER_FORECAST_TYPE = "weather-forecast";
const BAD = new Set(["unknown", "unavailable", ""]);
export const WEATHER_CONDITIONS = Object.freeze({
  "clear-night": { icon: "🌙", label: "Sereno (Notte)" }, cloudy: { icon: "☁️", label: "Nuvoloso" }, fog: { icon: "🌫️", label: "Nebbia" }, hail: { icon: "🌫️", label: "Grandine" }, lightning: { icon: "⛈️", label: "Fulmini" }, "lightning-rainy": { icon: "⛈️", label: "Temporale" }, partlycloudy: { icon: "⛅", label: "Poco Nuvoloso" }, pouring: { icon: "🌧️", label: "Acquazzone" }, rainy: { icon: "🌧️", label: "Pioggia" }, snowy: { icon: "❄️", label: "Neve" }, "snowy-rainy": { icon: "🌨️", label: "Nevischio" }, sunny: { icon: "☀️", label: "Soleggiato" }, windy: { icon: "💨", label: "Ventoso" }, "windy-variant": { icon: "💨", label: "Vento Forte" },
});
export function weatherConditionMeta(condition) { return WEATHER_CONDITIONS[String(condition || "")] || { icon: "☀️", label: String(condition || "Sconosciuto").replaceAll("-", " ") }; }
function num(v) { const n = Number(v); return Number.isFinite(n) ? n : null; }
function fmt(n, locale = "it-IT", suffix = "") { return n === null ? "--" : `${new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(n)}${suffix}`; }
function entity(runtime, id) { return id ? runtime?.getEntityState?.(id) || null : null; }
function available(s) { return s && !BAD.has(String(s.state ?? "")); }
export function normalizeWeather(runtime = {}, config = {}) {
  const locale = runtime.locale || "it-IT"; const state = entity(runtime, config.weatherEntityId);
  if (!available(state)) return { available: false, locale, reason: config.weatherEntityId ? "Meteo non disponibile" : "Entità meteo richiesta" };
  const a = state.attributes && typeof state.attributes === "object" ? state.attributes : {};
  const tempEntity = entity(runtime, config.outdoorTemperatureEntityId); const humEntity = entity(runtime, config.outdoorHumidityEntityId); const apparent = entity(runtime, config.apparentTemperatureEntityId); const updated = entity(runtime, config.updateTimestampEntityId);
  const temperature = num(available(tempEntity) ? tempEntity.state : a.temperature);
  const humidity = num(available(humEntity) ? humEntity.state : a.humidity);
  const unit = config.unitDisplay || a.temperature_unit || "°C";
  const windUnit = a.wind_speed_unit || "km/h";
  const forecast = Array.isArray(a.forecast) ? a.forecast.map((f) => ({ datetime: typeof f.datetime === "string" ? f.datetime : "", condition: String(f.condition || ""), temperature: num(f.temperature), templow: num(f.templow ?? f.low_temperature), precipitation: num(f.precipitation) })).filter((f) => f.datetime || f.temperature !== null) : [];
  return { available: true, entityId: state.entity_id || config.weatherEntityId, condition: String(state.state), conditionMeta: weatherConditionMeta(state.state), temperature, temperatureText: fmt(temperature, locale, unit), apparentTemperature: num(available(apparent) ? apparent.state : a.apparent_temperature), humidity, humidityText: fmt(humidity, locale, "%"), pressureText: fmt(num(a.pressure), locale, a.pressure_unit ? ` ${a.pressure_unit}` : ""), windText: fmt(num(a.wind_speed), locale, ` ${windUnit}`), windBearing: a.wind_bearing ?? null, updatedText: available(updated) ? String(updated.state) : (state.last_updated ? new Date(state.last_updated).toLocaleString(locale) : ""), forecast, locale };
}
export function defaultWeatherCurrentConfig() { return { weatherEntityId: "weather.home", outdoorTemperatureEntityId: "", outdoorHumidityEntityId: "", apparentTemperatureEntityId: "", updateTimestampEntityId: "", showTitle: false, showSubtitle: false, unitDisplay: "°C" }; }
export function defaultWeatherForecastConfig() { return { weatherEntityId: "weather.home", showForecast: true, forecastItemCount: 7, unitDisplay: "°" }; }
export function validateWeatherCurrentConfig(c = {}) { const e = []; if (!c || typeof c !== "object" || Array.isArray(c)) return [{ field: "config", message: "Config must be an object." }]; if (typeof c.weatherEntityId !== "string" || !c.weatherEntityId.trim()) e.push({ field: "config.weatherEntityId", message: "Weather entity id is required." }); for (const k of ["outdoorTemperatureEntityId", "outdoorHumidityEntityId", "apparentTemperatureEntityId", "updateTimestampEntityId", "unitDisplay"]) if (c[k] !== undefined && typeof c[k] !== "string") e.push({ field: `config.${k}`, message: `${k} must be a string.` }); for (const k of ["showTitle", "showSubtitle"]) if (c[k] !== undefined && typeof c[k] !== "boolean") e.push({ field: `config.${k}`, message: `${k} must be a boolean.` }); return e; }
export function validateWeatherForecastConfig(c = {}) { const e = validateWeatherCurrentConfig({ weatherEntityId: c.weatherEntityId, unitDisplay: c.unitDisplay, showTitle: false, showSubtitle: false }); if (c.showForecast !== undefined && typeof c.showForecast !== "boolean") e.push({ field: "config.showForecast", message: "showForecast must be a boolean." }); if (!Number.isInteger(c.forecastItemCount) || c.forecastItemCount < 1 || c.forecastItemCount > 10) e.push({ field: "config.forecastItemCount", message: "forecastItemCount must be an integer from 1 to 10." }); return e; }
export function renderWeatherCurrentCard(card, runtime = {}) { const c = { ...defaultWeatherCurrentConfig(), ...(card.config || {}) }; const w = normalizeWeather(runtime, c); const shell = el("article", { className: "dashboardmodern-card legacy-card weather-widget dm-weather-current", attrs: { "data-card-kind": WEATHER_CURRENT_TYPE, tabindex: "0", role: "button", "aria-label": "Apri previsioni meteo" } }); if (c.showTitle) shell.append(el("h3", { className: "section-title", text: card.title || "Meteo" })); if (!w.available) { shell.append(emptyState(w.reason)); return shell; } const left = el("div", { className: "w-left" }); left.append(el("div", { className: "w-icon", text: w.conditionMeta.icon, attrs: { "aria-label": w.conditionMeta.label, role: "img" } })); const wrap = el("div", { className: "w-temp-wrap" }, [el("span", { className: "w-temp", text: w.temperatureText }), el("span", { className: "w-state", text: w.conditionMeta.label })]); left.append(wrap); const right = el("div", { className: "w-right" }, [el("div", { className: "w-detail", text: `💧 Umidità ${w.humidityText}` }), el("div", { className: "w-detail", text: `💨 Vento ${w.windText}` })]); shell.append(left, right); shell.addEventListener("click", () => runtime.interactions?.openWeather?.(w.entityId)); shell.addEventListener("keydown", (ev) => { if (ev.key === "Enter" || ev.key === " ") runtime.interactions?.openWeather?.(w.entityId); }); return shell; }
export function renderWeatherForecastCard(card, runtime = {}) { const c = { ...defaultWeatherForecastConfig(), ...(card.config || {}) }; const w = normalizeWeather(runtime, c); const shell = el("article", { className: "dashboardmodern-card legacy-card dm-weather-forecast", attrs: { "data-card-kind": WEATHER_FORECAST_TYPE } }); shell.append(el("h3", { className: "section-title", text: card.title || "PREVISIONI 7 GIORNI" })); if (!w.available || !c.showForecast) { shell.append(emptyState(w.reason || "Previsioni nascoste")); return shell; } for (const f of w.forecast.slice(0, c.forecastItemCount)) { const m = weatherConditionMeta(f.condition); const day = f.datetime ? new Date(f.datetime).toLocaleDateString(w.locale, { weekday: "long", day: "numeric" }).toUpperCase() : "—"; shell.append(el("div", { className: "detail-row dm-forecast-row" }, [el("span", { className: "dm-forecast-icon", text: m.icon, attrs: { role: "img", "aria-label": m.label } }), el("strong", { text: day }), el("span", { className: "dm-forecast-temp", text: `${f.templow !== null ? fmt(f.templow, w.locale, c.unitDisplay) + " " : ""}${fmt(f.temperature, w.locale, c.unitDisplay)}` })])); } if (!w.forecast.length) shell.append(emptyState("Nessuna previsione disponibile")); return shell; }
function weatherEditor(documentRef, card, controller, errors = [], forecast = false) { const form = documentRef.createElement("section"); form.className = "dashboardmodern-plugin-editor"; const add = (k, label) => form.append(textInput(documentRef, label, card.config?.[k] || "", (v) => controller.updateCardConfigPatch(card.id, { [k]: v }), `card:${card.id}:config.${k}`)); add("weatherEntityId", "Weather entity id"); if (!forecast) { add("outdoorTemperatureEntityId", "Outdoor temperature entity id"); add("outdoorHumidityEntityId", "Outdoor humidity entity id"); add("apparentTemperatureEntityId", "Apparent temperature entity id"); add("updateTimestampEntityId", "Update timestamp entity id"); } else add("forecastItemCount", "Forecast item count (1-10)"); add("unitDisplay", "Unit display"); for (const error of errors) form.append(fieldError(documentRef, error.message)); return form; }
export const renderWeatherCurrentEditor = (d, c, ctl, e) => weatherEditor(d, c, ctl, e, false);
export const renderWeatherForecastEditor = (d, c, ctl, e) => weatherEditor(d, c, ctl, e, true);
