export const THEME_TOKENS = Object.freeze({accent:"#22c55e",green:"#22c55e",background:"var(--dm-bg)",cardSurface:"var(--dm-surface)",border:"var(--dm-border)",text:"var(--dm-text)",mutedText:"var(--dm-muted)",radius:"var(--dm-radius-xl)",shadow:"var(--dm-shadow-card)",spacing:"1rem",duration:"220ms"});
export const APPLIANCE_TYPES = Object.freeze(["washing-machine","dryer","dishwasher","oven","refrigerator","freezer","robot-vacuum","pool","irrigation","generic-device"]);
export function defaultBrandingConfig(title="Smart Home Dashboard"){return{branding:{title,subtitle:"Premium Home Assistant dashboard",logoRef:"",accentColor:"#22c55e"},theme:{mode:"auto",accentColor:"#22c55e"}};}
export function defaultAction(){return{type:"service",domain:"",service:"",target:{entity_id:""},serviceData:{},confirmation:false};}
export function defaultVisibility(){return{enabled:true,entityId:"",condition:"always",value:""};}
export function defaultCardLayout(){return{desktop:{columns:4,rows:3},tablet:{columns:4,rows:3},mobile:{columns:4,rows:3}};}
export function entityRef(entityId="",label=""){return{entityId,label,required:false};}
export function applianceConfig(){return{id:"",title:"Appliance",subtitle:"",applianceType:"generic-device",icon:"appliance",imageRef:"",primaryStateEntityId:"",powerEntityId:"",energyEntityId:"",progressEntityId:"",remainingTimeEntityId:"",statusMapping:{},startAction:defaultAction(),pauseAction:defaultAction(),stopAction:defaultAction(),customActions:[],visibility:defaultVisibility(),layout:defaultCardLayout(),detailPopup:{enabled:false,fields:[]}};}
export const PLUGIN_SCHEMA_FIELDS=Object.freeze({branding:["title","subtitle","logoRef","accentColor"],theme:["mode","accentColor"],section:["id","title","subtitle","icon","visibility","layout"],layout:["desktop","tablet","mobile"],entityReference:["entityId","label","required"],action:["type","domain","service","target","serviceData","confirmation"],visibility:["enabled","entityId","condition","value"],genericAppliance:Object.keys(applianceConfig())});
