"""Generate frontend build provenance without requiring a bundler."""

from __future__ import annotations

import datetime
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "custom_components/dashboardmodern/frontend/legacy/build-info.js"


def main() -> None:
    manifest = json.loads(
        (ROOT / "custom_components/dashboardmodern/manifest.json").read_text()
    )
    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
    ).strip()
    date = datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat()
    asset_hash = subprocess.check_output(
        ["git", "rev-parse", "--short=12", "HEAD"], cwd=ROOT, text=True
    ).strip()
    payload = json.dumps(
        {
            "version": manifest["version"],
            "date": date,
            "commit": commit,
            "assetHash": asset_hash,
        }
    )
    OUT.write_text(
        "// Generated by scripts/generate_build_info.py during release packaging.\n"
        f"export const BUILD_INFO = Object.freeze({payload});\n"
    )


if __name__ == "__main__":
    main()
