function clone(value) { if (typeof structuredClone === "function") return structuredClone(value); if (Array.isArray(value)) return value.map(clone); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, clone(v)])); return value; }
export function cloneDashboard(dashboard) { return clone(dashboard); }
export function collectIds(d) { return new Set([d?.id, ...(d?.views||[]).map(x=>x.id), ...(d?.sections||[]).map(x=>x.id), ...(d?.cards||[]).map(x=>x.id)].filter(Boolean)); }
export function createIdGenerator(prefix="node", sequence=[1]) { return (used=new Set()) => { let id; do { id = `${prefix}-${sequence[0]++}`; } while (used.has(id)); return id; }; }
function nextId(d, gen) { const id = gen(collectIds(d)); if (collectIds(d).has(id)) throw new Error(`Duplicate id: ${id}`); return id; }
function move(arr, id, delta) { const a=[...arr]; const i=a.indexOf(id); const j=i+delta; if(i<0||j<0||j>=a.length) return a; [a[i],a[j]]=[a[j],a[i]]; return a; }
function fields(obj, patch, names) { const out={...obj}; for (const n of names) if (Object.hasOwn(patch,n)) out[n]=patch[n]; return out; }
export function updateDashboardMetadata(d, patch) { return fields(clone(d), patch, ["title","description"]); }
export function addView(d, patch={}, gen=createIdGenerator("view")) { const draft=clone(d); const id=patch.id || nextId(draft, gen); draft.views=[...(draft.views||[]), { id, title: patch.title||"New view", description: patch.description||"", section_ids: [] }]; return draft; }
export function updateView(d,id,patch){ const draft=clone(d); draft.views=(draft.views||[]).map(v=>v.id===id?fields(v,patch,["title","description"]):v); return draft; }
export function removeView(d,id){ const draft=clone(d); const v=(draft.views||[]).find(x=>x.id===id); const secIds=new Set(v?.section_ids||[]); const cardIds=new Set((draft.sections||[]).filter(s=>secIds.has(s.id)).flatMap(s=>s.card_ids||[])); draft.views=(draft.views||[]).filter(v=>v.id!==id); draft.sections=(draft.sections||[]).filter(s=>!secIds.has(s.id)); draft.cards=(draft.cards||[]).filter(c=>!cardIds.has(c.id)); return draft; }
export function moveView(d,id,dir){ const draft=clone(d); const ids=move((draft.views||[]).map(v=>v.id),id,dir); draft.views=ids.map(i=>draft.views.find(v=>v.id===i)); return draft; }
export function addSection(d,viewId,patch={},gen=createIdGenerator("section")){ const draft=clone(d); const id=patch.id||nextId(draft,gen); draft.sections=[...(draft.sections||[]),{id,title:patch.title||"New section",description:patch.description||"",card_ids:[]}]; draft.views=(draft.views||[]).map(v=>v.id===viewId?{...v,section_ids:[...(v.section_ids||[]),id]}:v); return draft; }
export function updateSection(d,id,patch){ const draft=clone(d); draft.sections=(draft.sections||[]).map(s=>s.id===id?fields(s,patch,["title","description"]):s); return draft; }
export function removeSection(d,id){ const draft=clone(d); const s=(draft.sections||[]).find(x=>x.id===id); const cardIds=new Set(s?.card_ids||[]); draft.views=(draft.views||[]).map(v=>({...v,section_ids:(v.section_ids||[]).filter(x=>x!==id)})); draft.sections=(draft.sections||[]).filter(s=>s.id!==id); draft.cards=(draft.cards||[]).filter(c=>!cardIds.has(c.id)); return draft; }
export function moveSection(d,viewId,id,dir){ const draft=clone(d); draft.views=(draft.views||[]).map(v=>v.id===viewId?{...v,section_ids:move(v.section_ids||[],id,dir)}:v); return draft; }
export function addCard(d,sectionId,patch={},gen=createIdGenerator("card")){ const draft=clone(d); const id=patch.id||nextId(draft,gen); draft.cards=[...(draft.cards||[]),{id,title:patch.title||"New card",type:patch.type||"custom",config:patch.config&&typeof patch.config==="object"&&!Array.isArray(patch.config)?clone(patch.config):{}}]; draft.sections=(draft.sections||[]).map(s=>s.id===sectionId?{...s,card_ids:[...(s.card_ids||[]),id]}:s); return draft; }
export function updateCard(d,id,patch){ const draft=clone(d); draft.cards=(draft.cards||[]).map(c=>c.id===id?fields(c,patch,["title","type","config"]):c); return draft; }
export function removeCard(d,id){ const draft=clone(d); draft.sections=(draft.sections||[]).map(s=>({...s,card_ids:(s.card_ids||[]).filter(x=>x!==id)})); draft.cards=(draft.cards||[]).filter(c=>c.id!==id); return draft; }
export function moveCard(d,sectionId,id,dir){ const draft=clone(d); draft.sections=(draft.sections||[]).map(s=>s.id===sectionId?{...s,card_ids:move(s.card_ids||[],id,dir)}:s); return draft; }
export function parseCardConfig(text){ const value=JSON.parse(text||"{}"); if(!value||typeof value!=="object"||Array.isArray(value)) throw new Error("Card config must be a JSON object."); return value; }
