import { DEFAULT_WIDGET_REGISTRY } from "../widgets/registry.js";

const ENTITY_RE = /^[a-z0-9_]+\.[a-z0-9_]+$/;
const SIZES = ["small", "medium", "large", "full"];
function input(doc, labelText, value, onInput, attrs = {}) { const label = doc.createElement("label"); label.textContent = labelText; const field = doc.createElement("input"); field.value = value || ""; for (const [k,v] of Object.entries(attrs)) field.setAttribute(k, v); field.addEventListener("input", () => onInput(field.value)); label.append(field); return label; }
function check(doc, labelText, checked, onChange) { const label = doc.createElement("label"); label.textContent = labelText; const field = doc.createElement("input"); field.type = "checkbox"; field.checked = checked !== false; field.addEventListener("change", () => onChange(field.checked)); label.append(field); return label; }
function select(doc, labelText, value, options, onChange) { const label = doc.createElement("label"); label.textContent = labelText; const field = doc.createElement("select"); for (const opt of options) { const o = doc.createElement("option"); o.value = opt.value || opt; o.textContent = opt.label || opt; o.selected = o.value === value; field.append(o); } field.addEventListener("change", () => onChange(field.value)); label.append(field); return label; }
function csv(v) { return Array.isArray(v) ? v.join(", ") : ""; }
function split(v) { return String(v || "").split(",").map((x) => x.trim()).filter(Boolean); }
function configPatch(section, widget, controller, patch) { controller.updateWidget(section.id, widget.id, { config: { ...(widget.config || {}), ...patch } }); }
function entityList(doc, section, widget, controller, key = "entityIds") { return input(doc, "Entity IDs", csv(widget.config?.[key]), (value) => configPatch(section, widget, controller, { [key]: split(value) }), { "aria-invalid": split(csv(widget.config?.[key])).some((id) => !ENTITY_RE.test(id)) ? "true" : "false" }); }
function actionList(doc, section, widget, controller, key) { const raw = JSON.stringify(widget.config?.[key] || [], null, 2); const label = doc.createElement("label"); label.textContent = key; const ta = doc.createElement("textarea"); ta.value = raw; ta.addEventListener("input", () => { try { const parsed = JSON.parse(ta.value || "[]"); if (Array.isArray(parsed)) configPatch(section, widget, controller, { [key]: parsed }); ta.setAttribute("aria-invalid", "false"); } catch { ta.setAttribute("aria-invalid", "true"); } }); label.append(ta); return label; }
export function renderWidgetSpecificEditor(doc, section, widget, controller) { const panel = doc.createElement("div"); panel.className = "dashboardmodern-widget-specific-editor"; switch (widget.type) { case "home-hero": panel.append(input(doc, "Hero title", widget.config?.title, (title) => configPatch(section, widget, controller, { title })), input(doc, "Subtitle", widget.config?.subtitle, (subtitle) => configPatch(section, widget, controller, { subtitle })), check(doc, "Show date", widget.config?.showDate !== false, (showDate) => configPatch(section, widget, controller, { showDate })), check(doc, "Show time", widget.config?.showTime, (showTime) => configPatch(section, widget, controller, { showTime }))); break; case "weather-summary": panel.append(input(doc, "Weather entity", widget.config?.entityId, (entityId) => configPatch(section, widget, controller, { entityId }), { "aria-invalid": widget.config?.entityId && !ENTITY_RE.test(widget.config.entityId) ? "true" : "false" }), input(doc, "Displayed fields", csv(widget.config?.displayedFields), (v) => configPatch(section, widget, controller, { displayedFields: split(v) }))); break; case "home-status": panel.append(actionList(doc, section, widget, controller, "metrics")); break; case "alerts-summary": panel.append(actionList(doc, section, widget, controller, "rules")); break; case "quick-actions": panel.append(actionList(doc, section, widget, controller, "actions")); break; case "favorites": panel.append(actionList(doc, section, widget, controller, "items")); break; case "lights-summary": case "light-group": case "lights-overview": panel.append(entityList(doc, section, widget, controller)); break; case "light-tile": case "light-control-panel": panel.append(input(doc, "Light entity", widget.config?.entityId, (entityId) => configPatch(section, widget, controller, { entityId }), { "aria-invalid": widget.config?.entityId && !ENTITY_RE.test(widget.config.entityId) ? "true" : "false" })); break; default: panel.append(actionList(doc, section, widget, controller, "config")); }
  return panel; }
export function renderWidgetEditor(doc, section, controller, registry = DEFAULT_WIDGET_REGISTRY) { const panel = doc.createElement("section"); panel.className = "dashboardmodern-widget-editor"; const title = doc.createElement("h3"); title.textContent = "Widgets"; panel.append(title); if (!section) { panel.append(Object.assign(doc.createElement("p"), { textContent: "Select a section to edit widgets." })); return panel; } const catalog = registry.list().filter((d) => ["home", "lights"].includes(d.owner)); panel.append(select(doc, "Add widget", "", [{ value: "", label: "Choose widget…" }, ...catalog.map((d) => ({ value: d.type, label: d.displayName }))], (type) => { if (type) { const def = registry.get(type); controller.addWidget(section.id, { type, title: def.displayName, config: def.defaultConfig?.() || {}, layout: { size: def.supportedLayoutSizes?.[0] || "medium" } }); } })); for (const widget of section.config?.widgets || []) { const item = doc.createElement("article"); item.className = "dashboardmodern-widget-editor-item"; item.append(input(doc, "Title", widget.title || "", (title) => controller.updateWidget(section.id, widget.id, { title })), check(doc, "Enabled", widget.enabled !== false, (enabled) => controller.updateWidget(section.id, widget.id, { enabled })), select(doc, "Size", widget.layout?.size || "medium", SIZES.map((s) => ({ value: s, label: s })), (size) => controller.updateWidget(section.id, widget.id, { layout: { ...(widget.layout || {}), size } })), renderWidgetSpecificEditor(doc, section, widget, controller)); for (const [label, fn] of [["Move up",()=>controller.moveWidget(section.id, widget.id, -1)],["Move down",()=>controller.moveWidget(section.id, widget.id, 1)],["Duplicate",()=>controller.duplicateWidget(section.id, widget.id)],["Remove",()=>controller.removeWidget(section.id, widget.id)]]) { const b = doc.createElement("button"); b.type = "button"; b.textContent = label; b.addEventListener("click", fn); item.append(b); } panel.append(item); } return panel; }
