name: Clean temporary branch

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cleanup-noop-branch.yml"

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove temporary branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: git push "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" --delete noop-check-should-not-create
